### ISSUE TITLE
i could not use worker and worklist and run plugin not work.

### ISSUE THREAD

**Issue by notwhy** [owtf/owtf#1001]
## Expected Behavior

i can see and use worker and worklist
## Current Behavior

i could not use worker and worklist and run plugin not work. 

## Steps to Reproduce (for bugs)

i donot know how to reproduce this . so i make a gif to easily see my problem. 
https://ws1.sinaimg.cn/large/006tNbRwgy1fuzntkxhvdg31am0k2kjq.gif

## Logs

i could only see exception in /owtf_review/logs/MainProcess.log . any other seem fine 

[DEBUG] [2018-09-05 07:51:43,540] [File 'error.py', line 125, in log_and_exit_handler] - MainProcess: caught signal SIGINT, exiting

## Your Environment

* Installation method used:git
* Version/branch used:
* Operating System and version (like Kali, Debian, ArchLinux, etc):kali 2018
* pip/setuptools version:
* sudo access:

**Comment by viyatb** [comment]
Please use https://github.com/owtf/owtf/releases/tag/v2.4 for a working web interface. The web interface in the develop branch (latest) is undergoing a refactor.

**Comment by notwhy** [comment]
I use https://github.com/owtf/owtf/releases/tag/v2.4 for a working web interface
unfortunately. i met another problem.   

root@kali:~/owtf-2.4# python -m owtf
[-] Loading config from: /root/owtf-2.4/owtf/data/conf/framework.cfg..
ERROR:root:Aborted by Framework: Config file not found at: /root/owtf-2.4/owtf/conf/general.cfg

I use command locate resources.cfg  and found its in /root/owtf-2.4/owtf/data/conf/resources.cfg  so i correct it in framework.cfg then i was able to run .

but when i added some target and ran some plugins . no worker was running . i didnot see any logs. :( 
when i clicked Report Errors  on github . it said Currently no errors exists

**Comment by jakobsn** [comment]
Hello, I am having a similar issue. In addition I realized that after relaunching OWTF the tests could be seen in the logs, but not in the dashboard. Additional tests added after relaunch are moved to the worklist, however they are not moved further to workers until application relaunch. Something strange is also that even when OWTF-2.4 is launched it states version 2.3b in the log as seen below.  No error reports.

- Status in dashboard: Worker 1 - Not running

>>Indivudual target subpage shows:
----------------------------------------------------------------------------------------------------------------------
RUNTIME Successful
TIME INTERVAL 08/09/2018-16:2508/09/2018-16:25
STATUS Successful
OUTPUT FILES (directed to empty folder)
ACTIONS (delete or reload)
----------------------------------------------------------------------------------------------------------------------

>>Example for worker status:
----------------------------------------------------------------------------------------------------------------------
Worker 1
PID: 614
Start Time: N/A
Logs:
[INFO] [2018-09-08 16:25:43,071] [File 'plugin_handler.py', line 420, in process_plugin] - __________ 1 - Target: http://0.0.0.0:3000/#/search -> Plugin: Web Application Fingerprint (web/passive) __________
----------------------------------------------------------------------------------------------------------------------

>>Generated report:
----------------------------------------------------------------------------------------------------------------------
OWTF-IG-004 Web Application Fingerprint What is that site running?

Plugin type: passive(Unranked)
 	Plugin output here.
	Note: User notes here (Presently stored as HTML in DB so cannot be rendered)
----------------------------------------------------------------------------------------------------------------------

>>Console log:
----------------------------------------------------------------------------------------------------------------------
`$ sudo python -m owtf `
        @owtfp
    http://owtf.org
    
[-] Loading config from: /root/.owtf/conf/framework.cfg..
[*] OWTF Version: 2.3b, Release: MacinOWTF 
[-] Loading framework please wait..
[-] Loading Resources from: /root/.owtf/conf/resources.cfg..
[-] Loading Mapping from: /root/.owtf/conf/mappings.cfg..
[*] 127.0.0.1:8008 <-- HTTP(S) Proxy to which requests can be directed
[*] http://127.0.0.1:8009 <-- Web UI URL
[-] Press Ctrl+C when you spawned a shell ;)
[-] __________ 1 - Target: http://0.0.0.0:3000/#/search -> Plugin: Web Application Fingerprint (web/passive) __________
----------------------------------------------------------------------------------------------------------------------

**Comment by viyatb** [comment]
I'll open this there are any outstanding problems - to run OWTF in its latest state, run `python setup.py develop` and `owtf`. Make sure the PostgreSQL database is up by running `make startdb` (it requires ` docker` to be installed).
