### ISSUE TITLE
Improve installation / run for Windows users

### ISSUE THREAD

**Issue by black-snow** [owtf/owtf#1002]
Hi,

I'm bound to MS Windows (work PC) and trying to get owtf up and running. Sadly the docs seem somewhat incomplete in how to do so.

The **github readme** *Requirements* section mentions kali and macOS. If I only read this I'd think that there was no way to run owtf on Windows except via a kali VM. Then there's some installation information that does not apply and then it finishes with

> To run OWTF on Windows or MacOS, OWTF uses Docker Compose. You need to have Docker Compose installed (check by docker-compose -v). After installing Docker Compose, simply run make compose and open localhost:8009 for the OWTF web interface.

Surely it's not enough to just run `make compose` ... where shall I run this? There is no `make` on my windows machine. Shall I clone the git repo? There's no dockerfile in the root dir.

Then there is [this ](https://owtf.github.io/) page. Again no download mentioned and there's no `make` on Windows (by default).

Then there's the [wiki](https://github.com/owtf/owtf/wiki/OWASP-OWTF-Installation) - Windows not mentioned.

How do I get this to work on Windows? :|

P.S.: I've used docker once a couple years ago.

**Comment by black-snow** [comment]
Even more instructions: http://docs.owtf.org/en/latest/installation/methods.html

**Comment by black-snow** [comment]
Installation inside WSL fails with another error.

**Comment by viyatb** [comment]
I don't think Windows will ever get native support. You can either install in inside the embedded bash shell in Windows 10 (with Unix like tools installed).

**Comment by black-snow** [comment]
@viyatb Thanks for the reply. So what's the deal with the docker stuff?

**Comment by viyatb** [comment]
@black-snow if you can't run `make`, try running the `docker-compose` command manually,

 `docker-compose -f docker/docker-compose.dev.yml up`
