### ISSUE TITLE
Page is under construction

### ISSUE THREAD

**Issue by kj0317** [owtf/owtf#1010]
## Expected Behavior
cd /path/to/pentest/folder ; owtf (in python2.7 virtualenv)

         _____ _ _ _ _____ _____
        |     | | | |_   _|   __|
        |  |  | | | | | | |   __|
        |_____|_____| |_| |__|

            @owtfp
        http://owtf.org
        Version: 2.4.0
        
[+] Loading /home/kj0317/.owtf/conf/framework.yaml..
[+] Loading /home/kj0317/.owtf/conf/general.yaml..
[+] Loading resources from: /home/kj0317/.owtf/conf/resources.cfg..
[+] Loading framework please wait..
[!] Starting HTTP(s) proxy server at 127.0.0.1:8008
[!] Starting API and UI server at http://0.0.0.0:8009

Browse to http://0.0.0.0:8009 and begin testing, adding targets, etc.

## Current Behavior
cd /path/to/pentest/folder ; owtf (in python2.7 virtualenv)

         _____ _ _ _ _____ _____
        |     | | | |_   _|   __|
        |  |  | | | | | | |   __|
        |_____|_____| |_| |__|

            @owtfp
        http://owtf.org
        Version: 2.4.0
        
[+] Loading /home/kj0317/.owtf/conf/framework.yaml..
[+] Loading /home/kj0317/.owtf/conf/general.yaml..
[+] Loading resources from: /home/kj0317/.owtf/conf/resources.cfg..
[+] Loading framework please wait..
[!] Starting HTTP(s) proxy server at 127.0.0.1:8008
[!] Starting API and UI server at http://0.0.0.0:8009

Open browser at http://0.0.0.0:8009 and presented with login page. Click on Login, and it takes me to a white page that says, "Page is under construction". If I click on the TARGETS tab, the page briefly flashes the actual targets page, then goes all white and I'm presented with a blank page. 

Clicking on either the WORKERS or the WORKLIST tabs also shows "Page is under construction" message. All other tabs work. The OWTF Dashboard also does not display any information.

The same behaviour also happens when launched from within a python3 venv. This problem does not happen within docker, however.

## Possible Solution
?? It is entirely plausible that this issue is because I am not using Kali, I'm using Parrot, but I'm unsure.

## Steps to Reproduce (for bugs)
1. 
![image](https://user-images.githubusercontent.com/39319087/53257119-612fe080-3697-11e9-9f9b-00631300f93a.png)

2.
![image](https://user-images.githubusercontent.com/39319087/53257169-7efd4580-3697-11e9-97a2-9a7bc7262e48.png)

3.
![image](https://user-images.githubusercontent.com/39319087/53257198-93414280-3697-11e9-9497-b34dc28c642e.png)

## Logs
ui_server.log
https://pastebin.com/HqeJh1Qx

## Context
Just trying to get OWTF to work while installed locally instead of using it in a docker container.

## Your Environment

* Installation method used: python2.7 virtualenv, pip install git+https://github.com/owtf/owtf#egg=owtf
* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): Linux parrot 4.19.0-parrot1-13t-amd64 #1 SMP Debian 4.19.13-1parrot1.13t (2019-01-09) x86_64 GNU/Linux
* pip/setuptools version: pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)
* sudo access: Not using it when launching owtf but yes I have sudo on this machine.

**Comment by viyatb** [comment]
We are still in the process of porting over pages from mixed Jinja templating to pure React - keep an eye out!
