### ISSUE TITLE
gives an error if the current session is deleted without changing it.

### ISSUE THREAD

**Issue by dr3dd589** [owtf/owtf#1012]
- [x] bug
If we are using a current session and unfortunately deleted this without changing session then this gives an error.
## Possible Solution

we should make a default session so that if any session is deleted then it automatically set to default session.

## Steps to Reproduce (for bugs)

1. make a new session.
2. use this session .
3. delete this session without changing it.
4. gives an error because that session is deleted from database and currently none session is set as default.

![peek 2019-03-03 16-41](https://user-images.githubusercontent.com/31597172/53694470-8deda180-3dd5-11e9-8db6-93fed9cc107d.gif)

## Your Environment

* Installation method used:
* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): ubuntu
* pip/setuptools version:
* sudo access:

**Comment by viyatb** [comment]
This is fixed in the latest commit (https://github.com/owtf/owtf/commit/22b7dfb9d7bed5716b01da28c74b425835f85879).
