### ISSUE TITLE
Docker setup doesn't assign workers to any job in the worklist

### ISSUE THREAD

**Issue by ThunderSon** [owtf/owtf#1013]
## Expected Behavior
After adding jobs from target tab, items get added in the worklist and the targets get updated.
Workers should grab the items and start applying the rules on the given target.

## Current Behavior
After adding the targets, the items get added to the worklist. Workers stay idle and don't pick up any task to work on.

## Steps to Reproduce (for bugs)
1. Follow the docker steps to build the container.
1. Add 127.0.0.1 as the target and run all plugins.
1. Make sure that the items are added to the Worklist tab and that the workers are idle.

## Context
Simply trying to test the application out in the fastest manner possible, which is through docker.

## Notes
Pausing/resuming the tasks make no difference.

## Your Environment
Using Kali Linux 2019.1; followed the docker installation and it properly worked.

**Comment by propmasterb** [comment]
I'm having the same issue.  I'm running OWTF in Docker loaded on Kali Linux 2019.1.  I can launch OWTF through Docker, access the web interface and add targets (I added a local web application and OWASP's Juice Shop).  When I select a plugin from the targets tab and hit "run", i receive the confirmation message "Yup! Selected plugins launched, please check worklist to manage :D"

In the Worklist tab, I can see the selected plugins, but there's no indication of activity.  If I attempt to pause individual plugins, I receive the "Oops! Server replied: Internal Server Error".  If I select pause all, every plugin appears "paused", if I then select "resume all", they appear to be "running", but do not show any activity (no entry under Est. Time column) and the Workers are still sitting idle.  

If I attempt to start a single paused plugin, I get the "Oops!" message.

**Comment by viyatb** [comment]
@propmasterb can you paste the logs or paste them in a pastebin and link them here? They are stored in `owtf_review/logs` directory.

**Comment by viyatb** [comment]
Restarting OWTF should also work - kill all OWTF processes by `ps -ef | grep "owtf" | xargs kill -9 ` and restart OWTF.
