### ISSUE TITLE
The targets are getting refreshed/deleted on restarting the docker container

### ISSUE THREAD

**Issue by Ashishen** [owtf/owtf#1015]
The targets are getting refreshed/deleted on restarting the docker container

## Expected Behavior
The owtf container should persist the targets, the history of the plugins tested on the targets, etc even after restarting the container.

## Current Behavior
The sessions created in the target, the targets and the plugin history tested on the targets getting refreshed on restarting the docker container.

## Steps to Reproduce (for bugs)
1. start the container: docker start <docker_image_name>
2. open the owtf ui on browser and add session and target in the target field.
3. select a target and run the plugins from plugin list.
4. restart the container: docker start <docker_image_name>

## Context
Trying to implement some penetration testing for the APIs using the docker.

**Comment by viyatb** [comment]
Thanks for the report! You'll need to add attach a volume to persist data on your host - it should be as simple as adding something like 
```
volumes:
  - ./postgres-data:/var/lib/postgresql
```

to the `docker/docker-compose.yml` file.

**Comment by viyatb** [comment]
I added the Docker volume for PostgreSQL support in https://github.com/owtf/owtf/commit/79d955694859036e194f90b6e0f594a84ae0114e. All PostgreSQL data is saved in `${HOME}/.owtf/data`.

`git pull origin develop && python setup.py develop` should fix existing installations.
