### ISSUE TITLE
Page under is under constr

### ISSUE THREAD

**Issue by mokkastecher** [owtf/owtf#1032]
Hi, 

## Current Behavior
Webfronet doesnt work. When i go on Targets and Workes i got the Message: **Page is under construction.**

## Your Environment
* Installation method used: I installed OWTF with the manual on https://github.com/owtf/owtf
* Version/branch used: Version 2.60
* Operating System and version (like Kali, Debian, ArchLinux, etc): Kali 2019.2
* pip/setuptools version: newest form kali

**Comment by viyatb** [comment]
Please use the develop branch from Git. We are actively working on the new frontend there.
