### ISSUE TITLE
Check if the service that is going to be scanned speaks HTTP before launching ANY web test

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#108]
I've had a case where non-HTTP services (like SSH) were listening on HTTP ports (i.e. 80, 443). When this happens OWTF gets stuck forever since many of the tools launched will get stuck.

To avoid this, OWTF should be smarter and indicate that "this host does not speak HTTP" or similar and avoid running all the tests afterwards.

This check might perhaps be best implemented as a basic "GET / HTTP/1.1" request that most HTTP sites should have no option other than accept :).

**Comment by delta24** [comment]
I can confirm the "speaks" HTTPS check works now. Can you corroborate? @7a ?

**Comment by delta24** [comment]
Double checked - the `verify_ssl_cipher_check.sh` script in `scripts/ssl` directory correctly runs, and restricts any ssl tests if the target doesn't "speak" HTTPS. I'll reopen if a new issue pops up. :)
