### ISSUE TITLE
Frontend stuck at "Loading application".

### ISSUE THREAD

**Issue by EXTREMOPHILARUM** [owtf/owtf#1134]
The Latest version of node i.e. v16.0.0 is not supported by the node-saas package. This is resulting in the application frontend not loading.

## Expected Behavior
The page should load normally like the image below.
![image](https://user-images.githubusercontent.com/22239978/115780148-70755a80-a3d6-11eb-9413-e4eb1c9f2510.png)

## Current Behavior
Currently, the page is stuck at the loading page.
![image](https://user-images.githubusercontent.com/22239978/115776648-fcd14e80-a3d1-11eb-9c57-5c34a3fa2fdc.png)
In the Browser console we can observe the error.
![image](https://user-images.githubusercontent.com/22239978/115777347-c7793080-a3d2-11eb-97e9-acb3130cf019.png)

## Possible Solution
The node-saas package has been deprecated and a possible alternative for it is the dart-saas package. To use this package the framework will need a lot of modifications.

A temporary solution is lock the node version at 15.0.

## Steps to Reproduce (for bugs)
1. Clone the repo.
2. Run "docker-compose -f docker-compise.dev.yml up" in the cloned directory.

## Logs
https://gist.github.com/EXTREMOPHILARUM/1aa2f79866555eb808c918f5b8fa1446

## Your Environment
* Installation method used: Docker
* Version/branch used: develop
* Operating System and version : Kali, the latest update

**Comment by rahultalekar** [comment]
i am also getting same error is there any solution ? i have already tried the possible solution but it didn't work

**Comment by EXTREMOPHILARUM** [comment]
Hi @rahultalekar,
Can you please specify what you have tried?

**Comment by rahultalekar** [comment]
hi @EXTREMOPHILARUM,
i rebuild the node-sass also install nodejs version 15. but i am getting still same error. my current node-saas version is @6.00. can you provide your solution step by step here ?

**Comment by EXTREMOPHILARUM** [comment]
Hi @rahultalekar,
If you are trying to install on your base system, uninstall the previously install latest version, then run the script, and if you are doing it in docker, rebuilding the image should solve it.

**Comment by rahultalekar** [comment]
hi @EXTREMOPHILARUM , yes i have tried to rebuild the image but its not working can you provide step to rebuild image, it will be very helpful

**Comment by rahultalekar** [comment]
@EXTREMOPHILARUM hey build is not working can you provide steps ? is workaround worked for you ?

**Comment by EXTREMOPHILARUM** [comment]
Hi @rahultalekar, Contact me on the OWASP slack or telegram. My handle is @EXTREMOPHILARUM.

**Comment by tarunkant** [comment]
I am also having the same problem

**Comment by EXTREMOPHILARUM** [comment]
You can check [this](https://github.com/owtf/owtf/pull/1135) PR.

**Comment by EXTREMOPHILARUM** [comment]
PR merged closing issue.
