### ISSUE TITLE
Investigate integration with Vivek's search engine

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#116]
Vivek Ramachandran talked about a tool he is working on that we should be able to integrate with very well (i.e. for example, our passive plugins would open tabs that look for CSRF, HTML comments, etc. PASSIVELY). I will try to contact him next week.

Related PaulDotCom Episode: http://pauldotcom.com/wiki/index.php/Episode346
Security Tube: http://www.securitytube.net/
Personal site: http://www.vivekramachandran.com/

UPDATE 2014/01/03:  Vivek contacted (via @gmail account)
UPDATE 2014/01/31:  Vivek contacted again (via @secbinarysolutions account)

**Comment by delta24** [comment]
@7a I checked his homepage, and the SecurityTube website. I don't think there is any such tool.
