### ISSUE TITLE
make compose error

### ISSUE THREAD

**Issue by leo-mercier** [owtf/owtf#1185]
I'm trying to install owtf for 1 day. I'm unable to make compose. I need OWTF for my certification course.

here is the output of the error:

![image](https://user-images.githubusercontent.com/50695235/171192810-fe1f8edd-1a41-46ce-8d12-8efd5efb1cf4.png)

**Comment by leo-mercier** [comment]
i have tried on 3 diferent linux system

**Comment by mrchainman** [comment]
I created a Fork which fixes the Dockerfile here https://github.com/mrchainman/owtf/
I will make a PR, in the meantime you can use my version.
