### ISSUE TITLE
Evaluate the value of OWASP O-shaft and decide if is worth adding to OWTF or not

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#120]
There is a project called OWASP O-shaft that seems to test for a number of SSL weaknesses:
https://www.owasp.org/index.php/O-Saft

We are already doing this in the SSL plugin, the passive one uses ssllabs which is awesome, but sometimes websites are not public yet or they are on a port different from 443 so ssllabs is not an option. The active plugin runs both tlssled and ssl-cipher-check with some additional checks such as renegotiation, etc.

So, under this issue, we would like to test O-Saft and see if it does something that owtf is not doing at the moment, and if so, add it to the list of ssl commands to run.

Potential approach: We might be able to tweak the openssl version of Kali to support SSLv2 and make O-Shaft and sslyze work. The reason for this is that It seems that there are some problems to run O-Saft and sslyze on Kali based on some testing by Jim Kelly (thanks!):

OWTF cannot test for SSLv2 on server using either sslyze or o-saft at least on Kali because Kali ships with a version of Openssl with SSLv2 disabled.

 SCAN RESULTS FOR GOOGLE.COM:443 - 74.125.228.96:443
 ---------------------------------------------------

Unhandled exception when processing --sslv2: 
utils.ctSSL.errors.ctSSLFeatureNotAvailable - SSLv2 disabled.

also o-saft doesn’t appear to work at all on Kali it errors out:
**WARNING: SSL version 'SSLv2' not supported by openssl; ignored
==== Target: google.com:443 ====

**WARNING: Can't do DNS reverse lookup: for google.com: <<gethostbyaddr() failed>>; ignored at o-saft.pl line 4220, <DATA> line 1983.

fails on dns lookup and then hangs forever and dosn’t run.

-------------------------------------

IMPORTANT: (Below is courtesy of Jim Kelly, thank you!)

I checked the Kali bug reporting system and it appears that others have also noticed this problem

https://bugs.kali.org/view.php?id=146

The Kali SSLv2 issue conflicts with a previous Debian bug report as expected

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=589706

One idea might be to package OWTF with a custom built version of openssl with SSLv2 supported and compiled in then calling that instead of the Kali installed version.

**Comment by DePierre** [comment]
O-saft has been included in OWTF thanks to @Ahiknsr via 171ee5050e2bdf72c53d8f2e023f7434e7d75e51.
