### ISSUE TITLE
"OWTF-ABrF-001" BUG

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#125]
root@localhost:~/owtf# ./owtf.py -o 'OWTF-ABrF-001'

                  __       ___  
                 /\ \__  /'___\ 
  ___   __  __  _\ \ ,_\/\ \__/ 
 / __`\/\ \/\ \/\ \ \ \/\ \ ,__\ 
/\ \_\ \ \ \_/ \_/ \ \ \_\ \ \_/
\ \____/\ \___x___/'\ \__\\ \_\ 
 \/___/  \/__//__/   \/__/ \/_/ 

OWTF Version: 0.40, Release: Summer Storm III 

[*] Defaulting Plugin Group to 'aux' based on list of plugins supplied
[*] Loading framework please wait..
[*] Loading Config from: /root/owtf/profiles/general/default.cfg ..
[*] Loading Resources from: /root/owtf/profiles/resources/default.cfg ..
[*] Loading net Plugin Order from: /root/owtf/profiles/net_plugin_order/default.cfg ..
[*] Loading web Plugin Order from: /root/owtf/profiles/web_plugin_order/default.cfg ..
[*] SUCCESS: Integrity Check successful -> All tools were found
[*] Loading/Initialising database ..
[*] HTML ID DB is empty, initialising..
[*] SEED DB is empty, initialising..
[*] Starting Inbound proxy at 127.0.0.1:8008
[*] Starting Transaction logger process
[*] Setting up proxy(inbound) for OWTF requests..
[*] Proxy transaction's log file at /tmp/owtf/11162/proxy.log
[*] Visit http://127.0.0.1:8008/proxy to use Plug-n-Hack standard
[*] Execution of OWTF is halted.You can browse through OWTF proxy) Press Enter to continue with OWTF
                                                                                       
[*] Proxy Check: Avoid logging request again if already in DB..                        
{'URL': 'http://www.google.ie'} in DB: False                                           
[*] Proxy Check OK: The proxy appears to be working                                    
__________ 1 - Target: aux -> Plugin: Password Bruteforce (bruteforce) __________      
[*] Could not default not passed: 'CATEGORY' (Default order is: ['OWTF-ABrF-001_bruteforce_CATEGORY', 'OWTF-ABrF-001_CATEGORY', 'CATEGORY'])                                  
[*]                                                                                    
[*] ____________________________________________________________________________________________________                                                                      
[*]                                                                                    
[*] USER ERROR: Plugin: bruteforce/Password_Bruteforce@OWTF-ABrF-001.py requires argument: 'CATEGORY'                                                                         
[*] ****************************************************************************************************                                                                      
[*]                                                                                    
[*] Defaulted not passed 'ONLINE_USER_LIST' to '/root/owtf/dictionaries/users/basic_windows.txt' (Default order is: ['OWTF-ABrF-001_bruteforce_ONLINE_USER_LIST', 'OWTF-ABrF-001_ONLINE_USER_LIST', 'ONLINE_USER_LIST'])                                             
[*] Defaulted not passed 'BRUTEFORCER' to 'hydra' (Default order is: ['OWTF-ABrF-001_bruteforce_BRUTEFORCER', 'OWTF-ABrF-001_BRUTEFORCER', 'BRUTEFORCER'])
[*] Defaulted not passed 'CONNECT_WAIT' to '30' (Default order is: ['OWTF-ABrF-001_bruteforce_CONNECT_WAIT', 'OWTF-ABrF-001_CONNECT_WAIT', 'CONNECT_WAIT'])
[*] Defaulted not passed 'THREADS' to '1' (Default order is: ['OWTF-ABrF-001_bruteforce_THREADS', 'OWTF-ABrF-001_THREADS', 'THREADS'])
[*] Defaulted not passed 'REPEAT_DELIM' to ',' (Default order is: ['OWTF-ABrF-001_bruteforce_REPEAT_DELIM', 'OWTF-ABrF-001_REPEAT_DELIM', 'REPEAT_DELIM'])
[*] Defaulted not passed 'RESPONSE_WAIT' to '40' (Default order is: ['OWTF-ABrF-001_bruteforce_RESPONSE_WAIT', 'OWTF-ABrF-001_RESPONSE_WAIT', 'RESPONSE_WAIT'])
[*] Defaulted not passed 'ONLINE_PASSWORD_LIST' to '/root/owtf/dictionaries/restricted/passwords/phpbb.txt' (Default order is: ['OWTF-ABrF-001_bruteforce_ONLINE_PASSWORD_LIST', 'OWTF-ABrF-001_ONLINE_PASSWORD_LIST', 'ONLINE_PASSWORD_LIST'])
[*] 
[*] ERROR: Aborting argument processing, please correct the errors above and try again
[*] 
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] OWTF BUG: Please report the sanitised information below to help make this better. Thank you.
[*] ****************************************************************************************************
[*] 
[*] Message: Plugin bruteforce/Password_Bruteforce@OWTF-ABrF-001.py failed for target aux
[*] 
[*] Command: owtf.py -o OWTF-ABrF-001
[*] 
[*] Error Trace:
[*] Traceback (most recent call last):
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 272, in ProcessPlugin
[*]     output = self.RunPlugin(PluginDir, Plugin)
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 251, in RunPlugin
[*]     self.SavePluginInfo(PluginOutput, Plugin) # Timer retrieved here
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 369, in SavePluginInfo
[*]     self.Core.Reporter.SavePluginReport(PluginOutput, Plugin) # Timer retrieved by Reporter
[*] 
[*]   File "/root/owtf/framework/report/reporter.py", line 143, in SavePluginReport
[*]     + "p" + self.CCG('PORT_NUMBER'),
[*] 
[*] AttributeError: 'NoneType' object has no attribute 'replace'
[*] 
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] 
Process Worker-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/owtf/framework/plugin/ProcessManager.py", line 76, in run
    self.Core.PluginHandler.ProcessPlugin(pluginDir, plugin, self.status)
  File "/root/owtf/framework/plugin/plugin_handler.py", line 297, in ProcessPlugin
    self.SavePluginInfo(self.Core.Error.Add("Plugin "+Plugin['Type']+"/"+Plugin['File']+" failed for target "+self.Core.Config.Get('TARGET')), Plugin) # Try to save something
  File "/root/owtf/framework/plugin/plugin_handler.py", line 369, in SavePluginInfo
    self.Core.Reporter.SavePluginReport(PluginOutput, Plugin) # Timer retrieved by Reporter
  File "/root/owtf/framework/report/reporter.py", line 143, in SavePluginReport
    + "p" + self.CCG('PORT_NUMBER'),
AttributeError: 'NoneType' object has no attribute 'replace'
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] OWTF BUG: Please report the sanitised information below to help make this better. Thank you.
[*] ****************************************************************************************************
[*] 
[*] Message: Unknown owtf error
[*] 
[*] Command: owtf.py -o OWTF-ABrF-001
[*] 
[*] Error Trace:
[*] Traceback (most recent call last):
[*] 
[*]   File "./owtf.py", line 337, in run_owtf
[*]     if Core.Start(args):
[*] 
[*]   File "/root/owtf/framework/core.py", line 254, in Start
[*]     return self.run_plugins()
[*] 
[*]   File "/root/owtf/framework/core.py", line 296, in run_plugins
[*]     Status = self.PluginHandler.ProcessPlugins()
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 304, in ProcessPlugins
[*]     self.ProcessPluginsForTargetList(self.PluginGroup, Status, self.Core.Config.GetAll('TARGET'))
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 351, in ProcessPluginsForTargetList
[*]     self.ProcessManager.manageProcess()
[*] 
[*]   File "/root/owtf/framework/plugin/ProcessManager.py", line 177, in manageProcess
[*]     self.spawnworker()
[*] 
[*] AttributeError: ProcessManager instance has no attribute 'spawnworker'
[*] 
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] 
[*] Saving DBs
[*] Finishing iteration and assembling report again (with updated run information)
[*] owtf iteration finished
[*] Stopping inbound proxy processes and cleaning up, Please wait!
None

**Comment by delta24** [comment]
@marioskourtesis The plugin "OWTF-ABrF-001" does  not exist in the current OWTF codebase. Can you check once again?

**Comment by 7a** [comment]
aux plugins are called via the CLI, since that is usually what makes the most sense here! :)
The problem, in my view, based on the dump above is that the framework abort section is not working after the following line (from the dump above):
[] ERROR: Aborting argument processing, please correct the errors above and try again

**Comment by delta24** [comment]
This was before the restructuring of the Core object and many fixes. Plus as of now, `aux` plugins are not working. Should I close this + similar issues and create a meta-issue as a reference when the `aux` plugins are fixed? @7a @marioskourtesis ?

**Comment by delta24** [comment]
Meta-issue for all auxiliary plugins is https://github.com/owtf/owtf/issues/602 and this is fixed in 763660a6975a081ae9a5f31172fe415cc0bd93f5.
