### ISSUE TITLE
fuzzing bug at 'OWTF-ADoS-001' plugin

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#126]
root@localhost:~/owtf# ./owtf.py -o 'OWTF-ADoS-001' localhost/login.php

                  __       ___  
                 /\ \__  /'___\ 
  ___   __  __  _\ \ ,_\/\ \__/ 
 / __`\/\ \/\ \/\ \ \ \/\ \ ,__\ 
/\ \_\ \ \ \_/ \_/ \ \ \_\ \ \_/
\ \____/\ \___x___/'\ \__\\ \_\ 
 \/___/  \/__//__/   \/__/ \/_/ 

OWTF Version: 0.40, Release: Summer Storm III 

[*] Defaulting Plugin Group to 'aux' based on list of plugins supplied
[*] Loading framework please wait..
[*] Loading Config from: /root/owtf/profiles/general/default.cfg ..
[*] Loading Resources from: /root/owtf/profiles/resources/default.cfg ..
[*] Loading net Plugin Order from: /root/owtf/profiles/net_plugin_order/default.cfg ..
[*] Loading web Plugin Order from: /root/owtf/profiles/web_plugin_order/default.cfg ..
[*] SUCCESS: Integrity Check successful -> All tools were found
[*] Loading/Initialising database ..
[*] Starting Inbound proxy at 127.0.0.1:8008
[*] Starting Transaction logger process
[*] Setting up proxy(inbound) for OWTF requests..
[*] Proxy transaction's log file at /tmp/owtf/11868/proxy.log
[*] Visit http://127.0.0.1:8008/proxy to use Plug-n-Hack standard
[*] Execution of OWTF is halted.You can browse through OWTF proxy) Press Enter to continue with OWTF

[*] Proxy Check: Avoid logging request again if already in DB..
{'URL': 'http://www.google.ie'} in DB: False
[*] Proxy Check OK: The proxy appears to be working
Adding new EXTERNAL URL to EXTERNAL vetted DB: https://www.google.ie/
New owtf HTTP Transaction: 1 - 0s, 387ms - 200 OK - GET - https://www.google.ie/
__________ 1 - Target: aux -> Plugin: Direct Dos Launcher (dos) __________
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] USER ERROR: ['localhost/login.php'] arguments should be in NAME=VALUE format
[*] ****************************************************************************************************
[*] 
[*] Defaulted not passed 'CATEGORY' to 'HTTP_WIN,HTTP,SSL,TCP' (Default order is: ['OWTF-ADoS-001_dos_CATEGORY', 'OWTF-ADoS-001_CATEGORY', 'CATEGORY'])
[*] Defaulted not passed 'REPEAT_DELIM' to ',' (Default order is: ['OWTF-ADoS-001_dos_REPEAT_DELIM', 'OWTF-ADoS-001_REPEAT_DELIM', 'REPEAT_DELIM'])
[*] 
[*] ERROR: Aborting argument processing, please correct the errors above and try again
[*] 
Adding new EXTERNAL URL to EXTERNAL vetted DB: http://www.google.ie
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] OWTF BUG: Please report the sanitised information below to help make this better. Thank you.
[*] ****************************************************************************************************
[*] 
[*] Message: Plugin dos/Direct_DoS_Launcher@OWTF-ADoS-001.py failed for target aux
[*] 
[*] Command: owtf.py -o OWTF-ADoS-001 localhost/login.php
[*] 
[*] Error Trace:
[*] Traceback (most recent call last):
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 272, in ProcessPlugin
[*]     output = self.RunPlugin(PluginDir, Plugin)
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 251, in RunPlugin
[*]     self.SavePluginInfo(PluginOutput, Plugin) # Timer retrieved here
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 369, in SavePluginInfo
[*]     self.Core.Reporter.SavePluginReport(PluginOutput, Plugin) # Timer retrieved by Reporter
[*] 
[*]   File "/root/owtf/framework/report/reporter.py", line 143, in SavePluginReport
[*]     + "p" + self.CCG('PORT_NUMBER'),
[*] 
[*] AttributeError: 'NoneType' object has no attribute 'replace'
[*] 
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] 
Process Worker-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/owtf/framework/plugin/ProcessManager.py", line 76, in run
    self.Core.PluginHandler.ProcessPlugin(pluginDir, plugin, self.status)
  File "/root/owtf/framework/plugin/plugin_handler.py", line 297, in ProcessPlugin
    self.SavePluginInfo(self.Core.Error.Add("Plugin "+Plugin['Type']+"/"+Plugin['File']+" failed for target "+self.Core.Config.Get('TARGET')), Plugin) # Try to save something
  File "/root/owtf/framework/plugin/plugin_handler.py", line 369, in SavePluginInfo
    self.Core.Reporter.SavePluginReport(PluginOutput, Plugin) # Timer retrieved by Reporter
  File "/root/owtf/framework/report/reporter.py", line 143, in SavePluginReport
    + "p" + self.CCG('PORT_NUMBER'),
AttributeError: 'NoneType' object has no attribute 'replace'
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] OWTF BUG: Please report the sanitised information below to help make this better. Thank you.
[*] ****************************************************************************************************
[*] 
[*] Message: Unknown owtf error
[*] 
[*] Command: owtf.py -o OWTF-ADoS-001 localhost/login.php
[*] 
[*] Error Trace:
[*] Traceback (most recent call last):
[*] 
[*]   File "./owtf.py", line 337, in run_owtf
[*]     if Core.Start(args):
[*] 
[*]   File "/root/owtf/framework/core.py", line 254, in Start
[*]     return self.run_plugins()
[*] 
[*]   File "/root/owtf/framework/core.py", line 296, in run_plugins
[*]     Status = self.PluginHandler.ProcessPlugins()
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 304, in ProcessPlugins
[*]     self.ProcessPluginsForTargetList(self.PluginGroup, Status, self.Core.Config.GetAll('TARGET'))
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 351, in ProcessPluginsForTargetList
[*]     self.ProcessManager.manageProcess()
[*] 
[*]   File "/root/owtf/framework/plugin/ProcessManager.py", line 177, in manageProcess
[*]     self.spawnworker()
[*] 
[*] AttributeError: ProcessManager instance has no attribute 'spawnworker'
[*] 
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] 
[*] Saving DBs
New owtf HTTP Transaction: 2 - 0s,  37ms - 302 Found - GET - http://www.google.ie
[*] Finishing iteration and assembling report again (with updated run information)
[*] owtf iteration finished
[*] Stopping inbound proxy processes and cleaning up, Please wait!
None

**Comment by delta24** [comment]
@marioskourtesis  Same here. Is this still applicable? Can you check?

**Comment by 7a** [comment]
it seems as if the aux plugin framework abort section was not working, OWTF should have aborted after this due to missing parameters to the aux plugin (from dump above):

[] USER ERROR: ['localhost/login.php'] arguments should be in NAME=VALUE format
[] ***************************************************************************************************
[] 
[] Defaulted not passed 'CATEGORY' to 'HTTP_WIN,HTTP,SSL,TCP' (Default order is: ['OWTF-ADoS-001_dos_CATEGORY', 'OWTF-ADoS-001_CATEGORY', 'CATEGORY'])
[] Defaulted not passed 'REPEAT_DELIM' to ',' (Default order is: ['OWTF-ADoS-001_dos_REPEAT_DELIM', 'OWTF-ADoS-001_REPEAT_DELIM', 'REPEAT_DELIM'])
[] 
[] ERROR: Aborting argument processing, please correct the errors above and try again

**Comment by delta24** [comment]
Ok, I'll check that :)

**Comment by delta24** [comment]
Meta-issue for all auxiliary plugins is https://github.com/owtf/owtf/issues/602 and this is fixed in 763660a6975a081ae9a5f31172fe415cc0bd93f5.
