### ISSUE TITLE
Spear_Phishing plugin bug

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#128]
./owtf.py -f -o Spear_Phishing PHISHING_PAYLOAD=5 O

                  __       ___  
                 /\ \__  /'___\ 
  ___   __  __  _\ \ ,_\/\ \__/ 
 / __`\/\ \/\ \/\ \ \ \/\ \ ,__\ 
/\ \_\ \ \ \_/ \_/ \ \ \_\ \ \_/
\ \____/\ \___x___/'\ \__\\ \_\ 
 \/___/  \/__//__/   \/__/ \/_/ 

OWTF Version: 0.40, Release: Summer Storm III 

[*] Defaulting Plugin Group to 'aux' based on list of plugins supplied
[*] Loading framework please wait..
[*] Loading Config from: /root/owtf/profiles/general/default.cfg ..
[*] Loading Resources from: /root/owtf/profiles/resources/default.cfg ..
[*] Loading net Plugin Order from: /root/owtf/profiles/net_plugin_order/default.cfg ..
[*] Loading web Plugin Order from: /root/owtf/profiles/web_plugin_order/default.cfg ..
[*] SUCCESS: Integrity Check successful -> All tools were found
[*] Loading/Initialising database ..
[*] Starting Inbound proxy at 127.0.0.1:8008
[*] Starting Transaction logger process
[*] Setting up proxy(inbound) for OWTF requests..
[*] Proxy transaction's log file at /tmp/owtf/17009/proxy.log
[*] Visit http://127.0.0.1:8008/proxy to use Plug-n-Hack standard
[*] Execution of OWTF is halted.You can browse through OWTF proxy) Press Enter to continue with OWTF

[*] Proxy Check: Avoid logging request again if already in DB..
{'URL': 'http://www.google.ie'} in DB: True
[*] Proxy Check OK: The proxy appears to be working
[*] 
[*] Information for Plugin: se/Spear_Phishing@OWTF-ASEP-001.py
[*] 
[*] Description: Spear Phishing Testing plugin
[*] 
[*] Mandatory parameters:
[*] - MSF_LISTENER_PORT_____________Port where metasploit multi-handler will be listening to get the shells back
[*] - MSF_LISTENER_SETUP____________Setup the listener (yes/no): "no" can be useful when the goal is IDS testing
[*] - WORD_TEMPLATE_________________Word Template file to use for some of the SET payloads that need it/can use it
[*] - PHISHING_SCRIPT_DIR___________The directory where the SET phishing wrapper scripts are located
[*] - SMTP_LOGIN____________________Login to use to connect to the SMTP server
[*] - SMTP_PORT_____________________SMTP Port to connect to to send the emails
[*] - SMTP_HOST_____________________SMTP Host name or IP address to use to send emails
[*] - EMAIL_PRIORITY________________Send emails with high importance (use "yes") or no (use "no")
[*] - MSF_LISTENER_IP_______________IP where metasploit multi-handler will be listening to get the shells back
[*] - SMTP_PASS_____________________SMTP Password to use to connect to the SMTP server
[*] - EMAIL_TARGET__________________Email or File containing the target email addresses for phishing attacks
[*] - PDF_TEMPLATE__________________PDF Template file to use for some of the SET payloads that need it/can use it
[*] - ATTACHMENT_NAME_______________Filename for the attachment to be sent
[*] - SET_FILE_EXTENSION_ATTACK_____The SET file extension attack to carry out (1-17) -only relevant for 1_rar,1_zip,1_rce,1_zce-
[*] - SET_EMAIL_TEMPLATE____________SET Email template number to use (1-9)
[*] - EMAIL_FROM____________________Source email address to use for phishing attacks
[*] - PHISHING_PAYLOAD______________SET Payload for the phishing attack (1-18)
[*] 
[*] Optional parameters:
[*] - PHISHING_CUSTOM_EXE_PAYLOAD_DIRDirectory to store custom SET payloads (custom exes, etc)
[*] - ISHELL_DELAY_BETWEEN_COMMANDS_<secs> number of seconds to wait between commands
[*] - ISHELL_COMMANDS_BEFORE_EXIT___Commands to be run before exiting interactive shell
[*] - ISHELL_COMMANDS_BEFORE_EXIT_DELIMDelimiting character to indicate new commands
[*] - PHISHING_CUSTOM_EXE_PAYLOAD___Custom EXE to use for SET/Phishing
[*] - REPEAT_DELIM__________________Delimiter to repeat the command (i.e. "," -> Means RHOST=1,2 will execute for 1, then 2.\nRHOST=1,2 RPORT=3,4 will execute for RHOST=1 RPORT=3, then RHOST=2 RPORT=3, then RHOST=1 RPORT=4, then RHOST=2 RPORT=4)
[*] - ISHELL_EXIT_METHOD____________<kill/wait> kill or wait for shell to exit
[*] 
[*] Usage: PHISHING_SCRIPT_DIR=? PHISHING_CUSTOM_EXE_PAYLOAD_DIR=? SMTP_HOST=? MSF_LISTENER_IP=? REPEAT_DELIM=? EMAIL_FROM=? PHISHING_PAYLOAD=? ISHELL_DELAY_BETWEEN_COMMANDS=? ISHELL_COMMANDS_BEFORE_EXIT=? SMTP_PORT=? ISHELL_EXIT_METHOD=? SMTP_LOGIN=? MSF_LISTENER_SETUP=? MSF_LISTENER_PORT=? PDF_TEMPLATE=? SET_FILE_EXTENSION_ATTACK=? EMAIL_PRIORITY=? WORD_TEMPLATE=? ISHELL_COMMANDS_BEFORE_EXIT_DELIM=? SMTP_PASS=? PHISHING_CUSTOM_EXE_PAYLOAD=? EMAIL_TARGET=? ATTACHMENT_NAME=? SET_EMAIL_TEMPLATE=? 
[*] 
[*] Aborted by Framework: User is only viewing options, exiting
[*] Saving DBs
__________ 1 - Target: aux -> Plugin: Spear Phishing (se) __________
New owtf HTTP Transaction: 3 - 0s, 361ms - 200 OK - GET - https://www.google.ie/
[*] owtf iteration finished
[*] Stopping inbound proxy processes and cleaning up, Please wait!
None
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] OWTF BUG: Please report the sanitised information below to help make this better. Thank you.
[*] ****************************************************************************************************
[*] 
[*] Message: Plugin se/Spear_Phishing@OWTF-ASEP-001.py failed for target aux
[*] 
[*] Command: owtf.py -f -o Spear_Phishing PHISHING_PAYLOAD=5 O
[*] 
[*] Error Trace:
[*] Traceback (most recent call last):
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 272, in ProcessPlugin
[*]     output = self.RunPlugin(PluginDir, Plugin)
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 249, in RunPlugin
[*]     PluginOutput = self.GetModule("", Name, Path+"/").run(self.Core, Plugin)
[*] 
[*]   File "/root/owtf/plugins/aux/se/Spear_Phishing@OWTF-ASEP-001.py", line 62, in run
[*]     } }, PluginInfo):
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_params.py", line 198, in GetArgs
[*]     self.ShowParamInfo(FullArgList, Plugin)
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_params.py", line 83, in ShowParamInfo
[*]     self.Core.Error.FrameworkAbort("User is only viewing options, exiting", False)
[*] 
[*]   File "/root/owtf/framework/error_handler.py", line 53, in FrameworkAbort
[*]     self.Core.Finish(Message, Report)
[*] 
[*]   File "/root/owtf/framework/core.py", line 345, in Finish
[*]     self.reporting_process.join()
[*] 
[*]   File "/usr/lib/python2.7/multiprocessing/process.py", line 143, in join
[*]     assert self._parent_pid == os.getpid(), 'can only join a child process'
[*] 
[*] AssertionError: can only join a child process
[*] 
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] 
Process Worker-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/owtf/framework/plugin/ProcessManager.py", line 76, in run
    self.Core.PluginHandler.ProcessPlugin(pluginDir, plugin, self.status)
  File "/root/owtf/framework/plugin/plugin_handler.py", line 297, in ProcessPlugin
    self.SavePluginInfo(self.Core.Error.Add("Plugin "+Plugin['Type']+"/"+Plugin['File']+" failed for target "+self.Core.Config.Get('TARGET')), Plugin) # Try to save something
  File "/root/owtf/framework/plugin/plugin_handler.py", line 369, in SavePluginInfo
    self.Core.Reporter.SavePluginReport(PluginOutput, Plugin) # Timer retrieved by Reporter
  File "/root/owtf/framework/report/reporter.py", line 143, in SavePluginReport
    + "p" + self.CCG('PORT_NUMBER'),
AttributeError: 'NoneType' object has no attribute 'replace'
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] OWTF BUG: Please report the sanitised information below to help make this better. Thank you.
[*] ****************************************************************************************************
[*] 
[*] Message: Unknown owtf error
[*] 
[*] Command: owtf.py -f -o Spear_Phishing PHISHING_PAYLOAD=5 O
[*] 
[*] Error Trace:
[*] Traceback (most recent call last):
[*] 
[*]   File "./owtf.py", line 337, in run_owtf
[*]     if Core.Start(args):
[*] 
[*]   File "/root/owtf/framework/core.py", line 254, in Start
[*]     return self.run_plugins()
[*] 
[*]   File "/root/owtf/framework/core.py", line 296, in run_plugins
[*]     Status = self.PluginHandler.ProcessPlugins()
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 304, in ProcessPlugins
[*]     self.ProcessPluginsForTargetList(self.PluginGroup, Status, self.Core.Config.GetAll('TARGET'))
[*] 
[*]   File "/root/owtf/framework/plugin/plugin_handler.py", line 351, in ProcessPluginsForTargetList
[*]     self.ProcessManager.manageProcess()
[*] 
[*]   File "/root/owtf/framework/plugin/ProcessManager.py", line 177, in manageProcess
[*]     self.spawnworker()
[*] 
[*] AttributeError: ProcessManager instance has no attribute 'spawnworker'
[*] 
[*] 
[*] ____________________________________________________________________________________________________
[*] 
[*] 
[*] Saving DBs
[*] Finishing iteration and assembling report again (with updated run information)
[*] owtf iteration finished
[*] Stopping inbound proxy processes and cleaning up, Please wait!

**Comment by delta24** [comment]
The framework has changed since and all auxiliary plugin fixes are in this PR - https://github.com/owtf/owtf/pull/690.
