### ISSUE TITLE
Generate script for creating CA custom OpenVAS during installation

### ISSUE THREAD

**Issue by firebitsbr** [owtf/owtf#170]
![selection_014](https://f.cloud.github.com/assets/1431005/2337398/1c507be6-a49d-11e3-9507-806844e05b8d.png)
Actually it's not an issue, but create a script where you can enter information that will be in CA for OpenVAS because it is using default settings:

Country Name (2 letter code) [DE]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (eg, your name or your server's hostname) []:Email Address []:Using configuration from /tmp/openvas-mkcert-client.2282/stdC.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
countryName           :PRINTABLE:'DE'
localityName          :PRINTABLE:'Berlin'
commonName            :PRINTABLE:'om'
Certificate is to be certified until Mar  5 19:21:43 2015 GMT (365 days)

@firebitsbr

**Comment by delta24** [comment]
OpenVAS plugin was removed from the codebase in https://github.com/owtf/owtf/commit/15cc790277e45d2a29233bd8660ba4ff38f4632b. This was partly because it was difficult to control and was consumed too much resources.
