### ISSUE TITLE
OWTF Installation Improvement

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#192]
Recently i tried to make a fresh installation of OWTF. The installation process takes too much time. Is there any way to make the installation faster? 
Having a private server with:
    -pre-installed files for VMs
    -pre-configured and patched tools
    -Merged Lists
    -Pre-configured certificates
Additionally a minimal installation which will install the core of OWTF with the option of update can increase the installation speed. The update procedure will start fetching the latest file versions from the server and copy them to the right path.

Additional ideas are welcome.

**Comment by delta24** [comment]
- [x] a simple implementation done in [owtf/boostrap-script](http://github.com/owtf/bootstrap-script). 
 - [x] Docker image available

**Comment by delta24** [comment]
@marioskourtesis: Any addition feasible for this issue? I think that the docker image covers this (You just need to `docker pull owtf/owtf` and you have a fully functional OWTF installation.)

**Comment by delta24** [comment]
I am closing this issue because 2 things have been implemented to facilitate this (keeping in mind the host server attack surface and maintenance issues xD). I'll reopen if anything new comes up :) .
