### ISSUE TITLE
MiTM proxy bug: Secure Connection Failed

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#222]
This happens on the trunk OWTF version (but probably also on the ui branch), when setting up 127.0.0.1 over 8008 as the proxy on the browser, and then navigating to any https website, like https://www.google.ie/

On the browser, the user sees the following:
NOTE: This happens even AFTER setting up OWTF via Plug-n-Hack! :P

----
Secure Connection Failed

          An error occurred during a connection to www.google.ie.

SSL received a record that exceeded the maximum permissible length.

(Error code: ssl_error_rx_record_too_long)

  The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
  Please contact the website owners to inform them of this problem. Alternatively, use the command found in the help menu to report this broken site.

**Comment by delta24** [comment]
Still relevant?

**Comment by 7a** [comment]
If you can MiTM https connections using OWTF and your browser, I believe it
should be fixed and can be closed.
