### ISSUE TITLE
multiprocessing deadlock

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#224]
I ran a scan against 5 urls, 2 of which had the same IP, using a 2 processes per CPU setting. 3 workers got deadlocked as can be seen in the following screenshots:

![image](https://cloud.githubusercontent.com/assets/1230243/3052892/e23cbde8-e1a0-11e3-94aa-31ee1f1a8e77.png)

a few hours later:

![image](https://cloud.githubusercontent.com/assets/1230243/3052903/09b85c56-e1a1-11e3-8037-935666bf4ad9.png)

"Application Discovery (Active)" got stuck with no progress in 9.5 hours, oddly enough all targets have nearly identical content, so it makes no sense that other plugins got stuck on some targets but not others.

**Comment by delta24** [comment]
Maybe this was a one-off issue or it has been in subsequent commits. I ran a complete test today (all plugins) against 8 targets and there was no issue. I'll reopen if something like happens again.
