### ISSUE TITLE
urllib2 error on robots.txt request with invalid certs

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#226]
ERROR: The connection was not refused, unknown error! (Requester Object): https://xxxxxxxxxxxxxxxxxxxxxx.amazonaws.com:443/robots.txt
(<class 'urllib2.URLError'>, URLError('unknown url type: https',), <traceback object at 0xa3a1e64>) ...  ...

**Comment by delta24** [comment]
@Sentient07, @7a: still the case?

**Comment by DoomTaper** [comment]
@delta24 Ya! it's still there and I found out that we have made that plugin only for http (Take a look into [requester.py](https://github.com/owtf/owtf/blob/develop/framework/http/requester.py)) and when I print the output of `http_transaction` variable in [Spiders_Robots_and_Crawlers@OWTF-IG-001.py](https://github.com/owtf/owtf/blob/develop/plugins/web/semi_passive/Spiders_Robots_and_Crawlers%40OWTF-IG-001.py) it says
`ERROR: The connection was not refused, unknown error! (Requester Object): https://github.com:443/robots.txt
(<class 'urllib2.URLError'>, URLError('unknown url type: https',), <traceback object at 0x7f03712b35a8>)`

So it is confirmed that it is made for http only.

**Comment by delta24** [comment]
I investigated a little bit and saw that this works:

```
 import httplib
 c = httplib.HTTPSConnection("ccc.de")
 c.request("GET", "/")
 response = c.getresponse()
 print response.status, response.reason
 data = response.read()                                                                                                                     
 print data
```

Also if I add the protocol and port, it does not work `https://ccc.de:443`.

**Comment by delta24** [comment]
Also the `python` distributed with Kali Linux is built with `openssl` already, so ideally `python` should have out-of-box support for SSL.

**Comment by sharad1126** [comment]
@7a I would like to know about this bug. I am not able to understand from the above comments.

**Comment by viyatb** [comment]
Not applicable now - cannot reproduce. This works:
```
