### ISSUE TITLE
Bug in bug reporter :P

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#228]
It looks like the bug reporter does not handle backspaces well, it's a bit messy that you cannot delete text and start to see funny characters on the screen, but even then, after trying to report an issue, you get "None" :P

This is what is left from the sequence of what happened:

[*] Errors saved to owtf_review/db/errors.txt. Would you like us to auto-report bugs ?
[Y/n] 
[*] Do you want to add any extra info to the bug report ? [Just press Enter to skip]
> This was while bruteforcing with Dirbuster, which got into Tomcat, download the relevant version from here: http://olex.openlogic.com/packages/t                                                                            
[*] Do you want to add your GitHub username to the report? [Press Enter to skip]
Reported by @7a_
None

**Comment by delta24** [comment]
Bug reporter has been removed from the CLI in this [commit](77e15bb8ff4d4d756f65fae58b70fd251f0a933b). I am currently adding it to the web interface. :)
