### ISSUE TITLE
Run plugins pop up window improvement (UI branch)

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#243]
The Run Plugins pop up window is really big. As the number of plugins is getting increased, it is becoming more and more difficult to pass throw to each of them and choose what you need.
Suggestion:
Maybe is better to have a separate TAB where the pen-tester will see only the plugins that can run. For example we can have 2 TABs, one VIEW OUTPUT where the pen-tester can see the results from the executed plugins and one RUN PLUGINS.
Ideas are welcome:)

**Comment by DePierre** [comment]
I think the current ``Run Plugins`` pop-up is OK in the latest OWTF version. I am closing this for now until someone else wants to comment the issue.
