### ISSUE TITLE
Installed Tool Validation Project

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#249]
I have faced a problem that I had some tools installed but they were not working as they were supposed to work(due to missing dependencies and missconfiguration). The result was that some OWTF plugins were not working without knowing why. 
Proposed project:
Creation of a module that checks if the installed tools are working correctly.

Ex. We can create something like  ./owtf.py --tool-check which will validate all of the installed tools. It would be really useful for checking the stability of OWTF after upgrading the installed tools.

**Comment by delta24** [comment]
@marioskourtesis @DePierre @7a  Should we keep this for the reboot? This is because doing tool update checks with the current arch will be hard as it will slow down OWTF considerably.

**Comment by 7a** [comment]
sure, this is lower prio than the other bugs like deadlocks, etc.

**Comment by delta24** [comment]
ok, :). Will add to the reboot issues.
