### ISSUE TITLE
executed plugins inaccessible from interactive report...

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#262]
I'm still having to resort to the command line to open plugins on the browser, which is annoying.

ACTIVE plugins like w3af, nikto, skipfish (AND MORE!) are often missing on all OWTF reports, manual browsing of the file system is the only way to access the information given that the interactive report does not provide access to them...

**Comment by delta24** [comment]
@7a I can see the reports on the develop branch

![](http://i.imgur.com/ReeiL6R.png)
![](http://i.imgur.com/ewA1Wxq.png)

**Comment by 7a** [comment]
normally, this happens with the LAST plugins, never with nikto.
You need to run a full scan against many targets, then some of the LAST executed plugins will be missing in the report.
It looks like a race condition or an off-by-one error to me

**Comment by delta24** [comment]
ok :)
