### ISSUE TITLE
NTLM auth support in OWTF

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#264]
Our friend Jim Kelly has asked if we support NTLM auth yet:

From a search on our repo, it looks like there is a python-ntlm library that w3af uses: https://github.com/owtf/owtf/search?q=ntlm&ref=cmdform

From another search on w3af, we can see that such library has problems with NTLMv2 but appears to work with v1:

```
urllib2 handler which adds NTLM v1 support.
NTLM v2 is NOT supported since the "ntlm" library does NOT support it.
```

https://github.com/andresriancho/w3af/search?q=ntlm&ref=cmdform

Not sure if that's the best option in python but worth a look before starting, probably :)

**Comment by viyatb** [comment]
NTML is rarely used in web applications as an authentication mechanism and Tornado does not support it out of box.
