### ISSUE TITLE
Display logs in the webUI

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#271]
It would be great to have **logs** (*ui.log, proxy.log, and owtf.log*) displayed in the Bootstrap tabs fashion in the ***web interface***.

This enables easy viewing without opening several terminal windows.

**Comment by DePierre** [comment]
I leave this feature to someone else. I don't have time for this feature at the moment.

**Comment by delta24** [comment]
IMO it is not worth to integrate this feature now considering its little benefit and somwhat complex implementation (we need an extra Tornado websocket server :/)/
@7a ?
