### ISSUE TITLE
The report has messy owtf commands with proxychains config

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#275]
When the plugins are run, **OWTF** runs commands invoking a tool, etc. The *console output* is fine (the **owtf**-run commands are visible) but the ***report*** shows messy commands (with the whole *proxychains* config)

![2014-07-29-15 54 26_1366x768_scrot](https://cloud.githubusercontent.com/assets/4557897/3733719/157f967c-170b-11e4-93a8-c89b6dbd76c3.png)
![2014-07-29-15 54 35_1366x768_scrot](https://cloud.githubusercontent.com/assets/4557897/3733720/16d7a30c-170b-11e4-99f8-1d4356fccaa4.png)

**Comment by delta24** [comment]
Not a bug :P

**Comment by anantshri** [comment]
hey @delta24 I am interested in knowing why are we storing the entire sample proxychain config file in configuration. https://github.com/owtf/owtf/blob/a2c2fdef27b92c04f514c531d7f071b7a7b0aff7/profiles/general/default.cfg#L380 and even if we are doing it why are we storing it as a proxychains config again by plain echo. If i would be doing it i would prefer to keep just the lines which are required. i.e lines which doesn't start with a # 

I suppose we should clean that up too.

**Comment by delta24** [comment]
@anantshri  Yeah, you are right. Storing the whole config is just unnecessary :P

**Comment by delta24** [comment]
@anantshri or better, store it in ~/.proxychains.conf at install time from the installer ?

**Comment by anantshri** [comment]
I can see a case where we are giving user detailed debug config to make the choice if they want to customize it. But the next step where we do a echo to a specific file that can clearly be used to reduce the file and only store active lines. 

This on retrospect will reduce the line output on the html report also so a win win.

about storing it at install time, what if someone wants to change config. edit ~/.proxychains.conf then that has to be documented.

**Comment by delta24** [comment]
OK, I am committing the change cleans the config which removes the "#" lines. :)
We cannot store the config at install time, because the proxy variables are dynamic (@@XXX@@).
:)

**Comment by anantshri** [comment]
that's 1418 characters per command output line. this would be a quick report size reductions also.
