### ISSUE TITLE
Port Github auto-bug reporter to the UI

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#28]
I have noticed w3af has these cool "auto-generated bug reports":
https://github.com/andresriancho/w3af/issues?state=open

We need to do something similar in OWTF, an option at the end of execution that offers the user to send a sanitised version of owtf_review/db/errors.txt to github automagically after categorising the message to ideally also prevent duplicates.

Alessandro is perhaps best positioned to implement this :)

**Comment by anantshri** [comment]
any status update on this one. no commit marked to this can anyone confirm if UI has this feature now.

**Comment by delta24** [comment]
@anantshri Not ported yet.

**Comment by delta24** [comment]
Do we store the `nowebui` arg somewhere? Then we can check if web interface is running, then show the bug reporter in the UI or else default to console.

**Comment by delta24** [comment]
Aggregated to meta issue - web interface improvements (#695).

**Comment by saganshul** [comment]
@delta24 you can close this issue #716 solves this issue.
