### ISSUE TITLE
[wapiti] HTML report is not available anymore

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#287]
Since my commit aff4fef441f93938e13b86bf55a7846dcdf8d1a3, Wapiti generates XML formatted reports. That way, PTP can automatically rank its discoveries.

Sadly, Wapiti does not allow the user to generate both the HTML and the XML reports (whereas W3AF can generate all the formatted reports you want).

For now, we (@tunnelshade and @depierre) estimate that the automated ranking value given by PTP is more important for the user than the HTML report.

But a solution should be found in order to have both the HTML and the XML reports.

**Comment by delta24** [comment]
@DePierre: I see that (in Wapiti code) if you choose to generate a HTML report, it will automatically generate a JSON report with it. Maybe PTP can be changed to parse the JSON report rather than the XML report for automatic rankings?

**Comment by DePierre** [comment]
@delta24 Could you open a feature request on ptp's github repo? I don't know when I'll take the time to implement that but at least it will be written somewhere.

**Comment by delta24** [comment]
Sure :)

**Comment by delta24** [comment]
Closing as it is now on ptp's issue tracker.
