### ISSUE TITLE
github.io AND interactive report top SCA tools by platform

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#303]
This is a feature request to provide our users with:
NOTE: Suggested to add links to tutorials/demos where possible
NOTE 2: Suggested to put the most useful tools at the top of each platform -obviously :)-
1) A github.io section with suggested SCA tools
2) Same SCA tools from the interactive report

SCA meaning "Static Code Analysis" tools :). There are many platforms, many tools, and a centralised wiki (github.io) with this info would be handy, here are some tools, but definitely MORE should be added to this list :)

Python (Django) - Django SCA:
- Code: https://bitbucket.org/jsthyer/djangosca/overview
- Tutorial: http://securityweekly.com/2014/02/episode-362-django-source-code-scanner.html

(this is a WIP feature, will add more soon)

**Comment by anantshri** [comment]
Can you please elaborate on this. and if possible mark actions items for this.

**Comment by delta24** [comment]
@7a do we really need this? I mean there are some official OWASP lists for that where we can contribute:

- https://www.owasp.org/index.php/Source_Code_Analysis_Tools
- https://www.owasp.org/index.php/Static_Code_Analysis#Tools
