### ISSUE TITLE
owtf  auto-update option

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#31]
I believe we need an auto-update option, something like this:

owtf.py --update

To update:
1) OWTF itself
2) All the restricted tools (i.e. like w3af)

This will prevent out-of-date issues like this:
https://github.com/andresriancho/w3af/issues/351

sqlmap auto-updater for reference:
https://github.com/sqlmapproject/sqlmap/blob/4b9d8ed67304b228f80119070037dc2f5c68b14f/lib/core/update.py

w3af config style auto-update:
https://github.com/andresriancho/w3af/blob/f3b0667bf65a87d16dc0066a53b7a17945c9b98b/core/data/db/startup_cfg.py

**Comment by DePierre** [comment]
Indeed ``owtf.py --update`` is available but not from the Web UI (yet?). If someone feels like implementing a nice button ;)

**Comment by 7a** [comment]
yes @DePierre you are right, now that we have a cool UI, a UI hint like "updates available, click here" would be really cool. Once the user clicks on that the "--update" option could be invoked from the UI, after user confirmation.

**Comment by delta24** [comment]
Right now the web interface shows the status of the your local copy of OWTF wrt the latest commit in upstream. 

As the update cannot be done when running the web interface, I think this resolves this issue. When in the reboot, the core framework and the web interface are disjoint, there can be further improvement.

**Comment by anantshri** [comment]
Can we also do one more thing as part of this issue. get list of packages which we depend on and if distro has a new version available for it.

example we depend on w3af then can we have a check if there is a new version of w3af and mark that dependencies are also out of date. 

Just asking for this are we relying on pulling master or are we relying on release cycles i.e. new release available then update.

**Comment by delta24** [comment]
Checking tool updates at startup will cause the OWTF start to be **very slow** because it will first need to refresh repositories, etc.  I think it is safe to run the install script again to update the required tools. 
@7a ?

**Comment by anantshri** [comment]
can we do sort of lazy loading where UI and functionality starts and then an update checker starts in backend

**Comment by delta24** [comment]
Tool update checker will be implemented in reboot for now (new architecture where we can decide how to run this alongside OWTF). Duplicate  of #249.
