### ISSUE TITLE
Request replay is currently blocking

### ISSUE THREAD

**Issue by tunnelshade** [owtf/owtf#310]
- [ ] The current method of replaying a request is blocking, it can be made non-blocking by using tornado callback
- [ ] A better parameter name must be provided

**Comment by Sentient07** [comment]
Hi @tunnelshade , has this issue been solved ? If not, can you please provide some more details about this ?

**Comment by tunnelshade** [comment]
Not yet solved. The idea is to use async callback to make this non blocking. Check api handlers

**Comment by Sentient07** [comment]
Hi @tunnelshade I have made a few changes for this, how should I test that and ensure it's non-blocking  ?

**Comment by tunnelshade** [comment]
When you try to replay a request and then try to do someother activity like adding a target etc.. Since we have only one api instance. BTW your code must tell you if its blocking or not

**Comment by delta24** [comment]
@tunnelshade Can this be done using a separate AsynHTTPClient to send the replay request instead of the requester object?

**Comment by tunnelshade** [comment]
@delta24 Make sure you attach to the server tornado event loop so that you can write back response when the thing is done!

**Comment by delta24** [comment]
ok :)
