### ISSUE TITLE
[DB] (OperationalError) FATAL:  password authentication failed

### ISSUE THREAD

**Issue by tedher** [owtf/owtf#312]
I installed the OWTF using <code>bootstrap.sh</code> and selected OWTF GSoC'14-dev version, the installation process went OK.

When I tried to run the <code>owtf.py</code> I got the following error message:

<pre>
[-] Aborted by Framework: [DB] (OperationalError) FATAL:  password authentication failed for user "owtf_db_user"
[-] FATAL:  password authentication failed for user "owtf_db_user"
[-]  None None
[-] OWTF :P
</pre> 

It seems that the <code>db_config_setup.sh</code> script located in the <code>install</code> directory is not executed during the installation process.

**Comment by binaryAccess** [comment]
I just experienced the same issue and it was resolved by running /scripts/db_setup.dh from the root directory instead of the scripts directory

**Comment by viyatb** [comment]
@binaryAccess Yes, this can happen if PostgreSQL is not running during the instance (or fails somehow) and the user is not created.
