### ISSUE TITLE
Weird behaviour with https targets

### ISSUE THREAD

**Issue by tunnelshade** [owtf/owtf#316]
When requests go over a https channel, the requests have relative path as their url i.e

```
GET / HTTP/1.1
Host: somesite.com:443
```

So, when we try to search the transaction db for url `https://somesite.com`, we will not get a hit even when the transaction is actually present

**Comment by delta24** [comment]
Cannot reproduce now, must have been fixed in the develop branch.

**Comment by delta24** [comment]
Is very reproducible - breaks Spiders, Crawlers and Robots (passive, semi_passive) plugins! :(

**Comment by a0xnirudh** [comment]
@delta24 I think the reason for this is not because we use https. It breaks with `'http`, `https` or even if we don't specify any protocol at all.

**Comment by delta24** [comment]
@a0xnirudh the Spiders, Robots, and Crawlers semi-passive plugin breaks on `https` but works on `http` targets but the passive plugin breaks on any target.

**Comment by viyatb** [comment]
Cannot reproduce in `develop` anymore.
