### ISSUE TITLE
Transaction table must show match excerpts

### ISSUE THREAD

**Issue by tunnelshade** [owtf/owtf#317]
In a recent test, I really missed the ability to see the excerpt of the match, for all the matches I had to open each transaction and see. Moreover the tabbed request and response are not very handy. So following changes are required
- [x] Bring back old transaction view i.e there different panels with scrollable 'pre' in the same view
- [x] Add a column to transaction table to show match excerpt
- [x] Since we use server side processing, fetching the raw request and response headers might not be costly
- [ ] Response body search must be improved (investigation needed)

**Comment by delta24** [comment]
@tunnelshade, I didn't get what you meant by "response body search must be improved"?

**Comment by viyatb** [comment]
Closing this as not applicable in the new UI. (see https://github.com/owtf/owtf/tree/ui_improvements)
