### ISSUE TITLE
[Auto-Generated]  ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by osakaaa** [owtf/owtf#320]
Bug appeared in OWTF Version: 0.45.0, Release: Winter Blizzard  (stable)
after the next output:
[*] Proxy Check: Avoid logging request again if already in DB..
{'URL': 'http://www.google.ie'} in DB: True
New owtf HTTP Transaction: 3 - 0s, 330ms - 302 Found - GET - http://www.google.ie
[*] Proxy Check OK: The proxy appears to be working

Bug report:
[*] 
[*] OWTF BUG: Please report the sanitised information below to help make this better. Thank you.
[*] ****************************************************************************************************
[*] 
[*] Message: Unknown owtf error
[*] 
[*] Command: owtf.py -g web -t quiet http://some.target.com
[*] 
[*] Error Trace:
[*] Traceback (most recent call last):
[*] 
[*]   File "./owtf.py", line 412, in run_owtf
[*]     if Core.Start(args):
[*] 
[*]   File "/home/andrusha/owtf/framework/core.py", line 321, in Start
[*]     return self.run_plugins()
[*] 
[*]   File "/home/andrusha/owtf/framework/core.py", line 364, in run_plugins
[*]     Status = self.PluginHandler.ProcessPlugins()
[*] 
[*]   File "/home/andrusha/owtf/framework/plugin/plugin_handler.py", line 306, in ProcessPlugins
[*]     self.ProcessPluginsForTargetList(self.PluginGroup, Status, self.Core.Config.GetAll('TARGET'))
[*] 
[*]   File "/home/andrusha/owtf/framework/plugin/plugin_handler.py", line 352, in ProcessPluginsForTargetList
[*]     self.ProcessManager.spawnWorkers(Status)
[*] 
[*]   File "/home/andrusha/owtf/framework/plugin/ProcessManager.py", line 132, in spawnWorkers
[*]     if self.spawn_worker():
[*] 
[*]   File "/home/andrusha/owtf/framework/plugin/ProcessManager.py", line 140, in spawn_worker
[*]     work = self.get_task()
[*] 
[*]   File "/home/andrusha/owtf/framework/plugin/ProcessManager.py", line 115, in get_task
[*]     if int(free_mem) > int(self.Core.Config.Get('MIN_RAM_NEEDED')):
[*] 
[*] ValueError: invalid literal for int() with base 10: ''
[*] 
[*] 
[*] ____________________________________________________________________________________________________

**Comment by DePierre** [comment]
This has been fixed in the latest OWTF version.
