### ISSUE TITLE
db.cfg path error.

### ISSUE THREAD

**Issue by mattaereal** [owtf/owtf#345]
If I'm not mistaken when you install owtf a prompts asks you if you'd like to use .owtf/db.cfg to save the database config, but then automatically asumes that the default path for the db.cfg is in the current user that executes the init script, and you always have to run it using root, so it will be always failing for me.

It's not a big issue, I already worked it out by hand. It's not a fatal error, but thought that pointing this out might help a user that has less knowledge/patience to the issue.

**Comment by DePierre** [comment]
@mattaereal Thanks for the information but since OWTF is meant to be run from Kali and since Kali has a root user by default, it does not seem to be something we will fix (since it just *works*).

If you want to contribute, feel free to propose your patch for fixing that behavior ;)
