### ISSUE TITLE
Minor intuitiveness improvements

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#349]
Based on IRC user feedback, I believe something like the following would be helpful to make "access to the Web UI" more intuitive:
1) Install script indicates how to start owtf (at the end)
2) When you run owtf, owtf highlights in a more visible colour what the user must do to see the UI
Example: Output line indicating UI URL in light blue colour (easier to see if the rest has no colour)

-of course improvements welcome :)-

**Comment by delta24** [comment]
Done in https://github.com/owtf/owtf/commit/a2c2fdef27b92c04f514c531d7f071b7a7b0aff7.
