### ISSUE TITLE
Fix permissions

### ISSUE THREAD

**Issue by leebaird** [owtf/owtf#368]
After install, run the following commands to fix permissions:

find . -name "*.py" -exec chmod 755 {} \;

find . -name "*.sh" -exec chmod 755 {} \;

**Comment by DePierre** [comment]
@leebaird When using the ``boostrap.sh`` script (as explained in the installation guide), these permissions should not matter since the other scripts are run from ``bootstrap.sh`` itself. So I don't think we need to fix that.

@7a Thought on that?

**Comment by 7a** [comment]
@leebaird Please note that most bash (.sh) and python (.py) scripts/modules are invoked without a need for 755 permissions, if you find something that does not work due to incorrect permissions, then please provide us with some steps to replicate the problem and we will take a look.
Thanks!
