### ISSUE TITLE
Don't run internet resources against intranet sites

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#37]
We are currently running internet resources against intranet websites which does not make any sense and also slows down owtf, we run theharvester, robots.txt's motoricerca, metagoofil, etc all trying to use external websites which just won't work because we're testing an intranet site.

Steps to replicate:

owtf.py http://localhost

or also:

owtf.py http://192.168.1.16

Where 192.168.1.16 is an example IP for a host in your local network

**Comment by delta24** [comment]
Has this implemented? :)

**Comment by DePierre** [comment]
@delta24 It was implemented in the master branch long time ago but I am not sure that it has been ported to the develop one.

**Comment by delta24** [comment]
This --> https://github.com/owtf/owtf/blob/develop/framework/utils.py#L11 ?

**Comment by DePierre** [comment]
I don't know why it has been put in a class... Kind of stupid but anyway (PYTHON! WE NEED MORE CLASSES!!!), this was this original idea/patch indeed.

@delta24 As I suspected, the patch has not been properly ported to the develop branch so even google hack tool will be run against internal targets.

**Comment by anantshri** [comment]
Can someone please list out what is the part that is left for this specific issue. If the status has changed and this is fixed please close issue.
