### ISSUE TITLE
Selecting plugs-ins

### ISSUE THREAD

**Issue by leebaird** [owtf/owtf#372]
When selection plug-ins the run, checking the box in the top left corner should select ALL available plug-ins, not just the ones on the current page.

For example: View 10 rows.  Checking the box in the top left corner only selects the first 10 plug-ins.

**Comment by DePierre** [comment]
@leebaird This is an expected behavior.

If you want to select ALL plugins (and not just the ones from the current pane) you must go to ``Launch in groups`` and select the groups (for instance ``net + web``). This will run all WEB and NET plugins.
