### ISSUE TITLE
Show progress of scan

### ISSUE THREAD

**Issue by leebaird** [owtf/owtf#373]
On the Workers page, show progress with the total number of plug-ins selected and the number of the plug-in that is currently running.

For example:  (12/50)
Running the 12th plug-in of the 50 that were selected.

**Comment by DePierre** [comment]
@leebaird The details about the plugins can be seen from the ``Worklist`` pane. Isn't that enough?

**Comment by anantshri** [comment]
The worklist shows how much is pending but it doesn't list what is done and kind of approximate percentage of stuff done.

I would propose updating the homepage of OWTF UI pushing the owtf details a bit lower and showing the current running scan's progress as well as already complete scans.

**Comment by 7a** [comment]
+1, Approximate %, plugins run vs. Plugins left (12/50), this is currently
not clear. I'd go a bit further and also try to guess-estimate how long
(days+hours+minutes) is left based on the average time x executed plugin
vs. Plugins left (will have to be better than that, but that should be
close)

**Comment by anantshri** [comment]
guestimation compilcates the scenario coz if the plugin that are already run is say nmap or nikto and plugin left is arachini and skipfish. the timing will be scewed directly. i would prefer sticking to plugin complete and plugin left and maybe a percentage based on plugin count.

**Comment by delta24** [comment]
+1 to what @anantshri said

**Comment by 7a** [comment]
Sure, plugin % is probably the way to go.
Any takers? :)

**Comment by saganshul** [comment]
@7a  @delta24 @anantshri  I will do this work. Can you tell me where to show progress, I means on home page or worklist page or somewhere else. 
Also I think showing progress bar will be better and more UI friendly than just showing number of done, left and total.

**Comment by saganshul** [comment]
@7a  @delta24 @DePierre , should I display progress bar on homepage or worker page or both ?.

**Comment by delta24** [comment]
IMO homepage. Keeping it in workers page is counter intuitive and keeping in both is redundant.

**Comment by delta24** [comment]
> @7a : There should be a progress summary bar somewhere at the top of the owtf report, the pentester is most likely to be on the workers page (to see WTF is going on atm) or reviewing the results of a target, they will almost never be on the "all targets" page. That said, the progress bar also makes sense on the index aka "all targets" page.

Now that we are considering this, it would also be interesting to consider "total progress" vs. "this target progress" so if you are viewing the results for a given target, you have something that tells you "all plugins have already been run against this target" or not.
