### ISSUE TITLE
[develop] OWTF should start NET plugins when target is an IP

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#375]
By default, OWTF will run its plugins against a target when executing the following command (i.e. running OWTF without any option):

```
$ python2 owtf.py https://google.nl

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
[*] OWTF Version: 1.0.1, Release: LionHeart (Beta) 
[-] Loading framework please wait..
[-] The IP address for google.nl is: '64.233.166.94'
[*] 127.0.0.1:8008 <-- HTTP(S) Proxy to which requests can be directed
[*] http://127.0.0.1:8009 <-- Web UI URL
[-] __________ 1 - Target: https://google.nl -> Plugin: Application Discovery (active) __________
[-] 
[-] Executing :

cd owtf_review/targets/https__google.nl/partial/Application_Discovery/active; /usr/bin/dnsrecon --type std,rvl,goo -d google.nl -r 64.233.166.94-64.233.166.94

; Omitted outputs...
```

I remember that before GSoC 2014, OWTF wasn't running any plugin except when asked for (e.g. running ``-g web`` or ``-o OWTF-PLUGIN-CODE``).
OWTF should do as before and not run the plugins when no option is specified.

@7a any thought on that?

**Comment by tunnelshade** [comment]
This is too complex. This cannot be done as of now. The code gets too complex to support this while keeping our cmd flags working
