### ISSUE TITLE
Owtf not working properly with latest version of pip

### ISSUE THREAD

**Issue by Ahiknsr** [owtf/owtf#380]
I have installed owtf today and When i tried to run python owtf/owtf.py , it is throwing the error "parse_requirements() missing 1 required keyword argument: 'session' " , seems like the error is occuring because recent version of parse_requirements function in pip module needs session parameter and we are not passing it , temporary fix is add "session=1"  to parse_requirements function in owtf/framework/dependency_check.py .

**Comment by DePierre** [comment]
Thanks @Ahiknsr and sorry for the delay.
