### ISSUE TITLE
Owtf not starting

### ISSUE THREAD

**Issue by yashar6909** [owtf/owtf#385]
After using the bootstrap.sh script to install OWTF and all its dependencies, on Kali , i try to start owtf, and I get the following error:

root@kali:~/owtf# ./owtf.py 
Traceback (most recent call last):
  File "./owtf.py", line 41, in <module>
    verify_dependencies(os.path.dirname(os.path.abspath(sys.argv[0])) or '.')
  File "/root/owtf/framework/dependency_check.py", line 57, in verify_dependencies
    owtf_libraries = [req.req.project_name for req in owtf_reqs]
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'

Please help :)

**Comment by Ahiknsr** [comment]
Take a look at this  ,https://github.com/owtf/owtf/issues/380

**Comment by DePierre** [comment]
@yashar6909 A fix has be pushed for that issue but it is not part of a new release yet. To use the fix, please clone OWTF from the repository itself (master or develop branch) and install it using ``install/install.py`` script.
