### ISSUE TITLE
OWTF start is slow

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#387]
IMHO OWTF can be optimized to load faster but I am still not sure how we can do that. We need some investigation here.

**Comment by DePierre** [comment]
Quick and dirty investigation with ``datetime`` gives the following outputs when used in ``owtf.py``:

```bash
Starting time after banner: 7.7e-05 seconds
Starting time after initialisation_phase_1: 3.404685 seconds
Starting time after process_options: 3.412317 seconds
Starting time after initialisation_phase_2: 4.052184 seconds
Starting time after Core(): 4.052435 seconds
```

These numbers look alike between several runs but we get the idea:

+ the initialisation phase 1 takes ~3.5 seconds
+ the initialisation phase 2 takes ~0.5 seconds

**Comment by DePierre** [comment]
More data from ``framework.dependency_management.component_initialiser.initialisation_phase_1``:

```bash
Starting time after Config(): 0.000662 seconds
Starting time after ErrorHandler(): 0.000711 seconds
Starting time after DB(): 0.08585 seconds
Starting time after OWTFSessionDB(): 0.118404 seconds
Starting time after WorklistManager(): 0.118502 seconds
Starting time after ConfigDB(): 0.260291 seconds
Starting time after CommandRegister(): 0.260352 seconds
Starting time after TargetDB(): 0.260378 seconds
Starting time after ResourceDB(): 2.952003 seconds
Starting time after ErrorDB(): 2.952092 seconds
Starting time after MappingDB(): 2.952117 seconds
Starting time after VulnexpDB(): 2.95214 seconds
Starting time after Timer(): 2.956426 seconds
Starting time after PluginDB(): 3.354839 seconds
Starting time after zest(): 3.354906 seconds
Starting time after URLManager(): 3.35692 seconds
Starting time after TransactionManager(): 3.363087 seconds
Starting time after config.init(): 3.36318 seconds
Starting time after zest.init(): 3.372109 seconds
```

Seems that the bottleneck is ``ResourceDB`` but keeps in mind that these values are not accurates (only a few runs).

**Comment by DePierre** [comment]
From ``framework.db.resource_manager``:

```bash
Starting time after register_in_service_locator(): 1.3e-05 seconds
Starting time after get_component('config'): 7.7e-05 seconds
Starting time after get_component('db_config'): 9.7e-05 seconds
Starting time after get_component('target'): 0.000113 seconds
Starting time after get_component('db'): 0.000128 seconds
Starting time after LoadResourceDBFromFile: 2.60903 seconds
```

**Comment by DePierre** [comment]
From ``framework.db.resource_manager.LoadResourceDBFromFile``:

```bash
Number of requests in the for loop (query + add): 2298
```

I don't know exactly what is requested but it looks that **2298** is a lot, right?

**Comment by DePierre** [comment]
IMHO it should be possible to make only one big request instead of [that for loop here](https://github.com/owtf/owtf/blob/develop/framework/db/resource_manager.py#L29).

The for loop tries to do the following:

+ Get the resources from the files
+ Remove any older resources stored in the database
+ For each resource:
    + Check if it is already stored in the database
    + If not, add it
+ Commit all changes to the database

My guts tell me that it **should be faster and easier to use a ``set()`` when retrieving the resources from the files**. Then it won't be needed to do that for loop.
Then, we make one big request to add and commit all the resources to the database.

Thoughts on that @7a, @tunnelshade and anyone else?

**Comment by DePierre** [comment]
Using a ``set`` instead of a [``list`` here](https://github.com/owtf/owtf/blob/develop/framework/db/resource_manager.py#L36) and removing [that line](https://github.com/owtf/owtf/blob/develop/framework/db/resource_manager.py#L31) (since we have a set, we can't have duplicates) gives the following:

```bash
Timer before initialisation_phase_1: 1.1e-05 seconds
Number of requests (query + add): 1149
Timer after initialisation_phase_1: 1.377494 seconds
```

Twice less request for twice less time. We still need to only make one big request.

**Comment by DePierre** [comment]
@tunnelshade do you think it would be possible to only make one big request when adding the resources into the database? If so, how could it be done?

**Comment by tunnelshade** [comment]
The fastest way is to add all the resource, config objects (all db objects we do during initialisation phases) to one single session and commit ``only once``. This will be significantly faster since we are actually writing to db only once. For example look [here](https://github.com/owtf/owtf/blob/develop/framework/db/transaction_manager.py#L301). The `commit()` call is **outside** the for loop.

**Comment by DePierre** [comment]
@tunnelshade That is the case for the ``ResourceDB`` as well ([``commit()`` is outside the loop](https://github.com/owtf/owtf/blob/33b82c3ab62804301b708bf668002cf0210aa545/framework/db/resource_manager.py#L31)) but there is still the for loop to add one resource at a time.

Could it be possible to get rid of [the for loop here](https://github.com/owtf/owtf/blob/33b82c3ab62804301b708bf668002cf0210aa545/framework/db/resource_manager.py#L29)?

**Comment by tunnelshade** [comment]
The `for loop` might not be removable because even if we can perform bulk insert, we might have to create the db objects. I am also saying that instead of committing in every db manager during initialisation, we can  commit only once after the initialisation. That will speed up a lot of things. There is a  ``session.add_all()`` but we have to create list of objects for that.

**Comment by DePierre** [comment]
Ok I understand now what you meant by "commit() only once", I will check that today ;)

We have to check the rest though.

**Comment by DePierre** [comment]
@tunnelshade I tried removing all the ``session.commit()`` in the phase one to only keep one at the end but it does not speed up OWTF.

From what I saw:

+ Before removing the ``commit()`` calls, I hit a *0.5* seconds increase in the [``ResourceDB``'s ``commit()`` call](https://github.com/owtf/owtf/blob/develop/framework/db/resource_manager.py#L31).
+ After keeping only one ``commit()`` call, I hit a *0.5* seconds increase in [``db_config.Get()`` call](https://github.com/owtf/owtf/blob/develop/framework/dependency_management/component_initialiser.py#L68).

I understand from these facts that sqlalchemy is lazy enough to be efficient when dealing with such situation. By the way, only the first ``session.commit()`` hits a *0.5* seconds increase, the other ``commit()`` calls are super fast.

Any thought?

**Comment by tunnelshade** [comment]
Hmm. Interesting. I think we can tweak up some parameters in the [engine configuration](http://docs.sqlalchemy.org/en/rel_0_9/core/engines.html#postgresql). One bottleneck I can think of is [this](https://github.com/owtf/owtf/blob/develop/framework/db/db.py#L133)

**Comment by delta24** [comment]
@DePierre any more to do here? I changed the DB settings (engine parameters) a while back, but have not run the benchmarks yet.

**Comment by DePierre** [comment]
@delta24 Not sure, I personally haven't really benchmarked anything since that time. It would be nice if someone could run a quick benchmark in similar areas I benchmarked previously to see if there was any improvement.

**Comment by Tikam02** [comment]
Nope it starts normally and loads fast.

**Comment by viyatb** [comment]
Closing an wont-fix for now. I experimented with the engine parameters and did not see a sufficient increase in startup time. The `poolclass`, `poolsize` and `max_overflow` parameters were tested. Most of the tweaking is hard because it introduces blocking mechanisms (leading to deadlocks) due to the use of Python's `multiprocessing` in OWTF.
