### ISSUE TITLE
redisgned homepage 

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#396]
clear instructions on how to install specifically the one liner need to be placed better on owtf.org i.e. owtf wiki page also.

right now a person has to find where sources are and then scroll down nearly to the bottom to see how to install owtf.

**Comment by delta24** [comment]
Did you mean the OWASP site?

**Comment by anantshri** [comment]
owasp.org which points to OWASP webpage as well as owtf.github.io both don't list the one liner which can allow for seemless installation.

**Comment by delta24** [comment]
The one-liner was purposefully removed because some people had concerns executing an arbitrary  script over the network! 
See http://curlpipesh.tumblr.com/ :P

**Comment by anantshri** [comment]
I understand the concern but here is the disconnect. 

https://github.com/owtf/owtf/#installation <- we specifically recommend that. 

In case we decide to remove oneliner that's fine. But atleast we should have instructions like 
<pre>
git clone https://github.com/owtf/owtf
sh install/install.sh
./owtf.py
</pre>
The idea is that the person should not be left wondering what to do they should have a clear outline that this is how installation works.

**Comment by delta24** [comment]
Ok, that is fine :+1:

**Comment by delta24** [comment]
Already done, one-liner has been added to the README and wiki!

**Comment by anantshri** [comment]
so initially you said we don't want to put oneliner coz people get offended by it and then you close the issue stating its already there.

**Comment by delta24** [comment]
Basically, yes because it happens to be most simple way for many people to install, but the README also states that you can clone the repo as a second choice.
