### ISSUE TITLE
error on bootstrap

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#397]
Steps performed
1) Created a VM with debian 7.
2) change repositories to kali repository
3) did a apt-get update and apt-get install kali(entire suit)
so for all cases and purposes it becomes kali.
now bootstrap.sh was ran and everything was fine. 

but python owtf.py gives following error.

Traceback (most recent call last):
  File "owtf.py", line 41, in <module>
    verify_dependencies(os.path.dirname(os.path.abspath(sys.argv[0])) or '.')
  File "/home/anant/tools/owtf/framework/dependency_check.py", line 57, in verify_dependencies
    owtf_libraries = [req.req.project_name for req in owtf_reqs]
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'

**Comment by DePierre** [comment]
@anantshri This has been solved already (see 0bbeea1cd2e6380db56a1a3a67f6abfe8f8be3ea) but it is not part of the latest release yet.
We will merge that into the next release ;)

**Comment by anantshri** [comment]
so i suppose going bleeding eadge should get me started.
