### ISSUE TITLE
Lionhearted won't launch after install on Kali 1.09

### ISSUE THREAD

**Issue by macubergeek** [owtf/owtf#398]
when i launch it with ./owtf.py

I get this error

Traceback (most recent call last):
  File "./owtf.py", line 41, in <module>
    verify_dependencies(os.path.dirname(os.path.abspath(sys.argv[0])) or '.')
  File "/opt/owtf/framework/dependency_check.py", line 57, in verify_dependencies
    owtf_libraries = [req.req.project_name for req in owtf_reqs]
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'

**Comment by Ahiknsr** [comment]
hey @macubergeek , this is a known issue and this has been fixed but it not a part of new release yet . To fix it run "wget https://raw.githubusercontent.com/owtf/owtf/master/framework/dependency_check.py -O framework/dependency_check.py" from owtf directory .

**Comment by delta24** [comment]
As @Ahiknsr said this is due to a missing python-pip upgrade which requires a separate `sessions` parameter while parsing files for requirements. The fix is in the trunk, please use the master branch :)

**Comment by jaylinski** [comment]
please release a new minor version with this fix included.

**Comment by tunnelshade** [comment]
@jaylinski We are working for it. Progress can be tracked on [develop](https://github.com/owtf/owtf/tree/develop) branch

**Comment by jaylinski** [comment]
ok, thanks for the quick feedback :)
