### ISSUE TITLE
Add target UI issue

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#405]
When adding a target  the target input is not cleared.

**Comment by marioskourtesis** [comment]
fixed via 
https://github.com/owtf/owtf/commit/0ce520b06b0fff31dd2a884eab6c5c065c620bef

**Comment by 7a** [comment]
But please only if the target is added successfully :)
On 6 Apr 2015 19:23, "Marios" <notifications@github.com> wrote:

When adding a target the target input is not cleared.

—
Reply to this email directly or view it on GitHub
<https://github.com/owtf/owtf/issues/405>.

**Comment by marioskourtesis** [comment]
Yes, it is fixed ;).
