### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by jherrlin** [owtf/owtf#406]
To make the site more mobile friendly

**Comment by DePierre** [comment]
@jherrlin Do you mean the OWTF Web site or the OWTF Web UI?

**Comment by jherrlin** [comment]
@DePierre I was thinking of the OWTF Web UI.

Okey, i can clearly see that! 
I hade a situation in mind, where you start workers and then are able to watch them from a mobile device.
This of course requires the server to listen to incomming request from other interfaces than the loopback!

As i am pretty new to the project, i thought this was a way for me to get to know it.
If you have bug that are not to hard to fix, please asign me!

**Comment by DePierre** [comment]
@jherrlin This is in fact a nice idea about the workers :)

If you have time, could you test the OWTF installation process? Via the bootstrap script and via git (see #409 for instance).

**Comment by tunnelshade** [comment]
@jherrlin You can start UI on other interfaces also. See [here](http://docs.owtf.org/en/latest/configuration/framework_config.html)

**Comment by delta24** [comment]
Most of the part of the interface are now responsive. A few components including Bootstrap's `btn-group` and the datatables cannot be made responsive for all possible viewports without compromising the data being rendered. I am attaching some screenshots of the interface in a mobile viewport.

![screen shot 2016-02-06 at 15 50 44](https://cloud.githubusercontent.com/assets/4557897/12866177/9803c7da-ccea-11e5-9e4f-2e4228f4dbee.png)
![screen shot 2016-02-06 at 15 50 50](https://cloud.githubusercontent.com/assets/4557897/12866179/989fc018-ccea-11e5-96d1-bdd22c2463e2.png)
![screen shot 2016-02-06 at 15 56 04](https://cloud.githubusercontent.com/assets/4557897/12866180/9bdb2c04-ccea-11e5-85f5-204a3c925f1b.png)
![screen shot 2016-02-06 at 15 51 20](https://cloud.githubusercontent.com/assets/4557897/12866181/9d46e268-ccea-11e5-9473-39c48fd67077.png)
![screen shot 2016-02-06 at 15 51 29](https://cloud.githubusercontent.com/assets/4557897/12866182/9eb741b0-ccea-11e5-9e60-593a9591876f.png)
![screen shot 2016-02-06 at 15 51 33](https://cloud.githubusercontent.com/assets/4557897/12866183/a00ceede-ccea-11e5-9c34-b41eac23ef46.png)
![screen shot 2016-02-06 at 15 51 36](https://cloud.githubusercontent.com/assets/4557897/12866184/a147e754-ccea-11e5-9edd-ac21b401f568.png)
