### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by secureplanet** [owtf/owtf#409]
Dear Team , 

When i am trying to install OWTF in Kali Linux then its Giving A error i.e.

python ./owtf.py 
The following python libraries seem missing : 
   Markdown,PTP,python-owasp-zap-v2,PyVirtualDisplay,rdflib,selenium,tornado

Haven't you run the install script? 
   python2 install/install.py

If you are sure you ran the install script, install the missing libraries seperately
   pip install --upgrade -r install/owtf.pip

**Comment by marioskourtesis** [comment]
Hello,
I have tested the installation in a new and updated Kali VM and I did not
face any problems.
Is your VM updated?

Kind Regards

**Comment by 7a** [comment]
Did you run the install script as the error message said?

Haven't you run the install script?
python2 install/install.py

**Comment by DePierre** [comment]
@secureplanet I confirm the issue. I installed a new Kali 32bit VM (*Linux kali32 3.18.0-kali3-686-pae #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) i686 GNU/Linux*) and got your error messages after running the installation boostrap script the first time.

But as the error messages say, running ``python2 ./install/install.py`` seems to solve the problem.

Let us know if you are not able to run OWTF.

**Comment by delta24** [comment]
Closing subset of #516
