### ISSUE TITLE
OWTF should check if postgresql client is installed as well

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#413]
It was decided that the OWTF installation process should check if ``postgresql-server`` was installed and running. If not, OWTF would download and start the service on its own.

When trying to reproduce #409, it seems that OWTF is not checking if a ``postgresql-client`` was installed. During the installation process, the DB initialisation failed and the process continued.

```bash
[*] Running following command
sh /root/owtf/install/db_config_setup.sh /root/owtf
[*] Creating default config at /root/.owtf/db.cfg
[*] Don't forget to edit /root/.owtf/db.cfg
[*] Do you want to create database and user as specified in /root/.owtf/db.cfg [Y/n]?

[+] PostgreSQL server is not running.
[+] Can I start db server for you? [Y/n]

[+] Postgres running on :
[+] OWTF db config points towards 127.0.0.1:5432
[+] Do you want us to save the new settings for OWTF? [Y/n]

[+] New database configuration saved
Error: You must install at least one postgresql-client-<version> package.
[+] The problem seems to be the user role and db mentioned in /root/.owtf/db.cfg. Do you want us to create them? [Y/n]


------------------------- OWTF Database Helper Script -------------------------
                    Helps in creation of user and database                     
-------------------------------------------------------------------------------

[+] Ensure that you have required values in /root/.owtf/db.cfg

Press Enter to continue

Error: You must install at least one postgresql-client-<version> package.
Error: You must install at least one postgresql-client-<version> package.
[*] Installing Zest Jars
```

Of course, OWTF could not be run after the installation finished since the DB failed to be properly configured.

IMO, whether OWTF should check for a ``postgresql-client`` when checking for the server or OWTF should not check for ``postgresql`` at all.

**Comment by 7a** [comment]
I would go for:
OWTF should check for a postgresql-client when checking for the server

Well spotted!

**Comment by delta24** [comment]
Easier solution would be add this to the install script :) .
