### ISSUE TITLE
Force (tool) kill option

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#418]
@7a : In some cases, it happens that when you try to kill a process via the manager, is waiting forever, indefinitely. It would be nice to have another icon close to the “X” 

``` bash
$ ps -ef | grep -i w3af`
root       867 16404  0 18:45 pts/5    00:00:00 grep -i w3af
root     30908  5742  0 16:17 ?        00:00:00 /bin/sh -c cd owtf_review/targets/http__some.host.com/partial/W3Af_Unauthenticated/active; /root/owtf_develop/scripts/run_w3af.sh /usr/share/w3af/w3af_console http://some.host.com 127.0.0.1:8008 'Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/15.0'
root     30909 30908  0 16:17 ?        00:00:00 bash /root/owtf_develop/scripts/run_w3af.sh /usr/share/w3af/w3af_console http://some.host.com 127.0.0.1:8008 Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/15.0
root     30920 30909 99 16:17 ?        03:13:45 python /usr/share/w3af/w3af_console -n -s w3af_report2015-03-10_16_17_23.script.w3af
```

Killing the tool, helps OWTF continue, in this case:
`$ kill -9 30920`

**Comment by 7a** [comment]
The idea here is that some plugins may run several tools and the user
currently has no option to "stop command" from the UI

**Comment by viyatb** [comment]
https://github.com/owtf/owtf/commit/2b2bd2214e538c5e1ed269fb57b75f91dd200e8c and a19cb7d3da79e9e7bf64c87583b79e37f421ead7 should resolve this. I don't think there is a need to provide a UI option for this.
