### ISSUE TITLE
Display start time on the worker summary screen

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#419]
@7a : At the moment, it is not easy to see what worker started when, when you use **OWTF** in a *large scope*, this is quite important because you don’t want a single tool to delay the scan. i.e. If I see that nikto is running for more than 1 day, something is wrong.

With this in mind: It would be nice if http://127.0.0.1:8009/ui/workers/ displayed something like `“Start: 2015/03/10 12:30 (~3 hours)”` to the right of the current “PID” field.

**Comment by sharad1126** [comment]
@7a Will be working on it. Will add this feature on the workerlist_manager.html

**Comment by saganshul** [comment]
@7a  Here you just wanted start time of running worker right? If my understanding is right, is there any api call which can give me this information?
