### ISSUE TITLE
OWTF log files compression

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#423]
Hi Folks, I don't have log output to show the incidence however I have had incidence atleast once when the OWTF scan process created so much of log files which resulted in 100% disk usage which causes issues towards the system stability.
A check to see how much is free storage and may be doing a tar.gz / tar.bz2 of the log files should help in long way as the data is anyways plain text.

**Comment by delta24** [comment]
Cache files? I think @tunnelshade commited a fix to drastically reduce the proxy cache?

**Comment by tunnelshade** [comment]
@delta24 Yes

**Comment by delta24** [comment]
So, is this resolved?

**Comment by tunnelshade** [comment]
@delta24 I think log files thing can be still optimised. That can be looked into

**Comment by delta24** [comment]
Should I add logrotating of the log files in the install script and a script to backup the logs in a .tar.gz format to a directory of user's choice? @anantshri

**Comment by delta24** [comment]
Shifted to https://github.com/owtf/health_monitor/issues/8.
