### ISSUE TITLE
Poor clickflow

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#429]
@7a : At the moment you need 3 clicks + 1 nasty horizontal mouse move from left to right to rank ANY plugin.
We need to:
 - Put the plugins somehow into the plugin group banners (-1 click)
 - you know the plugins that have been run under that test, we could abbreviate with [ E P S A ] ← External, Passive, Semi-Passive, Active :)
 - Put the buttons to click on the plugins [ E P S A ] directly ABOVE the ranking buttons (decreased horizontal mouse trip)

**Comment by delta24** [comment]
- [ ] Optimise UI of the report
- [ ] ZAP/Burp like transaction log viewer
- [ ] Replace accordions to something more easier to navigate

**Comment by mikefitz888** [comment]
Minor improvement.
I've made a small change on a fork that contributes to this. When there's only one type of plugin (active, bruteforce etc...) to display a report of, then that tab will be open by default when that section of the accordion is opened.

https://github.com/mikefitz888/owtf/commit/9c05d7bcc07692e3181d1aa45b97bdb8d5db7b28

What do you think? Okay to submit a pull request?

**Comment by delta24** [comment]
Yes please @mikefitz888 ! :)

**Comment by delta24** [comment]
Shifted to superset issue, https://github.com/owtf/owtf/issues/695.
