### ISSUE TITLE
Bug - "Ops unable to add some targets”

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#443]
@7a : 

#### NOTE: 
Happens when you are trying to add a target twice within a (potentially) huge list of targets :)

When trying to add 20+ targets to an initial scope, I saw UI error like “Oops unable to add some targets :P”. This is VERY unhelpful because:

- It does not tell me which are the ones that could not be added (on the UI)
- It stops on the 1st error and does not add any other target, so I have to dig the original order in which the targets were added so that I have a list to copy-paste
    
Error on the CLI:
`http://target.com already present in Target DB & session`

**Comment by delta24** [comment]
I think we can have a function such as 

```javascript


function unique(r)
{
    var n = {};
    for(var i = 0; i < r.length; i++)
    {
        if (!n[r[i]])
        {
            n[r[i]] = true;
            r.push(r[i]);
        }
    }
    return r;
}
```
which takes an array, here `targetURLs` (https://github.com/owtf/owtf/blob/develop/framework/interface/templates/target_manager.html#L315) and outputs a array with only unique elements (see @ line https://github.com/owtf/owtf/blob/develop/framework/interface/templates/target_manager.html#L330).

This resolves any error due to addition of duplicate targets IMO.

**Comment by tunnelshade** [comment]
Solved in a peculiar way

**Comment by 7a** [comment]
Ok from me :)
