### ISSUE TITLE
CPU spikes: Lack of Indexing on OWTF db? 

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#444]
@7a : 

OWTF seems to struggle in huge assessments, below is after running Dirbuster, with just 2 workers, with almost NO urls found, this CPU spikes suggest that OWTF would probably benefit from indexing the DB.

![ ] (https://cloud.githubusercontent.com/assets/4557897/7429153/1ac0e814-f01a-11e4-9781-de8c8e5b87fb.png)

The scope in question was a FULL web scan (i.e. ALL web plugins) of 35 URLs, towards the end.

**Comment by 7a** [comment]
Confirmed as lack of indexing, adding the following index eliminated ALL CPU spikes "idle in transaction", "SELECT", etc. 

```n```
Name	Definition	Constraints	Clustered?	Actions	Comment
transaction_id_idx	CREATE INDEX transaction_id_idx ON transaction_grep_association USING btree (transaction_id)

**Comment by DePierre** [comment]
@tunnelshade Should we include such fix? What are the side effects?

**Comment by tunnelshade** [comment]
Yes, indexing will solve this for now as Abe suggested. Add indexing to the column of the transaction_grep_association table

**Comment by 7a** [comment]
Can somebody *please* add this to the DB init scripts? the index is *still* missing on develop and the spikes are therefore happening.

Simply create a btree index on the transaction_id column of the transaction_grep_association table, as above, and the spike is gone, as I troubleshooted and fixed 2 months ago above! :)

NOTE: This takes *forever* using the postgress DB UI, if using phppgadmin, you need to do this on an *empty* database to have a chance to see the full command generated.

**Comment by delta24** [comment]
Confirmed from @7a : the last referenced commit fixes the problem :)
