### ISSUE TITLE
Improve curl commands

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#446]
@7a : 
We need to improve CLI commands for ease of manual verification, for example, the curl PUT test, needs to be arranged so that it’s easy to verify “what was even attempted to be uploaded”, for example:

```bash
FILE=$(head /dev/random -c8 | od -tx1 -w16 | head -n1 | cut -d' ' -f2- | tr -d ' '); echo "Tried File: $FILE"; curl -s -i -A 'Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/15.0' -X 'PUT' --data "$FILE" -k "https://target.com/admin/$FILE"
Tried File: 44b7fa5e6d0d5798
```
ie. right now, we are calling /dev/random twice so that's not repeatable. The whole point of the curl commands is to give something repeatable so that the tester can copy + paste to see if the same response comes up.

**Comment by arunk-s** [comment]
@delta24 Can you explain a little more on this issue ? I'd like to work on this one.
