### ISSUE TITLE
UI unresponsive on large scopes

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#447]
@7a : It looks like the UI hangs or takes way too long to load the plugins for a given target on large scopes.

Eventually I did “Control + C” on the OWTF terminal, after which port 8009 worked again but port 8010 stopped working :(

Finally, tried to Control + C again, to execute OWTF once more, but the delay on load is also really bad (61 URLs scope)

``` bash
 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org

[*] OWTF Version: 1.0.1, Release: LionHeart (Beta) 
[-] Loading framework please wait.. ← 5-10 minutes waiting! :P
```

The whole point of a UI is something that is VERY responsive and does not make the tester waste any time.

**Comment by sharad1126** [comment]
I am using it on kali and it is opening in few seconds. I am running kali on VMWare in mac.

**Comment by delta24** [comment]
@sharad1126 This happens when you have a large number of targets. (>30)

**Comment by sharad1126** [comment]
@delta24 Ok need to check that. Not tried for so many targets.

**Comment by delta24** [comment]
Updated tracking and relevant information in #790.
