### ISSUE TITLE
 OWTF-SM-001 Session Management Schema Semi passive not working

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#449]
The "OWTF-SM-001 Session Management Schema" semi passive plug in is not working.

**Comment by DePierre** [comment]
@marioskourtesis hahaha, I wanted to investigate if it would fail sometimes or all the time but the root of that bug is even funnier.

From the [plugin file](https://github.com/owtf/owtf/blob/develop/plugins/web/semi_passive/Session_Management_Schema%40OWTF-SM-001.py) itself:
```python
def run(PluginInfo):
    # ServiceLocator.get_component("config").Show()
    # True = Use Transaction Cache if possible: Visit the start URLs if not already visited
    # Step 1 - Find transactions that set cookies
    # Step 2 - Request 10 times per URL that sets cookies
    # Step 3 - Compare values and calculate randomness
    URLList = []
    TransactionList = []
    Result = ""
    return ([])
```
In fact it hasn't been working since ever, like before 2012 maybe...
@7a @tunnelshade Would you have some information so share about that? https://github.com/owtf/owtf/commit/3ff965d113880d09844ae9a5526664dd3046a841#diff-40bec1612db6779ef9810c15e2e79e23L47

**Comment by DePierre** [comment]
Also, funny thing is that I can't even stop the worker assigned to that plugin...

**Comment by 7a** [comment]
Agreed, the approach described in that plugin makes sense however! any
takers? :)

**Comment by DarKnight24** [comment]
@delta24 @DePierre The current implements is throwing an error [here](https://github.com/owtf/owtf/blob/develop/plugins/web/semi_passive/Session_Management_Schema%40OWTF-SM-001.py#L22). 

`TransactionManager instance has no attribute 'GrepTransactionIDsForHeaders'`.Any suggestion to fix this.

**Comment by delta24** [comment]
@DarKnight24 see if there is a GrepTransactionIDsForHeaders in the framework config file - that regex must be defined somewhere.

**Comment by DarKnight24** [comment]
![screenshot from 2016-09-30 15-52-53](https://cloud.githubusercontent.com/assets/6971456/18988830/197172f4-8726-11e6-97dd-6132d761aa42.png)

@delta24 This is not mentioned anywhere else other than the usage in the plugin.

**Comment by DarKnight24** [comment]
@delta24 @7a @DePierre 

This function was removed in [this](https://github.com/owtf/owtf/commit/a25ea4131b05dc5857be906436f1c180b22eecdf#diff-5860fa2fa39931c18e250609443e5a5aL168) commit by @tunnelshade. Any suggestions for fixing?

**Comment by DarKnight24** [comment]
@delta24 Any updates on this issue?

**Comment by DarKnight24** [comment]
@delta24 @7a  The method `Get` is also removed from `config.py` in the same commit as above mentioned. 

IMO the plugin has to be rewritten.

**Comment by DePierre** [comment]
`GrepTransactionIDsForHeaders` does not exist anymore but there is no error being throw. It would mean that https://github.com/owtf/owtf/blob/9207e4bccf41d155067e7135e653ed2ae5447051/plugins/web/semi_passive/Session_Management_Schema%40OWTF-SM-001.py#L21 is actually freezing the program execution.

**Comment by viyatb** [comment]
Closed in https://github.com/owtf/owtf/commit/f3f65ea91d3f73d34f3dac403c80d98683ea2d75
