### ISSUE TITLE
Passive plug ins captcha bypass

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#452]
The passive plug-ins which are using google hacking may ask the user to type a CAPTCHA which is really annoying.
Potentially the CAPTCHA can be bypassed by opening the "google hacking urls" to different google domains.
Ex
google.co.uk
google.gr
google.se
and etc.

**Comment by DePierre** [comment]
IMO this is something the passive should do themselves and it's none of OWTF's business.

**Comment by 7a** [comment]
I found this too, spreading searches across Google subdomains should
hopefully decrease the CAPTCHA rate.

**Comment by 7a** [comment]
The problem is the Google CAPTCHA after you open all in tabs a few times,
it is really annoying :p

**Comment by mrtunglx** [comment]
Auto Bypass Google's reCaptcha (Captcha V2)
Only 10$ for imacros code or 15$ full setup any site!
Paypal or Bitcoin.
Video demo: https://www.facebook.com/lamborghini0000000/videos/149454865395433/
Contact: https://www.facebook.com/lamborghini0000000
Thanks!
