### ISSUE TITLE
Clean up colours from various tools prior to saving it in a file

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#456]
Tools such as hoppy, UA-Tester and others show pretty colours on the CLI.
Unfortunately, as OWTF saves their output and the output files are reviewed, this looks poorly, is harder to read and even wastes some disk space :)

It would be nice if OWTF had a generic "tool output clean-up" filter to avoid saving all this useless garbage.

**Comment by anantshri** [comment]
a lot of these tools might have some obsecure commandline option which can strip color's. We can try using it. Also if they don't have one lets also go one step more and ask dev's to add an option of non colored output.

**Comment by tunnelshade** [comment]
We already run such tools like whatweb etc.. by disabling color output. I couldn't find any such switch for UA-Tester and hoppy

**Comment by 7a** [comment]
I think we should have a generic "no colour" wrapper for tools that do not
support "no colour" output, after all, it's us that save stdout into files,
not them :)

**Comment by tunnelshade** [comment]
Yes, wrapper is the way to go ;)

**Comment by delta24** [comment]
There are a number of ready solutions already available at http://unix.stackexchange.com/questions/4527/program-that-passes-stdin-to-stdout-with-color-codes-stripped.
Please vote on which will be easiest to implement and also robust. :)

**Comment by tunnelshade** [comment]
One way that I would recommend is to use a `python regex` in the blocking shell class itself, which can be used to strip the colors from output just before the return from [shell_exec_monitor](https://github.com/owtf/owtf/blob/master/framework/shell/blocking_shell.py#L115)

**Comment by delta24** [comment]
Fixed in 77859e5 (tested, please check!)
