### ISSUE TITLE
Suggested improvements for the transaction log 

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#458]
Currently, the transaction log features a bunch of proxified http requests which is really awesome :)
This said, a number of relatively small changes will make a huge difference in usability:
1) More pagination options would be nice: For example, 1k, 2k and/or a textbox where the user can type whatever.
2) The response size is a CRITICAL, currently missing column: Sometimes this is the only useful indicator for custom 404 pages that return 200 OK codes.
3) The timestamp is also important and should be displayed on the left
4) The column names should sort when clicked, this would be very useful to see slower requests, sort by URL, etc. cumulative sorts -if easy- would be even more awesome :)
5) Optionally something like ZAP has on the "Tags" column would be nice (maybe we can do this later): In ZAP this features useful summary words like "comment, password, etc."

**Comment by tunnelshade** [comment]
+1 on the tags column

**Comment by delta24** [comment]
- [x] Response size column done
- [ ] The pagination control you are referring to is "input" style for Datatables. I tried implementing, but it seems buggy and the buttons wouldn't appear. You have to include a external plug-in from https://github.com/DataTables/Plugins/tree/master/pagination.

**Comment by tunnelshade** [comment]
Look [here](https://www.datatables.net/plug-ins/pagination/input) for the input style pagination plugin

**Comment by delta24** [comment]
The input style pagination plugin is outdated and not compatible with the datatables version we are using.    http://stackoverflow.com/questions/28181468/datatables-pagination-plugin-for-input-not-working

**Comment by tunnelshade** [comment]
Then you can maybe write a custom input and bind it to DataTables. The REST API uses **limit** get parameter to specify the number of returned records.

**Comment by delta24** [comment]
@7a  I implemented this in December last year. The rows are set default to 100 per page and has full pagination numbers. (e566bd147a29a855f591d68fb5eb0da15c153a3b) Can I close this issue?

**Comment by delta24** [comment]
Also implemented in the worklist table in 40d8e015275c17047e4b4e0adfe5cd2d8a10f8dd.
