### ISSUE TITLE
Rank should collapse the plugin, at least in some cases

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#459]
When only 1 plugin is being displayed, and this is ranked by the user, the most likely desired behaviour is that the plugin is collapsed. This was the behaviour in the old report, btw :)

In general, we need to improve click-flow and reduce the number of clicks required to navigate the report, this is a small step in that direction

**Comment by saganshul** [comment]
@7a  I am not understanding what you actually want to say in issue. Do you want to say that on clicking the rank button, plugin should collapse or something else.

**Comment by 7a** [comment]
Yes, exactly: when you rank a plugin you have already seen it and therefore
the plugin should collapse, this saves the user at least 1 click x plugin

**Comment by saganshul** [comment]
"When only 1 plugin is being displayed" what do you mean by this sentence? this can be done for every ranking right?

**Comment by delta24** [comment]
Closed in 02566fcb37762820e0292c9dcf2e2d475ae34302.
