### ISSUE TITLE
Can you guys add feature to scan I2P sites? Eepsites.

### ISSUE THREAD

**Issue by kurtcoke** [owtf/owtf#461]
Not really a issue. More of a feature request.

**Comment by delta24** [comment]
A paper on  **Identifying the true IP/network identity of I2P service hosts** presented at **BlackHat** may give some ideas. 
http://www.irongeek.com/downloads/Identifying%20the%20true%20IP%20of%20I2P%20service%20hosts.pdf

**Comment by tunnelshade** [comment]
@kurtcoke This is easy to use as of now. Just point OWTF to your local i2p proxy port just like you do it in your browser. Since you have an i2p domain name and network is routed through i2p, you can scan eepsite like any other. For outbound proxy settings, see the settings page in OWTF UI

**Comment by DePierre** [comment]
@tunnelshade Can we close this then? Since using OWTF's proxy settings allows scanning I2P websites.

**Comment by tunnelshade** [comment]
Yep. @kurtcoke Please reopen if you have any queries on this

**Comment by 7a** [comment]
Can we make it more intuitive? Maybe we need a quick how to page to point
our users to? :)
