### ISSUE TITLE
multiple responsive web ui issues

### ISSUE THREAD

**Issue by g4l4drim** [owtf/owtf#463]
On a 1024px wide screen, the add worker button is missplaced
![overflowing_add_worker_button](https://cloud.githubusercontent.com/assets/2065368/7704647/fe066396-fe3f-11e4-93af-4c923dc05b50.png)

when gui is resized, the target information display start to mess up

at a given size its ok:
![capture du 2015-05-19 08 09 18](https://cloud.githubusercontent.com/assets/2065368/7704818/f94331da-fe40-11e4-98e9-dbe4ee2f8bb4.png)

resizing up widths start to mess up things
![capture du 2015-05-19 08 09 24](https://cloud.githubusercontent.com/assets/2065368/7704822/00867344-fe41-11e4-9f9c-df602e6f8ca7.png)

and mess up more
![capture du 2015-05-19 08 09 28](https://cloud.githubusercontent.com/assets/2065368/7704857/249e8cee-fe41-11e4-8ecb-0c2ff861e483.png)

**Comment by delta24** [comment]
fixed in 555e52e.
