### ISSUE TITLE
What is the hurdle in doing passive scan's

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#464]
Hi Folks,

For a large number of passive scan results we are providing a link what are the possible reason's we are not doing a scan and giving output in our own report.

I assume they might have some kind of rate limit for some sites but for a lot of others we should be able to get direct response or by leveraging something like Ghost.py a screenshot.

Will make the report a bit more comprehensive

-Anant

**Comment by delta24** [comment]
I think this is because passive means that no traffic from the testing PC to the target. IMHO this is what @7a said in his initial OWTF presentations: that even before the go-ahead is given, the pentester can do valuable recon. (hence no direct traffic to the target is generated from the pentester's server.)

**Comment by anantshri** [comment]
I am not asking to send traffic to target but rather send traffic to somethings like shodan etc and get the details instead of just providing links.

May be at this point we can look at including recon-ng (if not done already) and poll its output for final report.

**Comment by tunnelshade** [comment]
Hey guys, I think screenshots can be the way to go because scraping becomes very difficult. And screenshots will help a lot especially when something like google search, it can be easily spotted if there are any results.

**Comment by anantshri** [comment]
exactly some might have anti automation etc. But whatever can work, taking a screenshot of the page would be simplest way to give actionable visual intel. It would not be of much use to machines as in parsable output but atleast before clicking on the link person would have an idea that this is what they can expect.

**Comment by delta24** [comment]
Yes, then this is feasible using PhantomJS.  :+1:

**Comment by delta24** [comment]
Move to reboot (PhantomJS will be the requester there) ?
