### ISSUE TITLE
XSS reports on http://xssposed.org/

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#465]
If possible we should have an integration of this also which might list XSS already found by people on XSSPosed.org

**Comment by 7a** [comment]
yes, this is in line with other similar website integrations like:
https://www.punkspider.org/ (which we have an issue for)
http://www.zone-h.org/ (which lists defacements for urls)

Under this issue, it would be nice to integrate with both xssposed.org and www.zone-h.org, which will list found XSS or defacements respectively and are great passive tests.

Thanks @anantshri ! :)

**Comment by tunnelshade** [comment]
Punk Spider and ZoneH are already added :)

**Comment by 7a** [comment]
Did we get XSSPosed.org covered too? Thanks!

**Comment by tunnelshade** [comment]
Yes, we did :)
