### ISSUE TITLE
Evaluate the use of extracting URIs from different file inputs

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#468]
For example, we can extract extra URIs and hosts from a `pcap` or (Wireshark's `pcap-ng`) file.
A button to upload the file and extract all this relevant info will be a good way to go :)

**Comment by DePierre** [comment]
@delta24 I like that idea ♥ Might not be a priority but it would be nice to that feature implemented one day.
Do you know any interesting python project to parse pcap files? AFAIR last time I tried to parse a pcap, it was kind of a pain in the ass.

**Comment by delta24** [comment]
Need to do some research on that one :)

**Comment by delta24** [comment]
Moving this to reboot :)
