### ISSUE TITLE
Metasploit msfcli is deprecated. OWTF plugins should be updated.

### ISSUE THREAD

**Issue by GautamAnghore** [owtf/owtf#469]
On a fresh installation of owtf from master branch using commands 
```
git clone https://github.com/owtf/owtf
cd owtf
./install/install.py
./owtf.py
```
and then on running PTES 001, the following error occurred:
![rake-error-full](https://cloud.githubusercontent.com/assets/7152214/8214681/7595b2da-1548-11e5-975e-075fa1d8013f.png)

**Comment by DePierre** [comment]
@GautamAnghore Hi and thanks for the issue but this is not a problem from OWTF. It is in fact a problem with your metasploit ruby installation. Better ask them ;)
Also, a pastebin is usually more practical than a screenshot but I suppose you had no other options.

By the way, check the develop branch of the project! Lot of nice stuff going on there!

If you need anything else, let us know ;)

**Comment by DePierre** [comment]
Might be worth keeping as a note for the msfcli deprecation though

**Comment by GautamAnghore** [comment]
@DePierre Thanks :+1: . I'll try the develop branch of the project.

**Comment by DePierre** [comment]
Updated the issue title to emphasize on the msfcli deprecation warning in @GautamAnghore's screenshot.

**Comment by DePierre** [comment]
Clone of #399
