### ISSUE TITLE
The grep stats for header matche percent are incorrect

### ISSUE THREAD

**Issue by tunnelshade** [owtf/owtf#470]
There seems to be a bug in header matches plugin. The number of transactions matched are incorrect.

**Comment by 7a** [comment]
Is this consistent behaviour or are steps to replicate needed? :)

2015-06-18 8:48 GMT+02:00 Bharadwaj Machiraju <notifications@github.com>:

> There seems to be a bug in header matches plugin. The number of
> transactions matched are incorrect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owtf/owtf/issues/470>.
>



-- 
Abraham Aranguren
http://7-a.org

**Comment by tunnelshade** [comment]
This must be consistent. Just use XSS protection header check against a site like facebook. The percentage must be 100% since only **facebook.com** is in scope. But instead we get some random percentage

**Comment by delta24** [comment]
Just to be sure, which plugin is this?

**Comment by delta24** [comment]
Verified one-off error with `https://github.com` - improper configuration on Facebook's side.
