### ISSUE TITLE
DNSpider will not download

### ISSUE THREAD

**Issue by mavensecurity** [owtf/owtf#471]
The connection times out eventually.  I tried this from several geographic points of origin.  No joy.
Same result for http://www.agarri.fr/docs/wordlists.tgz

Perhaps the site is down temporarily.

Here is sample of what I see happen:
$ wget http://www.agarri.fr/docs/dnsspider-0.6.py
--2015-06-18 21:39:14--  http://www.agarri.fr/docs/dnsspider-0.6.py
Resolving www.agarri.fr (www.agarri.fr)... 92.243.29.213
Connecting to www.agarri.fr (www.agarri.fr)|92.243.29.213|:80... connected.
HTTP request sent, awaiting response...

**Comment by 7a** [comment]
Strange, works perfectly for me right now, could you try again @mavensecurity ?

wget http://www.agarri.fr/docs/dnsspider-0.6.py
--2015-06-19 20:43:23--  http://www.agarri.fr/docs/dnsspider-0.6.py
Resolving www.agarri.fr (www.agarri.fr)... 92.243.29.213
Connecting to www.agarri.fr (www.agarri.fr)|92.243.29.213|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10173 (9.9K) [text/x-python]
Saving to: `dnsspider-0.6.py'

100%[=>] 10,173      --.-K/s   in 0.08s   

2015-06-19 20:43:23 (123 KB/s) - `dnsspider-0.6.py' saved [10173/10173]

**Comment by tunnelshade** [comment]
This was a temporary outage @mavensecurity 

For more info: https://twitter.com/viyat/status/611788929063190528
