### ISSUE TITLE
potential command to add to the install scripts (develop branch)

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#473]
Should we run the following command towards the beginning of the Kali installer?

pip install --upgrade pip

Reasoning:
There are a bunch of warnings like the following when you install OWTF in the latest Kali, and maybe things work more smoothly after this?

You are using pip version 6.0.8, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by tunnelshade** [comment]
Most of the time pip won't interfere with what it is installing as of now. We are not having an issue with pip 6.0.8 . Upgrading pip at the start can be implemented.

**Comment by delta24** [comment]
IMO keeping in mind the issue #474, we should atleast add these:

```
pip install --upgrade pip
 rm -rf /usr/lib/python2.7/dist-packages/setuptools.egg-info
```

**Comment by 7a** [comment]
Sounds good to me, but please let's 1st:
1) Backup before we delete things (so that the user has the option to
rollback, if needed)
2) prompt the user before running things like "rm -rf directory" on the
user filesystem.

Maybe something like:

Delete /usr/lib/python2.7/dist-packages/setuptools.egg-info? (y/n)
(recommended, solves some issues)

Then, if "yes" is chosen:
1) We backup the system directory we are about to remove (IMPORTANT: add
timestamp to backup, to ensure a previous backup does not break the install
script, i.e. make the directory different each time)
NOTE: Here it would be nice if we showed a message like "directory backed
up to path/to/new/location"

2) We can now safely delete because: a) we prompted the user (who gave
consent) + b) we backed up the directory

Because of all of the above, the "mv" command might be a better way than
"rm -rf", i.e.
mv /usr/lib/python2.7/dist-packages/setuptools.egg-info
/usr/lib/python2.7/dist-packages/setuptools.egg-infoBACKUP20150626



2015-06-25 14:05 GMT+02:00 Viyat Bhalodia <notifications@github.com>:

> IMO keeping in mind the issue #474
> <https://github.com/owtf/owtf/issues/474>, we should atleast add these:
>
> pip install --upgrade pip
>  rm -rf /usr/lib/python2.7/dist-packages/setuptools.egg-info
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owtf/owtf/issues/473#issuecomment-115224959>.
>



-- 
Abraham Aranguren
http://7-a.org

**Comment by delta24** [comment]
Ok, I'll change that bit :)

**Comment by DePierre** [comment]
@delta24 Is this issue closed thanks to your commit?

**Comment by delta24** [comment]
Yes
