### ISSUE TITLE
SQLAlchemy bug when a large response body is inserted into the DB

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#476]
Following error occurs sometimes (dependent on target)  - looks like a `sqlachemy` issue,

```
OperationalError: (OperationalError) index row size 7656 exceeds maximum 2712 for index "grep_outputs_name_output_target_id_key"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

> Update: @tunnelshade : This happens when huge comments are found in the response body.

**Comment by DePierre** [comment]
@delta24 @tunnelshade Any fix on its way? Where are we standing here?

**Comment by tunnelshade** [comment]
@DePierre Trying to find ways to fix this. We cannot control the comment size, so we have to find a hack

**Comment by DePierre** [comment]
@tunnelshade If the problem only happens when inserting these comments into the database, we could simply split/slice them before into chunks? And then add one chunk at a time. Is that possible?

**Comment by 7a** [comment]
Wouldn't full text indexing solve the problem + be more appropriate for
responses? Take a look at the error message :)

Consider a function index of an MD5 hash of the value, or use full text
indexing

**Comment by delta24** [comment]
full text indexing for responses  (because their raw size is unpredictable) is way to go IMHO :)

**Comment by delta24** [comment]
Fix on the lines of this: http://stackoverflow.com/questions/32040868/hashed-primary-key

Any takers :) ?

**Comment by delta24** [comment]
Tested on various websites including https://facebook.com, https://google.com and https://reddit.com. I'll reopen this if the error creeps up again (this must have been fixed by the new `sqlalchemy` update).
