### ISSUE TITLE
Getting error while running plugins. Error "Oops! Server replied: Bad Request"

### ISSUE THREAD

**Issue by sukudo** [owtf/owtf#481]
Hi Team,

While running the plugins against a target in the tool, I am getting 'Oops! Server replied: Bad Request'. Not really sure, what is the issue.

Could you please help.

Here is the screenshot for refernece:
![owtf error](https://cloud.githubusercontent.com/assets/13011937/8470580/b85c35ee-205b-11e5-9b92-848f0aed1e8a.png)

Thanks,
Sushil

**Comment by DePierre** [comment]
@sukudo Would it be possible to copy-paste the logs from ``/tmp/owtf/ui_server.log``?

**Comment by DePierre** [comment]
@sukudo I would like to know if you were still willing to share the log files to help us investigate?

**Comment by delta24** [comment]
@sukudo There must be some error in the Tornado server. Can you share the log files?

**Comment by delta24** [comment]
Closing (because no response and lack of information). I'll reopen this if a new issue is found regarding this.
