### ISSUE TITLE
Tool Suggestion: GIT/SVN/Mercurial extraction

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#485]
If .git or .svn etc are found we can look at getting data or atleast metadata out of it.

Tools that can be integrated.
https://github.com/evilpacket/DVCS-Pillage
https://github.com/anantshri/svn-extractor (self-promotion on this one)

**Comment by DePierre** [comment]
Worth adding to the plugins IMO. @7a @tunnelshade what do you guys think?

**Comment by tunnelshade** [comment]
Yes definitely @DePierre . Thanks for the suggestion @anantshri

**Comment by 7a** [comment]
Yes please, any takers? :)

**Comment by delta24** [comment]
> @DoomTaper: I have added plugin SVN-Extractor DoomTaper@d150c3a
Can anybody review the changes?

**Comment by sachinkamath** [comment]
@delta24 can you assign me?

**Comment by delta24** [comment]
@sachinkamath it is already in a review phase.
And you cannot be assigned to an issue if you are not a member of the organisation.

**Comment by delta24** [comment]
We already use `svndigger` to get a large number of svn urls in the combined dictionaries (to be used with dirbuster) - so do we need to integrate SVN extractor? Will it find more urls?
