### ISSUE TITLE
Zest integration

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#49]
We would like to pursue Zest integration from within OWTF.
In particular, it would be very useful to have buttons within the OWTF report so that we can fire Zest actions in ZAP via Zest scripts.

The ideal way to do this, would be a generic "Zest script generator" that other modules can call from within OWTF so that the effort of having "Zest action buttons" on the report is as low as possible moving forward.

More context on Zest can be found on:
https://github.com/mozilla/zest/wiki
https://github.com/mozilla/zest
http://www.slideshare.net/psiinon/owasp-2013-appseceu

**Comment by delta24** [comment]
Initial implementation done by @dscarson during GSoC'14.
