### ISSUE TITLE
url check not working properly

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#494]
I am on kali 
When i run the command  "./owtf.py http://example.com"
it gives me ip of example.com lets say x.x.x.x
now if I run the command "./owtf.py https://example.com"
it was able to resolve the host and gives me the same ip but it shouldn't do that as https://example.com doesn't exist.
while in the framework if i write to add "example.com" without checking which one (http or https) exists it just added both of them.

**Comment by delta24** [comment]
`http` and `https` are just protocols. The hostname will be resolved to the ip of the webserver. :)
Even if your website doesn't have a SSL certificate, the ip of the webserver will still remain the same.

**Comment by DoomTaper** [comment]
@delta24 didn't it should check if domain is speaking https and then add it to db ?

**Comment by delta24** [comment]
Yes, that is a separate issue. See https://github.com/owtf/owtf/issues/108.

**Comment by DoomTaper** [comment]
Got it! :+1:

**Comment by 7a** [comment]
Originally, the idea was that:
1) If OWTF is given urls this is a web assessment
2) If OWTF is given domain names, this is 1st a network assessment: OWTF
should port scan the targets, figure out which ports speak http or https,
then run a web assessment on those

Not sure about how smoothly this works right now, looking forward to your
test results! :)
