### ISSUE TITLE
url encoding not working on command line interface

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#499]
After running command "./owtf.py http://www.hygeiabeauty.com/brystforstørrelse.html"
I got the error 
"UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46"

but If I run  "./owtf.py http://www.hygeiabeauty.com/brystforst%F8rrelse.html" 
plugins are working fine

**Comment by DoomTaper** [comment]
If I run "./owtf.py http://www.hygeiabeauty.com/brystforstørrelse.html" again then rather than showing 
"target already exists in db" 
prior error of adding same target occurs
"sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) duplicate key value violates unique constraint "targets_target_url_key"
DETAIL:  Key (target_url)=(http://www.hygeiabeauty.com/brystforstørrelse.html) already exists."

**Comment by DoomTaper** [comment]
The problem I am getting is how to filter targets only from sys.argv. The reason I want to filter sys.argv rather than using url_parser of cli_options.py is that after using url_parser the url 
" http://www.hygeiabeauty.com/brystforstørrelse.html " becomes " http://www.hygeiabeauty.com/brystforst\xc3\xb8rrelse.html" , now due to \x in url, quote() function is unable to encode it.
I am still working on that. Any suggestions ??

**Comment by DePierre** [comment]
@DoomTaper the error should be fixed thanks to 82ada63. I leave the issue opened until I have your confirmation that the bug is gone.

Thanks ;)

**Comment by delta24** [comment]
Yes, `utf-8` decoding should fix this :+1:

**Comment by DoomTaper** [comment]
Yes! It's working now. Thanks! :) :+1:
