### ISSUE TITLE
Not giving alternative ips

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#506]
If I run ./owtf.py for those domains having multiple ips (lets say google.com) then it is not showing them, just taking a single ip

**Comment by DoomTaper** [comment]
By using getaddrinfo() instead of gethostbyname() we have two advantages
1. get multiple ips if one has so 
2. it supports ipv6 as well

**Comment by tunnelshade** [comment]
We don't use that multiple IPs, but we have the all the IPs resolved. See [here](https://github.com/owtf/owtf/blob/master/framework/config/config.py#L358). `alternative_IPs` consist of all other IPs. It is already there, but we are not making use of this information

**Comment by DoomTaper** [comment]
"alternative_IPs" consist nothing when I run owtf.py for say google.com
