### ISSUE TITLE
Using a remote server

### ISSUE THREAD

**Issue by BrianHoldsworth** [owtf/owtf#510]
Unless I am overlooking some bit of configuration, it is not possible to utilize OWTF on a remote server. The access to the file storage, which is normally assigned to port 8010, only seems to work for localhost:8010 i.e. you have to have a local OWTF server.

This seems like a shortcoming if you want to share a server with a small workgroup as a collaboration aid during testing.

Additionally, the config options that do exist (SERVER_ADDR, UI_SERVER_PORT, FILE_SERVER_PORT) don't seem to offer the possibility of utilizing OWTF remotely over a single standard web port, like 443.

I have also not discovered an effective way of inserting a reverse-proxy, like nginx, to solve this dilemma. The browser client seems to "think it knows best" in trying to reference files on 'localhost' directly, instead of just relying on a URI scheme that would allow a proxy to direct requests to appropriate endpoints/ports, if that sort of backend architecture is truly desirable.

**Comment by 7a** [comment]
Hi Brian, I believe you can charge the listening IP to the host you are
using, if you do that, I would personally white-list client IPs on a need
to connect basis.

Let us know how this works out for you please :)

**Comment by BrianHoldsworth** [comment]
When you say "change the listening IP", are you referring to the "SERVER_ADDR" value in the "framework_config.cfg" file? I currently set this to 0.0.0.0, so that owtf listens on the correct IP and the UI works fine. It's when you want to access file on the FILE_SERVER_PORT (8010, by default) that the browser client decides it should route the request to "localhost".

**Comment by 7a** [comment]
Bharadwaj, can you chime in here?

**Comment by tunnelshade** [comment]
Hey, @BrianHoldsworth Ideally both file server and ui run on same interface. The redirection should be happening which seems buggy in this case. Please provide the following information so that debugging will be easier for us

+ Which plugin did you run?
+ What link is failing?

**Comment by delta24** [comment]
Hi @BrianHoldsworth you can do something like this:

- Generate an SSL certificate via Nginx
```
 sudo mkdir /etc/nginx/ssl
 sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
```
- Add this to the config (server block)
```
        listen 443 ssl;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
```
and restart nginx
- Of course you can add your own SSL cert :)

I've created a [barebones nginx config](https://gist.github.com/delta24/a6b1ce8a7c67f370c588) for your reference ;)


Also I think that I've fixed the buggy redirection in a previous commit. Can you check?
