### ISSUE TITLE
[develop] broken cookie parser

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#514]
plugin: Web_Application_Fingerprint/semi_passive

[!] unknown Cookie attribute: 'expires=Fri'
[!] unknown Cookie attribute: 'unrecognized'
[!] unknown Cookie attribute: 'expires=Fri'
[!] unknown Cookie attribute: 'unrecognized'

But wait, it is even more broken than that:

Testing For Cross Site Flashing (web/passive) __________
[!] unknown Cookie attribute: 'expires=Fri'
[!] unknown Cookie attribute: 'unrecognized'
[!] unknown Cookie attribute: 'expires=Fri'
[!] unknown Cookie attribute: 'unrecognized'
[!] unknown Cookie attribute: 'expires=Fri'
[!] unknown Cookie attribute: 'unrecognized'
[!] unknown Cookie attribute: 'expires=Fri'
[!] unknown Cookie attribute: 'unrecognized'
[!] Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 565, in _finalize_fairy
    fairy._reset(pool, echo)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 699, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 406, in do_rollback
    dbapi_connection.rollback()
OperationalError: SSL error: decryption failed or bad record mac

**Comment by marioskourtesis** [comment]
I had experienced something similar in the past.

**Comment by delta24** [comment]
@7a,  @marioskourtesis : definitely the cookie parser, looks like it doesn't take the edges cases **or** it is too strict in handling. I had a talk with the developer and she told me that an override class which accepts non-RFC cookies is the way to go.
