### ISSUE TITLE
[develop] plugin getting stuck stops the whole scan...

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#515]
The following plugin got stuck, with no output on the CLI, stopping the whole scan, I am amazed precisely *this* plugin can get stuck, can someone please take a look?

Plugin: Spiders Robots And Crawlers (web/semi_passive)

**Comment by DoomTaper** [comment]
I have done some partial fixing for the plugin in https://github.com/owtf/owtf/commit/1e76b70a33e120123412c8a19c55b7589be41f09.
I guess this fix runs the plugin (as when i printed out the status_msg it says successful) but when I go to the target page it just shows loading as in the screenshot but doesn't load the results. Any suggestions ?
![screenshot 41](https://cloud.githubusercontent.com/assets/10975138/12180172/063ca660-b5a1-11e5-9f8b-d14bc47db15e.png)

**Comment by delta24** [comment]
Closed in https://github.com/owtf/owtf/commit/84f22dd0c68447a2c90a88b92135419a7678c6ac.
