### ISSUE TITLE
Auto Bypass Google's reCaptcha (Captcha V2)

### ISSUE THREAD

**Issue by mrtunglx** [owtf/owtf#517]
Auto Bypass Google's reCaptcha (Captcha V2)
Only 10$ for imacros code or 15$ full setup any site!
Paypal or Bitcoin.
Video demo: https://www.facebook.com/lamborghini0000000/videos/149454865395433/
Contact: https://www.facebook.com/lamborghini0000000
Thanks!

**Comment by delta24** [comment]
Looks like spam :P

**Comment by DePierre** [comment]
I reported the account to GitHub.

**Comment by mrtunglx** [comment]
Not Spam!

**Comment by delta24** [comment]
@mrtunglx: then you don't post any buy / suspicious links because well they look pretty much like spam
