### ISSUE TITLE
install/install.py skip sudo password

### ISSUE THREAD

**Issue by SpoonBoy** [owtf/owtf#519]
I just recently cloned the owtf project on a Kali Sana, and was asked to run the following command : `python2 install/install.py`
I did so, but I forgot I was running it with a non-sudoer user.
So, I just `Ctrl+C` and the script kept on downloading the requirements.

```python
python2 install/install.py 
[*] Great that you are installing OWTF :D
[!] There will be lot of output, please be patient

(1) Kali Linux
(2) Samurai-WTF
(0) My distro is not listed :(
Select a number based on your distribution : 1
[*] Running following command
sh /home/user/git/owtf/install/kali/install.sh /home/user/git/owtf

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for user: 
user is not in the sudoers file.  This incident will be reported.
[sudo] password for user: 
[*] Installing pip
[*] Switching to /tmp/owtf-install/pip/6157
```

**Comment by delta24** [comment]
Hi, you need `sudo` to install some system and python packages. But the installer can proceed without that step. This behaviour is intended because some may already have the dependencies satisfied.

**Comment by 7a** [comment]
Would it make sense for the installer to be smart enough to handle this
alone? :)

**Comment by SpoonBoy** [comment]
when a user sends  `SIGINT`  he just wants the program to stop, regardless of dependencies already installed or not.

**Comment by delta24** [comment]
I check add a check to see if the user has `sudo` privileges, if not then do a clean stop. @SpoonBoy  @7a ?
