### ISSUE TITLE
Pip Import Error Kali Install

### ISSUE THREAD

**Issue by rakarivaldi** [owtf/owtf#520]
I have this error, what should I do?
![error](https://cloud.githubusercontent.com/assets/16013343/11392096/ecebe27c-9389-11e5-8773-0b1d0ea8582a.jpg)

**Comment by DoomTaper** [comment]
Take a look [here](https://github.com/owtf/owtf/issues/357)!

**Comment by delta24** [comment]
@rakarivaldi Did you try what @DoomTaper suggested?

**Comment by delta24** [comment]
Seems to be resolved in the issue referenced.  Please do `pip install -U pip`.  Closing for now...
