### ISSUE TITLE
Use a vulnerability database to provide more info in the report.

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#524]
Can't think of any specific use case however we might want to have a look at it for our own tool: https://github.com/vulndb/data

**Comment by delta24** [comment]
I think we can use it for displaying info wherever we have "Intended to show info in future" (in the plugins"

**Comment by delta24** [comment]
The project, ***vulndb*** has been inactive for a year now, I think we should go with vfeed (https://github.com/toolswatch/vFeed): in case - https://www.owasp.org/index.php/Winter_Code_Sprint#OWASP_OWTF_-_VMS_-_OWTF_Vulnerability_Management_System_.28FREE.21.29

**Comment by viyatb** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by anantshri** [comment]
Why close. i would say keep it open may be someone some day might be interested.

**Comment by viyatb** [comment]
Right, I intend to move this issue to https://github.com/owtf/addons as soon as I implement a pluggable, external addon system.
