### ISSUE TITLE
Unable to open directory from browser

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#525]
Reproduce
---
When you pass an OWTF target containing especial URL characters such as "?" on the file browser (i.e. "Browse Files" button) on any plugin, this fails to load because these characters are not urlencoded, hence the browser interprets them and OWTF fails to open the relevant directory.

Fix
---
Calling the relevant url encoding function will fix this problem, for example using `encodeURIComponent` from JavaScript.

 or

calling `escape` from Tornado template methods

**Comment by delta24** [comment]
The previous fix included using `quote_plus` from the urllib library. But it encoded '/' also, which resulted in bad links in the directory listing.
@DePierre thoughts on this?

**Comment by DoomTaper** [comment]
@delta24 have you tried using `safe` parameter of quote_plus like this `quote_plus(item, safe='/')` ?

**Comment by delta24** [comment]
No, that looks doable. Let me try :)
Thanks @DoomTaper!

**Comment by DoomTaper** [comment]
@delta24 Is this issue resolved?

**Comment by delta24** [comment]
nope, go ahead. :)
