### ISSUE TITLE
Workers do not pick items from worklist

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#527]
@7a : The workers do not pick up the work in the work list on first run. I reported this before, still happening, this is pretty bad because you could be creating more work in the middle of a scan and the workers should be able to pick up new work automatically
		
I think Control + C on the terminal will work, trying <-- that works, but still, users should not need to do that, we should pick up new work from the worklist as soon as it's added, this is a workaround, not a fix.

> Update:  Another odd behaviour: the workers take the worklist items if you try to remove the "stuck" worker  and add/remove a new worker

@tunnelshade ?

**Comment by tunnelshade** [comment]
The process that happens here

+ When a new work is added it is stored in the worklist table
+ The FileServer actually polls for free workers and if there are any then get the work and give it

The problem might be that some worker might be struct on some work. Then this is difficult to solve. Can you reproduce and try @delta24

**Comment by delta24** [comment]
@tunnelshade, to reproduce: Add a target and select say 2 groups of plugins: external, passive. I observed no direct activity on the console, and the `Worker-1` was idle.

**Comment by tunnelshade** [comment]
Please do the following things for debugging

+ Check if the periodic callback is happening (this actually polls the workers)
+ Check if the workers are visible as idle to this callback (Workers are different process and this callback happens in a different process)
+ Check if worklist is returning work

The error here is actually due to a failed db commit. Might be while saving work?

**Comment by offsecguy** [comment]
Hi delta24,

I am using lattest version, still facing same issue. I have to press ctr-c to get worklist loaded into workers.

**Comment by delta24** [comment]
Yes, I am still looking into it. I have a couple of options, and I'll fix this in a week. :)

**Comment by offsecguy** [comment]
Thanks bro :)

**Comment by delta24** [comment]
@tunnelshade I turned on the debug=True flag in the tornado servers and I got:

```
Process InterfaceServer-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/viyat/workspace/owtf/framework/lib/owtf_process.py", line 53, in run
    self.pseudo_run()
  File "/home/viyat/workspace/owtf/framework/interface/server.py", line 38, in pseudo_run
    self.server.start(0)
  File "/usr/lib/python2.7/site-packages/tornado/tcpserver.py", line 199, in start
    process.fork_processes(num_processes)
  File "/usr/lib/python2.7/site-packages/tornado/process.py", line 121, in fork_processes
    raise RuntimeError("Cannot run in multiple processes: IOLoop instance "
RuntimeError: Cannot run in multiple processes: IOLoop instance has already been initialized. You cannot call IOLoop.instance() before calling start_processes()
```

Could this be causing the issue?
