### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by sealmindset** [owtf/owtf#531]
Okay managed to get OWTF installed using the bootstrap script.  No errors reported after installing.  However, when attempting to execute, it reports that psycopg2, pycurl and six are missing. So, I checked if python is reporting any issues with the libraries.  All three  libs appear to be okay, ie no errors.  Even ran both variations of the install script, still reports them missing.

Also, the database tables, etc., are not installed due to permission fails, added a line to give the /root/owtf/install read/execute rights in the bootscrap script just before:

cd install/; python2 install.py (line 95)

Now the db gets setup, still cannot make it run.

**Comment by delta24** [comment]
Did you use latest OWTF (develop branch)?

**Comment by sealmindset** [comment]
No, did the master.  After much trial and error got it to work by:

# apt-get update && apt-get upgrade -y
# apt-get dist-upgrade -y
# service postgresql start
# update-rc.d postgresql enable
# cd /opt
# git clone -b lions_2014 https://github.com/owtf/owtf.git
# pip install --upgrade cffi
# apt-get install libssl-dev
# pip install --upgrade -r /opt/owtf/install/owtf.pip
# pip install --upgrade beautifulsoup4 lxml Markdown psycopg2 pycurl six
# apt-get install libpq-dev
# chmod u+x /opt/owtf/install/install.py
# /opt/owtf/install/./install.py
# /opt/owtf/script/./db_setup.py init  
# cd /opt/owtf/profiles/general

Edit

# vi default_backtrack.cfg
Change TOOL_METASPLOIT_DIR

/usr/share/metasploit-framework
Edit

# vi default.cfg
Change TOOL_METASPLOIT_DIR

/usr/share/metasploit-framework 

msfcli is now replace with msfconsole -x

# find /opt/owtf -type f -print0 | xargs -0 sed -i 's/msfcli /msfconsole -x /g'

**Comment by delta24** [comment]
Which distro are you using? If you use Kali, then just `git clone https://github.com/owtf/owtf; python2 install/install.py` should do it!

**Comment by sealmindset** [comment]
Initially I did a dash b master, develop and then lions_2014.  The same issue kept popping up.

**Comment by mushinnomushin** [comment]
I'm getting a similar error when trying to run OWTF in Kali 2 x64.

```The following python libraries seem missing : 
   beautifulsoup4,lxml,Markdown,psycopg2,pycurl,six```

**Comment by sealmindset** [comment]
@mushinnomushin 

Have you tried this?

pip install --upgrade cffi
apt-get install libssl-dev
pip install --upgrade -r </YOUR/PATH/TO>/owtf/install/owtf.pip
pip install --upgrade beautifulsoup4 lxml Markdown psycopg2 pycurl six

**Comment by mushinnomushin** [comment]
That worked. Thanks!

**Comment by delta24** [comment]
@mushinnomushin Even if it shows the libraries missing error, run the installer again. :)
