### ISSUE TITLE
Use CI tools for build status checks

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#533]
Besides build status check we can also check build health by running it against these targets 

http://demo.testfire.net
http://hackazon.webscantest.com
https://public-firing-range.appspot.com
http://testaspnet.vulnweb.com
http://testasp.vulnweb.com
http://testhtml5.vulnweb.com
http://testphp.vulnweb.com
http://www.webscantest.com
http://zero.webappsecurity.com

if any logic bug present most probably it will lurk its head then.

I will try and get this setup in next month or so.
- [x] Functional tests - build passing! (@Depierre)

**Comment by anantshri** [comment]
This would be massive work required as usual CI's like travis-ci provide us with default ubuntu vm and that might never have tools we are actually concerned with. so i suppose i might shift the whole thing to a developer side check via custom shell or python script. But would be keeping this on hold for my worklist for atleast a month.

**Comment by delta24** [comment]
@anantshri is this practical? How can we catch subtle tool errors programmatically like Travis builds?

**Comment by anantshri** [comment]
@delta24 initial idea looked nice conceptually but i have had 2 attempts at it and have not made much progress on it. This root of this idea was the fact that during the time of raising the issues configuration was a major issue and tools were missing or were getting stuck and hence to catch then we thought why not run some tests on public targets.
but i suppose a better approach would be if we have 
1) Internal test cases to validate sections.
2) a automated script which can run scan's on common targets locally and allow us to observe results and confirm that things are good.

but to be honest i am talking it all not practically doing hence can't be sure of practicality.

**Comment by delta24** [comment]
@anantshri I am closing this because of the inclusion of the Dockerfile. I will add the instructions to test OWTF before merging or committing a breaking change in a separate, clean Docker container (using the list of sample targets).
