### ISSUE TITLE
Installer Issues

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#534]
1) Site Down : http://unspecific.com/ssl/ssl-cipher-check.pl
So wget is still stuck trying to get me ssl-cipher-check.pl 
we should atleast put a limit on number of tries to be made.

2) We need to ensure following tools are absolutely present 
git, unzip
We rely on this assuming they will be present where as they might not be.

Would report more inconsistencies if i find something.

**Comment by anantshri** [comment]
Why no certificate check for hoppy. Certificate seems right to me. We should not be doing it wrong. ssl is present so use it properly.
https://github.com/owtf/owtf/blob/78cca27e2a28fd57afcfb816a887a4a8297d438f/install/distro-independent.cfg#L22

All wget-s should have a timelimit --tries=3 is what i am suggesting for all wget

**Comment by delta24** [comment]
@anantshri  We do not use `git` anywhere in the installation process and `unzip` is present by default on most distros.
However `--tries=3` is the way to go for wget. :)

**Comment by anantshri** [comment]
that's git being used : https://github.com/owtf/owtf/blob/78cca27e2a28fd57afcfb816a887a4a8297d438f/install/distro-independent.cfg#L30

**Comment by delta24** [comment]
ah, ok :/

**Comment by anantshri** [comment]
Just a quick question. We have distro independent stuff and distro specific stuff. I would assume distro independent stuff should be installed first and then distro specific. But looks like installer is doing inverse. Just wanted to confirm if that's by design or something just ignored.

i suppose https://github.com/owtf/owtf/blob/develop/install/install.py#L119 should be at  https://github.com/owtf/owtf/blob/develop/install/install.py#L112 if someone can confirm i will create a pull request.

**Comment by anantshri** [comment]
I suppose this check (https://github.com/owtf/owtf/blob/develop/install/install.py#L131) should again only run if we have a kali setup. Which we anyways have already detected above. so a conditional statement should be added. Any specific concerns otherwise i will raise a pull request for this change too.

**Comment by delta24** [comment]
@anantshri Yes, some commit must've jumbled up the order. Send the PR :)
