### ISSUE TITLE
Installation in Kali is not working correctly

### ISSUE THREAD

**Issue by DarKnight--** [owtf/owtf#544]
I ran `install.py` for four times, each time zest was downloaded irrespective of its presence.

If the internet connection is down due to any reason during installation of tools, all the directories are made, which prevents further installation of them during next run.

[installation_output.txt](https://github.com/owtf/owtf/files/107257/installation_output.txt) terminal output of install.py.

- I run : ran successfully
- II run : ran successfully

> Deleted tools which gets install by `install.py`

- III run : unsuccessful (removed Internet connection in middle)
- IV run : completed  successfully

**Results:**

- zest installed each time I ran `install.py` (Line No. 63, 338, 604, 1338)
- In VI run, look after line no. 1344, all the installation were skipped due to creation of directories during III run

**Comment by delta24** [comment]
So this is resolved? @DarKnight--

**Comment by DarKnight--** [comment]
@delta24 Yes, I again tested with deleting some tools and left empty folders, zest was not downloaded and it downloaded all the empty directory tools.
