### ISSUE TITLE
Plugin Filter Display not working properly

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#547]
On the target list page after clicking on "run" button and then filtering plugins on any basis (lets say on the basis of Name I wrote "http"). Now refresh the page and again click on "run" button, plugins are filtered on "http" basis but it doesn't show "http" in the filter box. Although it doesn't show anything but I have to delete "http" from that filter box to let it show all plugins.

**Comment by delta24** [comment]
That must be a frontend error. Can you try changing the behaviour to **not** persist the search results?

**Comment by delta24** [comment]
After some thought, I don't think that this should be changed. Imagine you want to run some specific plugins and you have already selected a few of them (say 20). Now without `stateSave`, this selection would not persist an accidental click outside the modal window.
@7a?

**Comment by DoomTaper** [comment]
I think the solution would be to show the user input even after the page reload. @delta24 ?
