### ISSUE TITLE
README - GSoC 2016 wiki link broken

### ISSUE THREAD

**Issue by thc202** [owtf/owtf#561]
The link, in README.md, for GSoC 2016 wiki page is broken, it seems it is now:
https://github.com/owtf/owtf/wiki/Google-Summer-of-Code-2016:-Getting-started
the current link:
https://github.com/owtf/owtf/wiki/Getting-started-with-Google-Summer-of-Code-2016
ends up being redirected to main wiki page.

**Comment by delta24** [comment]
Fixed in 4b4d032cf354b04fbf79881a78c41406e1e13847
