### ISSUE TITLE
Increase readability of manual installation output on terminal.

### ISSUE THREAD

**Issue by karandesai-96** [owtf/owtf#564]
Currently there are two installation methods: Through bootstrap script and through python script.

* The output of bootstrap script is comparatively more readable and easy to keep track as different colors are used for display.

* A similar workaround is needed for manual installation through python scripts as the output through python script sometimes gets lost among the output log of apt-get and wget while execution.

* The colors and bold fonts should be implemented in Python scripts, similar to bootstrap scripts.

**Comment by karandesai-96** [comment]
I think an `enhancement` tag is appropriate for this issue. Please assign it to me, I have got a workaround :smiley:

**Comment by tunnelshade** [comment]
@karandesai-96 You cannot be assigned as your not yet a core contributor. Since you already commented over here, go ahead with a PR

**Comment by karandesai-96** [comment]
Oh, ok. I did not know much about constraints of assigning issues on Github. Nevertheless, I will work upon a PR and hopefully would be able to send it within a couple of hours :smiley:
