### ISSUE TITLE
Installation problem on ubuntu

### ISSUE THREAD

**Issue by DarkPrince304** [owtf/owtf#566]
Hello,

I was installing OWTF Build on my Ubuntu machine but while installation it seemed that some package werent installed succesfully. I noticed this when I ran the command "./owtf.py"
Here's what I got after this:

```
The following python libraries seem missing : 
   Markdown,pexpect,psycopg2,PTP,pycurl,python-owasp-zap-v2,PyVirtualDisplay,rdflib,selenium,SQLAlchemy,tornado

Haven't you run the install script? 
   python2 install/install.py

If you are sure you ran the install script, install the missing libraries seperately
   pip install --upgrade -r install/owtf.pip
```

So I ran the command ` pip install --upgrade -r install/owtf.pip ` . But it got me this:
```
Requirement already up-to-date: beautifulsoup4==4.3.2 in /usr/lib/python2.7/dist-packages (from -r install/owtf.pip (line 6))
Requirement already up-to-date: cookies==2.2.1 in /usr/local/lib/python2.7/dist-packages (from -r install/owtf.pip (line 7))
Requirement already up-to-date: ipaddr==2.1.11 in /usr/local/lib/python2.7/dist-packages (from -r install/owtf.pip (line 8))
Collecting lxml==3.4.0 (from -r install/owtf.pip (line 9))
  Using cached lxml-3.4.0.tar.gz
Collecting Markdown==2.5.1 (from -r install/owtf.pip (line 10))
  Using cached Markdown-2.5.1.tar.gz
Collecting pexpect==3.3 (from -r install/owtf.pip (line 11))
  Using cached pexpect-3.3.tar.gz
Collecting psycopg2==2.6.1 (from -r install/owtf.pip (line 12))
  Using cached psycopg2-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-69V4Cp/psycopg2**
```

I would like to confirm this with someone else too if he/she has the same problems on Ubuntu?

Thank you

**Comment by delta24** [comment]
The errors suggest either you don't have the python developement headers present (which are needed to build `psycopg2` package (native C extensions).
You can resolve it by `sudo apt-get install install python-dev libpython-dev libffi-dev`

OR your `setuptools` installation is corrupt. You can fix that by `sudo pip install --upgrade setuptools`.

**Comment by DarkPrince304** [comment]
I tried the above methods but it still won't work :\

**Comment by Ahiknsr** [comment]
can you try installing again after running `sudo apt-get install libpq-dev python-dev`

**Comment by sharad1126** [comment]
@DarkPrince304 I tried to install owtf on my mac as well as my friends ubuntu. owtf got installed on both but @7a on mac while creating a database, it showed some error. But is installing on ubuntu easily. I just installed git, python-3.4.4 and the direct command given on wiki page of owtf.
<img width="569" alt="screen shot 2016-03-05 at 8 32 35 pm" src="https://cloud.githubusercontent.com/assets/17527468/13548228/94159aa8-e311-11e5-8df5-4e416476da92.png">

**Comment by sachinkamath** [comment]
@sharad1126 , were you root? I see a `Operation Not Permitted` in your screenshot.

**Comment by delta24** [comment]
Root privileges are not required - only `sudo` access.

**Comment by sharad1126** [comment]
@sachinkamath yes I did used sudo.

**Comment by sachinkamath** [comment]
@sharad1126 , can you upload the entire installation output to a gist and submit the link here? It will help us debug the problem better.

**Comment by delta24** [comment]
@sharad1126 @DarkPrince304 any updates?

**Comment by sharad1126** [comment]
@sachinkamath will upload it.
@delta24 tried, but same error on mac.

**Comment by delta24** [comment]
@tunnelshade can you chime in? Mac problems ;)

**Comment by tunnelshade** [comment]
Everyone, the support for Mac is not present as of now and pretty pointless. Why? Because OWTF needs many tools and run and your mac installation will get ruined with all those. Use a VM or a VPS!!

**Comment by RahulPratapSingh** [comment]
Getting the same installation problem in Kali 2.0 (Sana).

Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.

Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-CVxFIC/psycopg2
Storing debug log for failure in /root/.pip/pip.log

Snippet of pip.log
<pre><code>
Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Mdyj3q/psycopg2
Exception information: 
 Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Mdyj3q/psycopg2
</code></pre>

**Comment by sachinkamath** [comment]
@RahulPratapSingh Try `sudo apt-get -y install postgresql `

**Comment by delta24** [comment]
@RahulPratapSingh we already install `postgresql-server-dev-all` as a part of the Kali Linux installation so if seems that you are missing `postgresql` or you did not run the installer correctly. Either way are you on the latest develop branch ? 

I cannot replicate your changes.

**Comment by RahulPratapSingh** [comment]
@delta24 I followed the recommended steps as shown on main page of OWTF
<pre><code>
wget -N https://raw.githubusercontent.com/owtf/bootstrap-script/master/bootstrap.sh; bash bootstrap.sh
</code></pre>

I think the problem was because of "libpq-dev". It was not able to locate the package in kali 2.0

I just figured out a way. It's working perfectly now. Added the following repositories in sources.lst
<pre><code>
deb [arch=i386,amd64,armel,armhf] http://http.kali.org/kali kali-dev main contrib non-free
deb [arch=i386,amd64,armel,armhf] http://http.kali.org/kali kali-dev main/debian-installer
deb-src http://http.kali.org/kali kali-dev main contrib non-free
deb [arch=i386,amd64,armel,armhf] http://http.kali.org/kali kali main contrib non-free
deb [arch=i386,amd64,armel,armhf] http://http.kali.org/kali kali main/debian-installer
deb-src http://http.kali.org/kali kali main contrib non-free
deb http://repo.kali.org/kali kali-bleeding-edge main

## Security updates
deb http://security.kali.org/kali-security kali/updates main contrib non-free
</code></pre>

Now, installed OWTF again. It downloaded the required packages and installed without any error. Solved some subtle problems too like error to locate archini and tor.

**Comment by delta24** [comment]
@RahulPratapSingh Which option did you choose? Please choose the develop branch as most of the errors are fixed in it.

**Comment by RahulPratapSingh** [comment]
@delta24 I didn't choose develop branch. I chose option 1) OWTF 1.0.1 Lionheart 
Sure, I will choose it for further reports. Thank you :)
