### ISSUE TITLE
Refactor and cleanup codebase

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#581]
- Make OWTF (the whole codebase) PEP8 (modified 120 char limit) compatible.
  That includes whitespace, indentation errors, etc
- Follow proper function naming conventions everywhere.
- Remove support files/code for Kali 1.x and Backtrack versions.
- Proxy and DB interface optimization

**Comment by yashmehrotra** [comment]
@delta24 Hi, I would like to work on this bug. Can you assign it to me ?

**Comment by delta24** [comment]
@yashmehrotra You cannot be assigned as your not yet a core contributor. Since you already commented over here, go ahead with a PR.

**Comment by yashmehrotra** [comment]
@delta24 Oh... cool. I'll get started on the PR.

**Comment by sachinkamath** [comment]
@delta24 , Wouldn't it be better to use `autopep8` ?  In there, E501 is defined as > 79 characters but I'm sure it can be hacked upon.

**Comment by delta24** [comment]
No autopep8 please. They tend to increase work and break code more than they are helpful.

**Comment by hTrap** [comment]
##Description
As Discussed in #623, the checklist below is structured to contain
- One Directory ( if no of files < 5) per PR
- 5 files per PR

###Checklist
- [x] /agents (3 files)  : #660 
- [x] /dictionaries (1 file) : #661

**Comment by delta24** [comment]
- First sweep done

**Comment by delta24** [comment]
- [x] Second sweep done - final PEP8 formatting done including all plugins!
- [x] Removed Kali 1.x code and Backtrack support

**Comment by delta24** [comment]
Cleanup started in https://github.com/owtf/owtf/tree/cleanup.

**Comment by viyatb** [comment]
Merged in https://github.com/owtf/owtf/commit/520cdc01356be73a46a82db832ae04411aa36b7e.
