### ISSUE TITLE
Connection reset by peer - wget

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#592]
**Problem :**
When behind a firewall, (or a proxy that allows only certain user-agents), wget returns a `Connection reset by peer` error. I am currently behind a Sonicwall Firewall and the installation script failed to download most of the stuff. 

**Reason:**
This happens because the Firewall/Proxy blocks certain user agents from making connections. This can cause issues with the installation as the script continues to execute without actually installing the packages.

**Solution:**

Passing a `--user-agent` flag to wget can help tackle the problem. This way, the requests will look as if coming from a browser.

**Comment by luky-chen** [comment]
i has one problem likes this.how  could i  solve it?  ps  tell me!

**Comment by viyatb** [comment]
Have an alias in your `.bashrc` with something like `alias wget=wget --user-agent $@`

**Comment by luky-chen** [comment]
something looks like no use。did you do it？

**Comment by luky-chen** [comment]
otherwhise  its the problem of remote server。  while，thank you  all the time
