### ISSUE TITLE
Fix AUX plugins

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#602]
This is an aggregated meta-issue to bring back the `aux` plugins into a working state.

### Related issues:

- [ ] https://github.com/owtf/owtf/issues/125
- [ ] https://github.com/owtf/owtf/issues/126
- [ ] https://github.com/owtf/owtf/issues/128
- [ ] https://github.com/owtf/owtf/issues/386

**Comment by DoomTaper** [comment]
@delta24 I would like to work on this issue.I will look into above issues. @delta24 @DePierre Can you suggest me where to start from ?

**Comment by delta24** [comment]
@DoomTaper look where the `aux` plugin support broked( use `gitk` 's advanced search ;) ) and try to fix it from there.

**Comment by DePierre** [comment]
@DoomTaper from @7a 

> aux plugins are intended to help with smaller more targetted tasks, think of them as a "sniper" approach instead of the general "cavalry and artillery" approach in OWTF. aux plugins are an attempt to provide OWTF msfcli-like functionality to OWTF, where you can build a plugin that helps with some security task. For this reason, aux plugins can be "to launch SET against email targets" or "to launch a bunch of metasploit DoS modules for testing DoS" or to "bruteforce xyz", can be anything and the concept of "target" is also completely different for aux plugins. the target of an aux plugin can range from a person, to a network service, or a url
