### ISSUE TITLE
Error 301 on fetching updates

### ISSUE THREAD

**Issue by RahulPratapSingh** [owtf/owtf#603]
During the installation phase of OWTF, it's fetching updates from following links which results in error with 301 response code.

301 error getting http://drupalcode.org/viewvc/drupal/contributions/modules/drupal_plugins.txt
301 error getting http://drupalcode.org/viewvc/drupal/contributions/themes/drupal_themes.txt

**Comment by delta24** [comment]
Duplicate #119
