### ISSUE TITLE
UI Add Targets button bug

### ISSUE THREAD

**Issue by RahulPratapSingh** [owtf/owtf#605]
Add Targets button get disabled even if the url is not valid.
![screenshot from 2016-03-17 12-18-13](https://cloud.githubusercontent.com/assets/8836104/13843945/b1a8d40a-ec5c-11e5-9c4a-d2bfe66863f0.png)

**Comment by DoomTaper** [comment]
@RahulPratapSingh are you on develop branch ?
Seems similar to issue #496

**Comment by RahulPratapSingh** [comment]
@DoomTaper yes. I am on develop branch. This bug seems similar to bug #496. I checked that now, but this issue isn't addressed in code. Even, to replicate no need to put any special character, just leave it blank and hit Add Targets!. It will get disabled and will remain same, until user refresh the page or do any other activity. It's seems to be annoying to user to refresh page everytime.

**Comment by sachinkamath** [comment]
@RahulPratapSingh I am not able to reproduce it. It works as intended.

Typed an Invalid URL first, also tried by leaving it blank : 
![1](https://cloud.githubusercontent.com/assets/9546091/13851057/a4abbb48-ec82-11e5-9c53-89a075d1a1ea.png)


Used a legit URL (https://www.google.com) and clicked again : 

![2](https://cloud.githubusercontent.com/assets/9546091/13851062/a9f177fa-ec82-11e5-801a-ecb406a85148.png)

**Comment by RahulPratapSingh** [comment]
@sachinkamath My bad. I checked it again before posting, but still compared with old (master branch code). I will make sure, this blunders won't happen again. :(
