### ISSUE TITLE
Verify distribution during installation

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#607]
I was trying to install OWTF onto an Ubuntu VM today and I *accidentally* chose Kali as my distribution.  The installation went fine and I was able to fire up the web UI just fine. But as expected, there were a lot of errors when I tested it by scanning a website like this as nikto was not installed : 

![screenshot from 2016-03-17 21-18-43](https://cloud.githubusercontent.com/assets/9546091/13851905/f2355aa6-ec85-11e5-9ded-9a08c8bdaf38.png)

Some of the things that can be done to resolve this : 
* Instead of prompting user's to select their distribution, dynamically detect it using `lsb_release -a`
* Verify if the dependencies are installed before firing up OWTF (or) add a button in the WebGUI to verify the dependencies.

**Comment by delta24** [comment]
We already detect the distribution automatically and the dependencies. @sachinkamath see the `install.py` and the `dependency_management` dir.

**Comment by sachinkamath** [comment]
@delta24 Gotcha. I had discussed about this on IRC with @7a . We concluded that auto-detection of the OS will help. I'll send a PR soon for that :)
