### ISSUE TITLE
Unexpected Behavior after deleting a session

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#608]
#### Steps to Reproduce : 

1) Navigate to Targets, click on Sessions and add a New Session, say `Test Session`.

![screenshot from 2016-03-17 23-04-50](https://cloud.githubusercontent.com/assets/9546091/13855226/4e871718-ec95-11e5-8e68-bbb68c1e76da.png)
<hr>
2) Select `Test session` as the session and then delete it, Click outside the popup to close it.

![screenshot from 2016-03-17 23-05-51](https://cloud.githubusercontent.com/assets/9546091/13855247/73e5e976-ec95-11e5-86dc-52cb50a434dd.png)
<hr>

3) Notice that Test Session is still selected as the session. Try adding a Target URL. You'll be greeted with an error.

![screenshot from 2016-03-17 23-06-26](https://cloud.githubusercontent.com/assets/9546091/13855255/7bb5403e-ec95-11e5-9a05-1fb0397ad24f.png)
<hr>

#### What's happening?####

As far as I understood, the `delete` method in `OWTFSessionHandler` deletes the session from the `db` but doesn't set it to the default value after deletion.

Snippet from api_handlers.py : 
```python 
def delete(self, session_id=None, action=None):
        if session_id is None or \
           action is not None:
            raise tornado.web.HTTPError(400)
        try:
            self.get_component("session_db").delete_session(
                int(session_id))
        except exceptions.InvalidSessionReference:
            raise tornado.web.HTTPError(400)
```

**Comment by delta24** [comment]
@sachinkam I am not sure if it is a bug. This action is intended IMO. Consider this:

- You have multiple sessions registered.
- You delete one of them
- You are expected to select another from the same modal window from which you deleted the session.
 Restoring the default session every time I delete a session is not good. Instead you can have this behaviour:

- If you have only 2 sessions registered, and you delete one of them -> then select the other one as the default one.

Do you get my point?

**Comment by sachinkamath** [comment]
@delta24 Got it. As discussed in IRC, it'd be better to force the user to select a session after deletion of a session by tweaking the templates. Closing #625
