### ISSUE TITLE
File Redundancy

### ISSUE THREAD

**Issue by RahulPratapSingh** [owtf/owtf#609]
There is file redundancy in tools directory. 

https://github.com/owtf/owtf/blob/develop/tools/discovery/web/rev_proxy/HTTP-Traceroute.py
https://github.com/owtf/owtf/blob/develop/tools/discovery/web/traceroute/HTTP-Traceroute.py

Both the files i.e HTTP-Traceroute.py are same.

**Comment by delta24** [comment]
Remove any one of them @7a ? But make sure not to break any plugins in the process.

**Comment by RahulPratapSingh** [comment]
@delta I checked it. According to my observation, HTTP-Traceroute.py in traceroute directory is not used anywhere in the code. Please correct, if I am wrong.

**Comment by delta24** [comment]
Yes @RahulPratapSingh, the HTTP-Traceroute.py in traceroute directory is not used - send a PR removing it! :+1:

**Comment by RahulPratapSingh** [comment]
@delta24 done :)
