### ISSUE TITLE
Check for tools before running commands

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#632]
It'd be better to check if a tool exists before running the actual plugin. This will be significantly reduce the run-time in distributions that are not pen-testing oriented. For example, Ubuntu does not have arachni pre-installed but arachni scans seem to run during analysis resulting in errors.

## Expected Behavior

OWTF should report that the tool is missing and the test will be skipped.
## Current Behavior

OWTF runs the command and returns an error message : 
![screenshot from 2016-03-25 07-20-48](https://cloud.githubusercontent.com/assets/9546091/14036029/075ac63e-f25b-11e5-9ab2-c2faca5756e6.png)

## Possible Solution

Check for installation before scanning.

## Steps to Reproduce (for bugs)

1. Run OWTF without certain tools installed.
2. Add target
3. Notice that the tests are done assuming all tools are installed. ( Takes up unnecessary time)

## Your Environment

* Installation method used: Manual
* Version/branch used: develop 
* Operating System and version (like Kali, Debian, ArchLinux, etc): Ubuntu 15.10
* pip/setuptools version: pip-8.1.1
* sudo access: Yes

**Comment by delta24** [comment]
@sachinkamath I don't think it will reduce the time. If a tool is not found, it will result in an error, and OWTF directly skips that plugin. 

The install script installs some required tools in Debian (read Ubuntu) and if they are still not installed, OWTF prints out a warning to continue the start process (if some tools are not found):
see `framework/config/health_check.py`.

**Comment by sachinkamath** [comment]
@delta24 I did not get any such warning/error message. Strange.

**Comment by delta24** [comment]
@sachinkamath By skipping the test I meant that OWTF will assign a "Failed" status to the work and move on (because the command will fail to run and return some empty object)
