### ISSUE TITLE
Session Modal breaks for large session names

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#635]
`SessionModal` handles the sessions in `/ui/targets` . When a large string is passed as session name, it stretches beyond the size of modal window and breaks the delete functionality
## Expected Behavior

The session name should have been truncated.
## Current Behavior 

The Session Name overflows out of bounds causing delete button to disappear
## Possible Solution

* Truncate the session name / Set a limit (Better Fix)
(or)
* Increase the modal size

## Steps to Reproduce (for bugs)

1. Open the Sessions and get the Modal popup.
2. Enter a long string.

![screenshot from 2016-03-26 11 40 57](https://cloud.githubusercontent.com/assets/9546091/14058477/09f6e632-f2f8-11e5-8b89-fa8d5fb46f6f.png)

## Your Environment

* Installation method used: Manual
* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): Kali Linux
* pip/setuptools version: 8.1.1
* sudo access: Yes

**Comment by delta24** [comment]
@sachinkamath @DePierre @tunnelshade @7a: I think better to truncate the session names to max. 50 chars.

**Comment by tunnelshade** [comment]
@delta24 Yes, put a limit on it. 50 characters make sense

**Comment by delta24** [comment]
@tunnelshade should we also start implementing length limits in the sqlalchemy models itself?

**Comment by tunnelshade** [comment]
Yes @delta24 . Then catch for exceptions while creating models.

**Comment by delta24** [comment]
Closed in https://github.com/owtf/owtf/commit/d9a2cf39cf96f792adc8c9558953931a01361b72.
