### ISSUE TITLE
OWTF takes few steps to start

### ISSUE THREAD

**Issue by RahulPratapSingh** [owtf/owtf#638]
Everytime, I restart my VM, it takes few steps to start OWTF like changing directory, go to scripts and then run scripts. It's a kind of little lengthy process, and tiredsome.

## Expected Behavior

It should start in 1 or 2 steps without much efforts of end user.

## Current Behavior

Takes multiple steps to start, after VM restart.

## Possible Solution

Little changes in the codebase results in the following output.
![screenshot from 2016-03-27 00 08 15](https://cloud.githubusercontent.com/assets/8836104/14061817/59ba7874-f3b0-11e5-8e2b-3fd7f1665579.png)

## Steps to Reproduce (for bugs)

1. Restart VM with kali installed in it.
2. Start OWTF

![screenshot from 2016-03-26 23 53 23](https://cloud.githubusercontent.com/assets/8836104/14061828/93d873a8-f3b0-11e5-912a-38610051018e.png)

## Your Environment

* Installation method used: Automatic
* Version/branch used: Develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): Tested in kali Linux & Parrot OS
* pip/setuptools version: 8.1.1
* sudo access: Yes

**Comment by sachinkamath** [comment]
This is something to be taken care at the system level IMO. OWTF is already slow w.ref to the start time as mentioned in #387. Adding a script to check pg status will only increase the loadtime of `owtf.py`

**Comment by RahulPratapSingh** [comment]
I haven't added any new script to check for pg status. It's already checked by OWTF at the starting. Just added few lines of code there. So, I don't think, it will significantly increase loadtime.

**Comment by delta24** [comment]
How does the possible fix you mention fix the problem?
> Everytime, I restart my VM, it takes few steps to start OWTF like changing directory, go to scripts and then run scripts. It's a kind of little lengthy process, and tiredsome.

**Comment by RahulPratapSingh** [comment]
@delta24 I just called both the files i.e start_postgres.sh and db_run.sh as required to start services. These are called when the current exception handling ask user to manually start service in files db_run.sh and db.py respectively.

<pre><code>  File: db_run.sh Line: 87
      
  if [ "$status_exitcode" != "0" ]; then
            # echo "[+] Starting failed because postgreSQL service is not available!"
            # echo "[+] Run # sh scripts/start_postgres.sh and rerun this script"
            bash scripts/start_postgres.sh
            echo "[+] All services started. Restart ./owtf.py"			
            exit 1 </code></pre>

<pre><code>  File: db.py Line: 159
             
              except:
                      try:
                            call("scripts/db_run.sh")
                      except KeyboardInterrupt:
                            print "\n[+] OWTF is aborted by the user"</code></pre>

**Comment by DePierre** [comment]
@RahulPratapSingh So basically, the extra step is that postgresql is not starting when your VM is booting?

If that is the case, then simply add it to your startup configuration, using systemctl for instance:
```bash
sudo systemctl enable postgresql.service
```

Then, you don't need to run ``db_run.sh`` but only ``owtf.py``.

IMO, OWTF should not start postgresql on startup but let the user configure his system.

@sachinkamath I don't think that it would be a problem of efficiency if we forced OWTF to run postgresql server if not started. However, I don't believe that it should be doing that and instead let the user deal with his services/daemons configuration.

@delta24 Thought?

**Comment by delta24** [comment]
@DePierre Same. OWTF should not concern with the system configuration.
