### ISSUE TITLE
Dirbuster Plugin not working

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#642]
There are two chained commands when running dirbuster plugin Old Backup And Unreferenced Files (web/active) which should run in the order it's given (see the order [here](https://github.com/owtf/owtf/blob/develop/plugins/web/active/Old_Backup_and_Unreferenced_Files%40OWTF-CM-006.py#L15)) but its not happening that way. look at the screenshot below
![screenshot 80](https://cloud.githubusercontent.com/assets/10975138/14078230/a37fdbc2-f511-11e5-9c22-926430e62943.png)

## Expected Behavior

2nd command should run before the first command ideally. (referring the screenshot )

## Current Behavior

first command is running before 2nd command.

## Possible Solution

Need some improvement in L[#69](https://github.com/owtf/owtf/blob/develop/framework/db/resource_manager.py#L69) 

## Steps to Reproduce (for bugs)

Just run the dirbuster plugin Old Backup And Unreferenced Files (web/active)

## Context

User will be able to run Dirbuster plugin

## Your Environment

* Installation method used: automatic
* Version/branch used:develop
* Operating System and version (like Kali, Debian, ArchLinux, etc):kali
* sudo access: yes

**Comment by delta24** [comment]
@DoomTaper this is not the case. Sometimes the plugin order is jumbled (random) where the grep plugins run before the semi-passive or active plugins have run + try running a full scan with all plugins (web test). You will see that the active/semi-passive plugins run before the passive+external plugins - which is wrong. This file, `profiles/web_plugin_order/default.cfg`, was earlier meant for this, but it is not used now.

Also happens with Nikto: 

```
[-] __________ 5 - Target: http://www.webscantest.com -> Plugin: Nikto Unauthenticated (web/active) __________
[-] 
[-] Executing :

cd owtf_review/targets/http__www.webscantest.com/partial/Nikto_Unauthenticated/active; /root/owtf/scripts/extract_urls.sh nikto Nikto.txt http://www.webscantest.com


[-] 
[-] ------> Execution Start Date/Time: 29/01/2016-22:27
[-] 
[*] File not found: Nikto.txt
[-] Time=0s,  19ms
[-] Spider/URL scaper time=0s, 127ms
[-] 
[-] Executing :

cd owtf_review/targets/http__www.webscantest.com/partial/Nikto_Unauthenticated/active; /root/owtf/scripts/run_nikto.sh /usr/share/nikto 69.164.223.208 127.0.0.1:8008 80 www.webscantest.com


[-] 
[-] ------> Execution Start Date/Time: 29/01/2016-22:27
[-] 
[*] /usr/share/nikto
[*] [*] Running: nikto  -evasion 1  -config /tmp/temp_owtf.21241.nikto.conf -host www.webscantest.com -port 80 -output /root/owtf/owtf_review/targets/http__www.webscantest.com/partial/Nikto_Unauthenticated/active/nikto2016-01-29_22_27_09.xml -Format xml
[*] - Nikto v2.1.6
[*] ---------------------------------------------------------------------------
[*] + Target IP:          69.164.223.208
[*] + Target Hostname:    www.webscantest.com
```

Duplicate https://github.com/owtf/owtf/issues/204

**Comment by DoomTaper** [comment]
@delta24 
1. I don't think this is similar to issue 204 because that issue is related between running different plugins while this issue is related between running different commands of a single plugin
2. Regarding nikto plugin this is different because in nikto plugin  a single argument `nikto_unauth` (plugin [here](https://github.com/owtf/owtf/blob/develop/plugins/web/active/Nikto_Unauthenticated%40OWTF-WVS-002.py#L15)) is causing two commands to run in which jumbling is occurring (or maybe not) ( see two commands at line [184](https://github.com/owtf/owtf/blob/develop/profiles/resources/default.cfg#L184) and line 185 ( just below it)).
3. This issue can be resolved by editing the dirbuster plugin as shown [here](http://pastebin.com/r1cAA1bi). I have tested this and works fine!
