### ISSUE TITLE
Bug in progress bar

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#644]
The major problem lies in the [formula](https://github.com/owtf/owtf/blob/develop/framework/interface/templates/manager_interface.html#L180) of calculating the percentage of completed work i.e. `complete_count / (left_count + complete_count)`
There are **two bugs** related to progress bar.
#### First bug
1. run `./scripts/db_setup.sh clean` and then `./scripts/db_setup.sh init` to ensure your db is clean.
2. Now add a target and run a single plugin against it. Now according to formula while the plugin is running `left_count=0` because work has been taken and `complete_count=0` because work is not finished yet. So in the formula `complete_count / (left_count + complete_count)` it will be 0/0 which is an error although it will not showup anywhere and that's why progress bar doesn't work (don't think progress bar was working for not showing any work , read my next bug to get clear about this).

#### Second bug
1. make sure you have successfully run a plugin so that `complete_count != 0` now run a **single plugin** against a target ( try to select a plugin which takes time like i tested for arachni_unauth web/active ). 
2. Go to the worklist page and you will see that progress bar is showing 100% completion even if plugin is running (see the terminal) because in this case `left_count = 0` (because work has been taken) so the formula `complete_count / (left_count + complete_count) ` becomes 1 ( remember `complete_count != 0`) but if `complete_count = 0` as in previous case rather than showing 100% progress bar will not work instead.

**P.S.**: Sorry to the collaborators for not following the template but this was not fitting into it :P

**Comment by saganshul** [comment]
@DoomTaper I will try to fix it today as soon as possible. Thank you for pointing it out :)

**Comment by delta24** [comment]
@saganshul Also change the progress bar title to something like "Total scan progress" or something like that :)

**Comment by DoomTaper** [comment]
@saganshul One more issue I have noticed
your method of computing `complete_count` is incorrect because
e.g. 
1. First run atleast 5 plugins successfully to clearly see this issue. This will make `complete_count = 5`
2. After all work has been done run 2 more plugins ( remember these 2 shouldn't be run along with above 5 ) now see the workers page since one work has been taken so `left_count = 1`. Now, Instead of showing 0% (because ideally `complete_count =0`) it will have some value ( = 5 / (5+1) * 100 % ).

@saganshul Try to make `complete_count` more dynamic.

**Comment by saganshul** [comment]
@DoomTaper  I knew about this when I was writing this functionality. But presently we do not have a space where I can find out completed task except plugin_outpout model correct me if I am wrong which gives me total completed task that's why you are getting 5. Specifically what we can do right now, we can filter it by date or time but still we can't have exact completed task because filtering it by start_time or end_time will not give much accuracy because 2 scans can be on a same day or at same time.
Give me some suggestions on how I can have exact completed tasks?

**Comment by DoomTaper** [comment]
@delta24 you should reopen this issue as there is still one issue which needs to be fixed. See my last [comment](https://github.com/owtf/owtf/issues/644#issuecomment-204322581) . @delta24 @DePierre  Should I open that as a new issue or edit the existing one so that it is noticeable ?
