### ISSUE TITLE
Fix run_tlssled.sh permission

### ISSUE THREAD

**Issue by pauTE** [owtf/owtf#645]
I executed the active Testing for SSL-TLS  OWTF-CM-001 and everything looked fine.But when I looked at the reports I discovered that the scripts/ssl/run_tlssled.sh script has no execution permission.

## Expected Behavior

The execution of the active Testing for SSL-TLS  OWTF-CM-001 should generate various reports, one of them must be report generated by the run_tlssled.sh script.To solve that executing the script with sh (adding sh to the test command in /profiles/resources/default.cfg is a good option.

## Current Behavior

The script has no execution permission and I'm getting  a permission denied.So the reports is not being generated.

![permission](https://cloud.githubusercontent.com/assets/11819820/14184363/ca220b5a-f742-11e5-8f62-9eaab2ceafd4.png)

## Possible Solution

To solve that executing the script with sh (adding sh to the test command in /profiles/resources/default.cfg is a good option.

## Steps to Reproduce (for bugs)

1.Execute active Testing for SSL-TLS  OWTF-CM-001 
2.Watch the reports

**Comment by delta24** [comment]
@pauTE ?

**Comment by pauTE** [comment]
I cannot remember.But I probably changed the permissions.However I think it's worth adding the 'sh' in case the user changed the permissions.

**Comment by delta24** [comment]
@pauTE You're right. Send a PR which applies this to all other scripts (meanwhile I'm closing the issue and the PR ;) )
