### ISSUE TITLE
Migrate to a cross-platform method to download files instead of using wget

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#658]
Currently, we are using the wget command to pull various files from the Internet during installation. The idea is to python-ify these and use python-wget instead. 

## Expected Behavior

Currently, OWTF uses `os.system( )` command to invoke wget commands. It'd be better to use the wget package in PyPI instead. This'd make the installation less dependent on external packages. Also, as mentioned [here](https://github.com/owtf/owtf/issues/448#issuecomment-207358972), Windows support for wget is not so great. It'd be better to move to python-wget for flexibility. 

## Context

If not implemented, we might face difficulties while porting OWTF to Windows.  

## Your Environment

* Installation method used: Manual
* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): Multi
* pip/setuptools version: 8.*
* sudo access: Yes

**Comment by delta24** [comment]
@sachinkamath Instead of porting OWTF to Windows completely, IMO it is better to use Docker to do that. This makes more time available for us to improve OWTF and not worry about support (distros, installation, etc.).
