### ISSUE TITLE
PostgreSQL Fix in db_setup.sh out-dated?

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#667]
Hi fellows,

I am creating this issue to ask a simple question regarding the script ``db_setup.sh``.
Is the fix https://github.com/owtf/owtf/blob/develop/scripts/db_setup.sh#L33 still necessary? Should we remove it? Or comment it?

Personally, it has two problems for me:
+ It doesn't work on my setup (archlinux):
```bash
$ ./scripts/db_setup.sh init 

------------------------- OWTF Database Helper Script -------------------------
                    Helps in creation of user and database                     
-------------------------------------------------------------------------------

[+] Ensure that you have required values in /root/.owtf/db.cfg

Press Enter to continue

CREATE ROLE
CREATE DATABASE
Having SSL=true in postgres config causes many errors (psycopg2 problem)
Remove SSL=true from the PostgreSQL config?[Y/n]y
sed: can't read /etc/postgresql/9.5/main/postgresql.conf: No such file or directory
Restarting the postgresql service
```
+ It prevents automation when running the functional test suites.

I could theoretically work-around the second problem, by using something like ``echo '\n' | ./script/db_setup.sh init``. But before doing that, I simply wanted to know if that script was still useful?

If not, we should consider removing it.

**Comment by DePierre** [comment]
Nevermind. I just got this error message on Travis build:
```pytb
OperationalError: (psycopg2.OperationalError) SSL error: decryption failed or bad record mac

 [SQL: 'SELECT configuration.key AS configuration_key, configuration.value AS configuration_value, configuration.section AS configuration_section, configuration.descrip AS configuration_descrip, configuration.dirty AS configuration_dirty \nFROM configuration \nWHERE configuration.key = %(param_1)s'] [parameters: {'param_1': 'MIN_RAM_NEEDED'}]
```

I believe that this is the problem the postgresql fix is addressing, right?

**Comment by delta24** [comment]
Yes.
