### ISSUE TITLE
Deleting the target in between hangs the corresponding worker

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#675]
## Expected Behavior

If a target is deleted in between then worker working on the target after running the plugin should get free.

## Current Behavior

If a target is deleted in between then the corresponding worker hangs while writing to db and shows below error which is obvious
`InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.IntegrityError) insert or update on table "command_register" violates foreign key constraint "command_register_target_id_fkey"
DETAIL:  Key (target_id)=(19) is not present in table "targets".
 [SQL: 'INSERT INTO command_register (start_time, end_time, success, target_id, plugin_key, modified_command, original_command) VALUES (%(start_time)s, %(end_time)s, %(success)s, %(target_id)s, %(plugin_key)s, %(modified_command)s, %(original_command)s)'] [parameters: {'original_command': u'/usr/bin/dnsrecon --type std,rvl,goo -d example.com -r 87.240.143.241-87.240.143.241', 'success': True, 'start_time': datetime.datetime(2016, 4, 21, 17, 10, 51, 917088), 'target_id': 19, 'modified_command': u'cd owtf_review/targets/http__example.com/partial/Application_Discovery/active; /usr/bin/dnsrecon --type std,rvl,goo -d example.com -r 87.240.143.241-87.240.143.241', 'end_time': datetime.datetime(2016, 4, 21, 17, 11, 11, 928419), 'plugin_key': u'active@OWTF-IG-005'}]`

I tried to delete that worker, refresh the page but didn't work
Then I tried "add worker" which replace that worker with a different PID and add a new worker

## Possible Solution

catching the appropriate exception may work.

## Steps to Reproduce (for bugs)

1. Select a target and run some plugins
2. Now delete the target
3. You will see that worklist is empty and worker is working. Now as the plugin ran and tried to write to db the above error is displayed on terminal.

## Your Environment

* Installation method used: automatic
* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): kali
* pip/setuptools version: 8.0.2
* sudo access: yes

**Comment by delta24** [comment]
@DoomTaper I cannot reproduce this on the latest develop checkout - can you verify?

**Comment by DoomTaper** [comment]
Yes! I am able to reproduce it and ideally it should be, as target has been deleted hence there is no target id in the database, so while db.commit() error should occur. @delta24 ?
![screenshot 100](https://cloud.githubusercontent.com/assets/10975138/16044618/ccecedd6-3262-11e6-9e61-b5dabb830498.png)

**Comment by DarKnight24** [comment]
I am able to reproduce it. @delta24 @DoomTaper

**Comment by delta24** [comment]
@DoomTaper @DarKnight24 @DePierre so the fix should be to delete all workers (for that target), remove work related from the worklist, and then delete the `target_obj` from the DB?

**Comment by DoomTaper** [comment]
@delta24 right now related work is already removed from the worklist, I'm not sure about target_obj in DB if it is deleted or not.

**Comment by DarKnight24** [comment]
@DoomTaper @delta24 @DePierre @7a Yesterday I have looked over the issue and found that after the execution the process is found in zombie state. Hence sending a kill signal on it had no effect.
