### ISSUE TITLE
New active plugin for JBoss Vulnerability Assessment

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#677]
Right now, we do not have any plugin to actively probe for JBoss instances and it'd be great to integrate one such tool as an active plugin into OWTF
## Possible Solution

[jexboss](https://github.com/joaomatosf/jexboss) looks promising. It is built for python 2.7.\* and has very less dependencies. [More Information](https://github.com/joaomatosf/jexboss/blob/master/README.md)
## Context

By implementing this, OWTF will be able to assess vulnerabilities in JBoss applications as well.  
## Your Environment

- Installation method used: Manual
- Version/branch used: develop
- Operating System and version (like Kali, Debian, ArchLinux, etc): Kali Linux
- pip/setuptools version: 8.0.2
- sudo access: Root :)

**Comment by 7a** [comment]
nice!
Ideally, ptp should be extended to automatically rank this as well, so that if something bad is found this is more visible to the tester reviewing the report! :D

**Comment by viyatb** [comment]
Moved to https://github.com/owtf/community-plugins/issues/5.
