### ISSUE TITLE
Improvements to existing fingerprinting plugin

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#678]
Unfortunately, httpprint and other tools are generally not that great to detect what is running on the server. For example, we do not have JBoss, Tomcat, ColdFusion, etc. detection in OWTF right now. 
## Possible Solution

[clusterd](https://github.com/hatRiot/clusterd) should be added to the existing fingerprinting plugin to add variety and improve detection. I suggest that we don't limit the detection to JBoss and also extend it to actively probe for ColdFusion, Tomcat, etc.
## Context

This will greatly improve the scope of OWTF and enhance the fingerprinting process
## Your Environment

- Installation method used: Manual
- Version/branch used: develop
- Operating System and version (like Kali, Debian, ArchLinux, etc): Kali
- pip/setuptools version: 8.0.2
- sudo access: Root :)

**Comment by 7a** [comment]
+1!

**Comment by viyatb** [comment]
Moved to https://github.com/owtf/community-plugins/issues/6.
