### ISSUE TITLE
OWTF not running on Fresh install of Kali 2.0 64 bit

### ISSUE THREAD

**Issue by bigduke1092** [owtf/owtf#688]
Running ./owtf.py from the owtf directory and this is the error I am getting

Traceback (most recent call last):
  File "./owtf.py", line 14, in <module>
    verify_dependencies(os.path.dirname(os.path.abspath(sys.argv[0])) or '.')
  File "/root/owtf/framework/dependency_check.py", line 40, in verify_dependencies
    owtf_libraries = [req.req.project_name for req in owtf_reqs]
AttributeError: 'Requirement' object has no attribute 'project_name'

I am running it out of VMware Fusion.

**Comment by delta24** [comment]
Duplicate #686 - this is due to `pip` error. For an immediate fix, please downgrade your `pip` version to 8.0.x.

**Comment by bigduke1092** [comment]
Thanks I will give that a shot!

**Comment by delta24** [comment]
Closed in 2d648e1
