### ISSUE TITLE
[webui] Redesign the web interface

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#695]
This is just the placeholder issue for web interface redesign.

> X-reboot issue: https://github.com/owtf/reboot/issues/18
- Reduce clicks and have a more natural flow ⇒ This refers to the fact that the current interface is not user-friendly, and can be modified to increase productivity while reducing redundancies and improving consistency.
- The main OWTF report uses elements known as accordions to represent findings of the plugins. The accordion element is not scalable: it is not a user-friendly technique to represent hundreds of rows of plugins.

The goal here is to come up with an interface that is user-friendly, scalable, and maintainable.
- CSS standards: Currently OWTF uses a heavy-CSS framework, Twitter Bootstrap to render elements. Twitter Bootstrap includes many unnecessary elements and is so heavy-handed, so prescriptive, that it is actually a nuisance to modify. It’s easier to use the defaults.
- Also write everything in SASS (Syntactically Awesome Stylesheets), reducing redundancy and development time.and increasing consistency. SASS is very easy to write and is a more maintainable alternative.
- Use compass (SASS -> CSS compiler) to compile everything (concatenate) the stylesheets and minify them whenever regenerating.

**Comment by delta24** [comment]
> Shifted here because it is a subset of the main issue.

At the moment you need 3 clicks + 1 nasty horizontal mouse move from left to right to rank ANY plugin.
We need to:
- Put the plugins somehow into the plugin group banners (-1 click)
- you know the plugins that have been run under that test, we could abbreviate with [ E P S A ] ← External, Passive, Semi-Passive, Active :)
- Put the buttons to click on the plugins [ E P S A ] directly ABOVE the ranking buttons (decreased horizontal mouse trip)
- [ ] Optimise UI of the report
- [ ] ZAP/Burp like transaction log viewer
- [ ] Replace accordions to something more easier to navigate

**Comment by viyatb** [comment]
@saganshul there are a couple of bugs in the new interface:

- [ ] The filters do not work.
- [ ] The proxy transactions should ideally be colored when "selected" => highlight the row.
- [ ] The transactions view does not have pagination.
- [ ] Browse files do not give the correct path from the file server (assigned to me).

**Comment by saganshul** [comment]
@viyatb In first point, which filters are you talking about?

**Comment by viyatb** [comment]
@saganshul the advanced filters in the report.

**Comment by saganshul** [comment]
@viyatb I checked advance filters are working correctly. Can you please specifically tell me which filter is not working?

**Comment by saganshul** [comment]
@viyatb Also in sorting thing, on which basis should I sort?
We don't have pagination here because table contains all the transactions.

**Comment by viyatb** [comment]
@saganshul 
re sorting: Time
re Pagination: I think if we have lots of transactions, it would be better to have pagination like in the old UI.

re Advance filters: Let me confirm it again ;)

**Comment by viyatb** [comment]
Here are some of the things left to do in this issue:
 
- [ ] Design and refine page layouts (like replacing accordions to something more easier to navigate)
- [ ] New react components, and better styling (SCSS)
- [ ] tests (unit, functional)

**Comment by viyatb** [comment]
Closing this meta issue in favor of smaller feature requests in the web interface.
