### ISSUE TITLE
Issue with metasploit pro location

### ISSUE THREAD

**Issue by Kaicastledine** [owtf/owtf#707]
## Expected Behavior
Plugin is meant to run with the use of metasploit 

## Current Behavior
When using any metasploit plugins they fail.
Metasploit pro is installed on the machine so edited the tool location to the following.
![image](https://cloud.githubusercontent.com/assets/11678433/15898767/64c22ba2-2d91-11e6-8f47-1377211cc3a9.png)->
PTF (Pentesting framework) has been used on the machine for most but not all apps it manages. This means the default location for tools are incorrect.
Some tools have been changed their location and work fine.

The error is as bellow
![image](https://cloud.githubusercontent.com/assets/11678433/15898864/bf2dcd26-2d91-11e6-851f-50c78339673a.png)

I have installed Rake and the version specified but the issue still persists.

## Possible Solution
Potential way to read current app links to find true location of already installed app ?
Or resolve the metasploit issue.

## Steps to Reproduce (for bugs)
1. Ran MS SQL probing plugin that uses metasploit
2.Error cannot find MSFCONSOLE
3.Changed location to metasploit pro's MSFCONSOLE
4.Error produced as shown in images above

## Your Environment
* Installation method used: Fresh install using the bootstrap method
* Version/branch used: - 1.0.1 Release LionHeart Beta
* Operating System and version (like Kali, Debian, ArchLinux, etc): KALI
* pip/setuptools version:
* sudo access: running as root

**Comment by Kaicastledine** [comment]
Let me know if you want to logs also, Have a feeling this might be a simple issue to resolve.

**Comment by delta24** [comment]
Hi @Kaicastledine, we have a new release which fixes the path issues. You can download it here  -
https://github.com/owtf/owtf/releases/tag/v2.0a or pull the latest changes: `git pull https://github.com/owtf/owtf.git`.

**Comment by Kaicastledine** [comment]
Ah I thought it was an old version. How come the bootstrap has not installed it ?

Or are the versions completely separate ?

**Comment by Kaicastledine** [comment]
I've just checked the the new version 2 is downloaded in the OWTF folder however whenever its used it reports it as the old version. Will remove the current version and use the Git Pull and let you know if that works.

Many thanks

**Comment by delta24** [comment]
Better clone in a new directory. :)

**Comment by Kaicastledine** [comment]
Already running kali 2
Msf console was removed to fix some issues between the metasploit pro install as the 2 different install locations of msf console was causing issues.

**Comment by Kaicastledine** [comment]
Just cloned the new version and I get this error on start 
![image](https://cloud.githubusercontent.com/assets/11678433/15901157/0f4c0824-2d9a-11e6-93ab-d4f4ba4990b1.png)

**Comment by delta24** [comment]
@Kaicastledine which plugin are you are trying to run?

**Comment by delta24** [comment]
@Kaicastledine does the above fix work for you?

**Comment by Kaicastledine** [comment]
Metasploit pro install in the highlighted text on the first image which is 
/opt/Metasploit 
I have changed the location and that error was produced instead of it not being able to find the application.

I will run new tests and post them results in shortly.

**Comment by delta24** [comment]
@Kaicastledine Did you get it working?
