### ISSUE TITLE
OWTF Start up issue

### ISSUE THREAD

**Issue by robin-williams** [owtf/owtf#712]
## Expected Behavior
When running the ./owtf.py command to start OWTF it fails.

## Current Behavior
This error is returned: 
```

ERROR:root:Aborted by Framework: [DB] (psycopg2.OperationalError) could not open file "base/66585/2604": No such file or directory
 [SQL: '\nCREATE TABLE errors (\n\tid SERIAL NOT NULL, \n\towtf_message VARCHAR, \n\ttraceback VARCHAR, \n\tuser_message VARCHAR, \n\treported BOOLEAN, \n\tPRIMARY KEY (id)\n)\n\n']
Run scripts/db_run.sh to start/setup db
```

Now, I did run the scripts/db_run.sh like it suggested but the same error reappears. 

## Your Environment

I used the git clone method to install OWTF. I am running the most current Kali 2.0 rolling version. (I updated it this morning). The install went smooth just ran into this error when starting OWTF.

**Comment by robin-williams** [comment]
Also getting this when running ./db_setup.sh clean

`------------------------- OWTF Database Helper Script -------------------------
                    Helps in creation of user and database                     
-------------------------------------------------------------------------------

[+] Ensure that you have required values in /root/.owtf/db.cfg

Press Enter to continue

ERROR:  could not open file "global/2964": No such file or directory
ERROR:  role "owtf_db_user" cannot be dropped because some objects depend on it
DETAIL:  owner of database owtfdb
1 object in database owtfdb
`

**Comment by delta24** [comment]
@robin-williams Few things:

- Did you run the `db_run.sh` script as root?
- The error looks like postgresql error: make sure it is a fresh image + your postgresql setup is corrupt
  You should re-initialize postgresql  - `sudo -U pgsql initdb`

**Comment by robin-williams** [comment]
The issue was with the PostgreSQL DB (more than likely my fault). I nuked it completely and re-installed, ran through the OWTF db scripts and it works like a charm now. Thanks!

**Comment by lianfeng30** [comment]
python2 -m owtf

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org

[-] Loading config from: /Users/x/.owtf/conf/framework.cfg..
ERROR:root:Aborted by Framework: [DB] (psycopg2.OperationalError) FATAL:  role "owtf_db_user" does not exist

Run 'make db-run' to start/setup db
