### ISSUE TITLE
Install from git on Kali Rolling fails to start

### ISSUE THREAD

**Issue by Graph-X** [owtf/owtf#720]
Install completes successfully without errors, but unable to start.  Errors out with missing Markdown PyOpenSSL and SQLAlchemy.

## Expected Behavior
Since the "missing" libraries are actually installed, owtf should start without dependency issues.

## Current Behavior
```
root@DaddyWarb0x:/opt/owtf# ./owtf.py 
The following python libraries seem missing : 
	Markdown,pyOpenSSL,SQLAlchemy

Haven't you run the install script? 
	python2 install/install.py

If you are sure you ran the install script, install the missing libraries seperately
	pip install --upgrade -r install/owtf.pip
```

```
root@DaddyWarb0x:/opt/owtf# pip list | grep -i 'markdown\|pyopenssl\|sqlalchemy'
Markdown (2.6.6)
pyOpenSSL (16.0.0)
SQLAlchemy (1.0.14)
```
```
>>> for i in pip.get_installed_distributions():
...     print(i.project_name, i.version)
... 
('cookies', '2.2.1')
('sortedcontainers', '1.5.3')
('selenium', '2.53.6')
('guess-language', '0.2')
('pycparser', '2.14')
('tornado', '4.3')
('vivisect-vstruct-wb', '1.0.3')
('setuptools', '25.2.0')
('keepalive', '0.5')
('python-pyqt5-vstructui', '0.4.0')
('davclient', '0.2.0')
('python-cim', '1.1')
('hexdump', '3.3')
('PTP', '0.3.0')
('PyDAV', '0.21')
('python-pyqt5-hexview', '0.4.3')
('easywebdav', '1.2.0')
('isodate', '0.5.4')
('python-owasp-zap-v2', '0.0.9')
('pyparsing', '2.1.7')
('pexpect', '4.2.0')
('cffi', '1.7.0')
('PyVirtualDisplay', '0.2')
('EasyProcess', '0.2.2')
('funcy', '1.7.1')
('webencodings', '0.5')
('html5lib', '0.999999999')
('intervaltree', '2.1.0')
('rdflib', '4.2.1')
('SPARQLWrapper', '1.7.6')
('certifi', '2016.8.8')
>>> 
```
## Possible Solution
This seems to be a bug more with pip than OWTF, but I was asked to report the issue here.
pip is version 8.1.2 on Python2.7

## Steps to Reproduce (for bugs)
1. git clone https://github.com/owtf/owtf.git
2. cd owtf/
3. python2 install/install.py
4. use defaults for all variables in the install script
5. ./owtf.py
6. failure

## Logs

None available

## Context

Can't use OWTF

## Your Environment

Kali Rolling latest update
pip 8.1.2
Python 2.7
installed using git instructions 
attempted to start OWTF
OWTF failed
crying uncontrollably started.

**Comment by DarKnight24** [comment]
@Graph-X This [issue](https://github.com/owtf/owtf/issues/516) has already been raised. Currently you can temporarily make OWTF work using virtualenv. Have a look at this [comment](https://github.com/owtf/owtf/issues/516#issuecomment-226993626).

**Comment by Graph-X** [comment]
That fixed it.  Thanks!
