### ISSUE TITLE
target required wrapper problem

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#722]
## Expected Behavior

whichever function is wrapped with target_required function should get target_id every time it is called no matter it is called from CLI or UI.
## Current Behavior

whichever function is wrapped with target_required function is getting target_id only when a new (not in database) target is provided. On successive runs for same target from CLI it fails.
## Possible Solution

[This](https://github.com/DoomTaper/owtf/commit/5090e034c2fef37524c905890a8dae25051238dd#diff-b3a64ea76164e9e9289670b57160a0e5R155) particular line is the fix. If you guys think of this as a legitimate issue then I'll send the PR.
## Steps to Reproduce (for bugs)

1. Make changes as [here](https://github.com/DoomTaper/owtf/commit/7dc5246fbc7b42974e8935c37b1b038bfe12789d)
2. run `./owtf.py -o OWTF-IG-001 http://example.com`. During first time it will print the target id.
   3.run again the same command it will print "None" this time.
3. Even if you run it with force overwrite option ( `./owtf.py -f -o OWTF-IG-001 http://example.com`), it will print "None".
## Context

This issue will be cause problem in those cases where any function has to deal with target_id each time it is called. Like I got in this issue while creating traffic uploader function which has to deal with the target id independent from where it is called either from CLI or UI. 
## Your Environment

- Installation method used: automatic
- Version/branch used: develop
- Operating System and version (like Kali, Debian, ArchLinux, etc): kali
- pip/setuptools version: 8.1.2
- sudo access: yes

**P.S.:** This is not valid if multiple targets are provided.

**Comment by delta24** [comment]
Do you have the correct implementation for multiple targets also?

**Comment by DoomTaper** [comment]
Nothing right now @delta24 :P

**Comment by viyatb** [comment]
Not applicable anymore.
