### ISSUE TITLE
follow fhs structure, aka make it distro friendly

### ISSUE THREAD

**Issue by blshkv** [owtf/owtf#725]
Hi, I'm trying to port the tool to pentoo and have some mess to clean up.

You keep system (database) configuration files in user's ~/.owtf folder and write results to a current folder which becomes system (read-only, /usr/lib64/owtf/owtf_review) after the tool is installed. It makes it difficult to preinstall and preconfigure it.

The tool should be able to start without ~/.owtf folder, read all configuration from system location and output all results to ~/.owtf.

Ideally, you should make it pip compatible and get rid of all *install shell hacks.

FYI: http://www.pathname.com/fhs/pub/fhs-2.3.html

**Comment by 7a** [comment]
Hi Anton,

Thanks for porting OWTF to Pentoo!
The idea of the OWTF output files is to generate them on a test basis, for
example :

cd 2016.08.Some_Client
/path/to/owtf.py

The files are saved on the current directory, which is :

2016.08.Some_Client/owtf_review

Then, you got another pentest, so you run OWTF from that other folder. This
way the OWTF output files are nicely saved on the relevant pentest
directory.

Users should never run owtf from the OWTF directory, maybe we should add a
warning for this  thoughts?

Makes sense?

Thank you and keep us posted!

Abe

**Comment by blshkv** [comment]
ok, I may be wrong about the output, but I found the following:
```
/framework/config/framework_config.cfg:
OUTPUT_PATH: owtf_review
```
So it is a current directory probably. Well, it would be good to have a warning that it will be a directory created, but I still find it is a bad behaviour. During a test, I could be in any directory actually. 

I've managed to convinced authords of few tools such as sqlmap (https://github.com/sqlmapproject/sqlmap/issues/746) and arachni (https://github.com/Arachni/arachni/issues/474)

So we keep configs in /etc/tool/* and the output in ~/.tool/* by default.

**Comment by delta24** [comment]
OWTF installation is primarily there to support Kali 2.x and the current approach works well. If you really need to tweak settings before installing to Pentoo, you can create a simple script which modifies the default **OUTPUT_PATH** to something like `~/.owtf/review/`.

**Comment by blshkv** [comment]
That's exactly my point. The tool should not be attached to a specific distro. You faced some problems already already after Kali moved all tools from /pentest location for example.

Also, the installation scripts are ugly. You should never install any packages from your tool and should never run "sudo". Leave it to a packet manager of each distro.

Make it PIP compatible and remove all workarounds such as customised configurations and installation scripts. That's the proper way.

**Comment by delta24** [comment]
> Also, the installation scripts are ugly. Make it PIP compatible and remove all workarounds such as customised configurations and installation scripts. That's the proper way.

Making OWTF `pip`  compatible is very hard and does not make sense. This is because the framework depends on a lot of different tools and the current method allows us to be much more flexible in handling tool variations, default configurations and libraries. 

> Leave it to a packet manager of each distro.

This is partly implemented - you can see the OWTF has separate distro-based installation for Debian-based, Arch, Samurai, etc.

As for 
> The tool should not be attached to a specific distro.

I agree - that is why we'll probably moving to a Docker based setup in near future so that the user is not tied to a specific distro.

**Comment by blshkv** [comment]
I've looked at the distro-specific scripts and it is a disaster.  As I mentioned, they change system files, install other tools using apt-get, pip and even wget like no tomorrow. 

However, "arch" looks different. There is a PKGBUILD script for the packet manager. But it does not belong here and should be pushed to arch tree. 

I have developed something similar for pentoo:
https://github.com/pentoo/pentoo-overlay/blob/master/net-analyzer/owtf/owtf-2.0a-r1.ebuild
As you can see, there are a lot of changes and hacks.  There are a lot of "sed" lines trying to adjust default configs to FHS structure but it is not complete because I got tired of this. For example, proxy cert keys and db.cfg are still in the "~/.owtf" folder

I would still have fix all paths if you fail to fix that bug. But it would also mean that it would require an additional validation with each new version and this is just wrong.

**Comment by delta24** [comment]
This means a huge change in the whole installation process and the way OWTF code structure is currently designed.

I believe OWTF will be moving to a Docker-based setup sometime towards the end of the year.

**Comment by blshkv** [comment]
https://www.youtube.com/watch?v=PivpCKEiQOQ

I've got an impression that you think Docker is some kind of magic which would allow you to say "use it and we dont support anything else" This is a wrong approach.  Users might face the same problem again once they decided to go with Heroku hosting for example.

**Comment by delta24** [comment]
More information and current progress tracking in #790.

**Comment by blshkv** [comment]
@delta24 I suggested several changes and the configuration file was only one of them.  Please do not close the bug report without addressing all of them
