### ISSUE TITLE
Human ranking propagates through the entire target.

### ISSUE THREAD

**Issue by saganshul** [owtf/owtf#727]
## Current Behavior
For example, 3 tools ranked their results, whatever, say, low + medium + high, I only rank the "low" as a "pass", because it was useless, but that makes the entire target to go to "pass", which is wrong (because the human has only overwritten 1 out of 3 automated rankings)

## Expected Behavior
The human ranking should only propagate to the target once all automated rankings have been overridden.

**Comment by DarKnight24** [comment]
@delta24 @saganshul 
I think the label added in ui against the target is weird on [target manager page](https://github.com/owtf/owtf/blob/develop/framework/interface/templates/target_manager.html#L349).
```
function getSeverityLabel(obj) {
  if (obj.max_user_rank != -1)
    return getLabel(obj.max_user_rank);
  return getLabel(obj.max_owtf_rank);
}
```
So if a target has user_rank then it will show it only irrespective owtf has given a high rank for any plugin against that target.

While on[ target panel](https://github.com/owtf/owtf/blob/develop/framework/interface/templates/plugin_report.html#L360) I guess the method used is correct.
```
    $.each(copyPOutputs, function(code, types) {
        $.each(types, function(type, poutput) {
            if (poutput.user_rank != null && poutput.user_rank > maxUserRank)
                maxUserRank = poutput.user_rank;
            else if (poutput.owtf_rank != null && poutput.owtf_rank > maxOWTFRank)
                maxOWTFRank = poutput.owtf_rank;
            if (maxUserRank == 5 || maxOWTFRank == 4)
                return false;
        });
        if (maxUserRank == 5 || maxOWTFRank == 4)
            return false;
    });
    localMax = (maxUserRank > maxOWTFRank) ? maxUserRank : maxOWTFRank;
```

@delta24  I think we will need to update the `getSeverityLabel` function same as `updateTargetInfo`.
I will send the PR for same after your view.

**Comment by DarKnight24** [comment]
I think we can replace `updateTargetInfo`
