### ISSUE TITLE
Add testssl.sh to the active ssl plugin

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#739]
Looks like this little tool has great feedback and I think it would probably be a good idea to run it in the active ssl plugin, any takers? :)

https://github.com/drwetter/testssl.sh

**Comment by Tikam02** [comment]
Yeah it has many essential features that can be implemented :
>Support of supplying timeout value for openssl connect -- useful for batch/mass scanning.
>tests via TLS sockets and improvements (handshake parsing, completeness, robustness)
>File output (CSV, JSON flat, JSON non-flat) supports a minimum severity level (only above supplied level there will be output)
>Parallel mass testing 
>Check for session resumption (Ticket, ID)
It seems like testssl.sh will  speed up the scanning process of targets and altogether scanning and testing process.

**Comment by viyatb** [comment]
Moved to https://github.com/owtf/community-plugins/issues/7.
