### ISSUE TITLE
Interface to use 'ZAP'/'BurpSuite Pro' API

### ISSUE THREAD

**Issue by BSec** [owtf/owtf#743]
Feature Request:

It would be nice to have and interface to add tools that are need per user choice of user.
For example, we have large user base of BurpSuite Pro and if there is an interface I would defiantly want to integrate BurpSuite Pro Results using its API into OWTF, this can attract more users with BurpSuite Pro license. Same applicable to ZAP & other open source users.

This will defiantly help the end user to have an integrated platform of testing which has builtin feature to consumes result of user's choice too.

**Comment by delta24** [comment]
@DePierre @BSec @7a can this be implemented as a Burp extension and import the results through the https://github.com/owtf/offline-http-traffic-uploader?

**Comment by DePierre** [comment]
@delta24 No idea to be honest :/

**Comment by viyatb** [comment]
Closing as won't-fix because Burp does not provide a ReST API.
