### ISSUE TITLE
CMS explorer download link returns a 404

### ISSUE THREAD

**Issue by saganshul** [owtf/owtf#745]
This issue arises on installing OWTF.

## Expected Behavior
Basically the download link ( http://cms-explorer.googlecode.com/files/cms-explorer-1.0.tar.bz2 ) should work.

## Current Behavior
Currently the link is broken and it returns 404.

## Steps to Reproduce (for bugs)
root@K2:~# python owtf/install/install.py

## Logs
[*] Installing CMS Explorer
[*] Switching to /root/owtf/tools/restricted/cms-explorer
[*] Running following command
wget --user-agent="Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/15.0" --tries=3 http://cms-explorer.googlecode.com/files/cms-explorer-1.0.tar.bz2; bunzip2 *; tar xvf *; rm -f *.tar 2> /dev/null; sh /root/owtf/install/update_convert_cms_explorer_dicts.sh /root/owtf
--2016-09-29 08:18:23--  http://cms-explorer.googlecode.com/files/cms-explorer-1.0.tar.bz2
Resolving cms-explorer.googlecode.com (cms-explorer.googlecode.com)... 64.233.161.82, 2a00:1450:400c:c06::52
Connecting to cms-explorer.googlecode.com (cms-explorer.googlecode.com)|64.233.161.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-09-29 08:18:24 ERROR 404: Not Found.

bunzip2: Can't open input file *: No such file or directory.
tar: *: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
[*] Going into directory: /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 28: cd: can't cd to /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0
[*] Updating cms-explorer dictionaries..
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 31: /root/owtf/install/update_convert_cms_explorer_dicts.sh: ./cms-explorer.pl: not found
Traceback (most recent call last):
  File "/root/owtf/scripts/update_cms_explorer_lists.py", line 87, in <module>
    get_plugins_wp()
  File "/root/owtf/scripts/update_cms_explorer_lists.py", line 26, in get_plugins_wp
    with open("%s/wp_plugins.txt.new" % CMS_EXPLORER_DIR, "w+") as file:
IOError: [Errno 2] No such file or directory: '/root/owtf/scripts/../tools/restricted/cms-explorer/cms-explorer-1.0/wp_plugins.txt.new'
[*] Merging old and new lists...
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 36: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_plugins.txt: Directory nonexistent
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 38: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_plugins.txt.tmp: Directory nonexistent
cat: /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_plugins.txt: No such file or directory
mv: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_plugins.txt.tmp': No such file or directory
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 36: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_themes.txt: Directory nonexistent
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 38: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_themes.txt.tmp: Directory nonexistent
cat: /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_themes.txt: No such file or directory
mv: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_themes.txt.tmp': No such file or directory
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 36: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_plugins.txt: Directory nonexistent
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 38: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_plugins.txt.tmp: Directory nonexistent
cat: /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_plugins.txt: No such file or directory
mv: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_plugins.txt.tmp': No such file or directory
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 36: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_themes.txt: Directory nonexistent
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 38: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_themes.txt.tmp: Directory nonexistent
cat: /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_themes.txt: No such file or directory
mv: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_themes.txt.tmp': No such file or directory
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 36: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_themes.txt: Directory nonexistent
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 38: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_themes.txt.tmp: Directory nonexistent
cat: /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_themes.txt: No such file or directory
mv: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_themes.txt.tmp': No such file or directory
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 36: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_plugins.txt: Directory nonexistent
/root/owtf/install/update_convert_cms_explorer_dicts.sh: 38: /root/owtf/install/update_convert_cms_explorer_dicts.sh: cannot create /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_plugins.txt.tmp: Directory nonexistent
cat: /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_plugins.txt: No such file or directory
mv: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_plugins.txt.tmp': No such file or directory
[*] Copying updated dictionaries from /root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0 to /root/owtf/dictionaries/restricted/cms
cp: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_plugins.txt': No such file or directory
cp: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_themes.txt': No such file or directory
cp: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_plugins.txt': No such file or directory
cp: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/drupal_themes.txt': No such file or directory
cp: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/wp_themes.txt': No such file or directory
cp: cannot stat '/root/owtf/tools/restricted/cms-explorer/cms-explorer-1.0/joomla_plugins.txt': No such file or directory
cat: 'dir_buster*': No such file or directory
cat: 'dir_buster*': No such file or directory
cat: 'dir_buster*': No such file or directory
[*] Creating all-in-one CMS dictionaries for DirBuster and CMS Explorer

## Context
This issue result into installation failure. 

## Your Environment

* Operating System and version (like Kali, Debian, ArchLinux, etc): Kali2

**Comment by delta24** [comment]
@saganshul Google changed the URLs - the new URL is https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/cms-explorer/cms-explorer-1.0.tar.bz2. Send a PR!  :)

**Comment by saganshul** [comment]
#747 fixes the bug . Closing the issue.
