### ISSUE TITLE
OWTF startup directory

### ISSUE THREAD

**Issue by saganshul** [owtf/owtf#746]
Ideally, OWTF should never be run from its own directory because it does not make sense.
## Expected Behavior

On running OWTF from it own directory it should print "Please navigate to the working directory for your pentest and then run OWTF like this: /path/to/owtf.py"
This will create an owtf_review directory for that pentest/project"
## Current Behavior

It does not print this message and OWTF as usual.

**Comment by delta24** [comment]
@saganshul @7a should we do something like this? 
1. Normal OWTF run should ask to create a new directory for a pentest (if not already in it).
2. For developers, we should add `--dev` to bypass this check
?

**Comment by 7a** [comment]
Even a developer should never run OWTF from its own directory:
We are talking output files being saved in a tool directory :)

I think the best way to avoid this mess is simply to do something like this:
Option 1) Refuse to run OWTF if on the same directory.
or
Option 2) Require an output directory parameter when OWTF is run

Other thoughts in https://github.com/owtf/owtf/issues/766 :)

**Comment by DarKnight24** [comment]
@delta24 Should we refuse to run if on the same directory?

**Comment by delta24** [comment]
@DarKnight24 yes.

**Comment by delta24** [comment]
Fixed in https://github.com/owtf/owtf/pull/789.
