### ISSUE TITLE
Deadlock issue for some of the plugins.

### ISSUE THREAD

**Issue by saganshul** [owtf/owtf#749]
There seem to be deadlock issues on the following plugins: 
"semi-passive / session management schema",
"Plugin: Http Methods And Xst (web/active)"
0 results for: ps -ef | grep -i hoppy | grep -v grep
## Your Environment
- Operating System and version (like Kali, Debian, ArchLinux, etc): Kali2

**Comment by delta24** [comment]
Yup, I also noticed this issue in a pentest - can you look more into it?

**Comment by DarKnight24** [comment]
@delta24 @saganshul  I am not able to reproduce anything for `"Plugin: Http Methods And Xst (web/active)"`. Please suggest a way to reproduce the problem.

**Comment by DarKnight24** [comment]
@saganshul Did you face the problem again?

**Comment by delta24** [comment]
@DarKnight24 this will always result in a deadlock because of https://github.com/owtf/owtf/issues/449.

**Comment by viyatb** [comment]
Closing as duplicate of https://github.com/owtf/owtf/issues/695.
