### ISSUE TITLE
Spiders_Robots_and_Crawlers plugin is broken

### ISSUE THREAD

**Issue by saganshul** [owtf/owtf#750]
The Spiders_Robots_and_Crawlers plugin is broken and hangs forever, at least sometimes: 

## Logs
Worker 4 - Spiders_Robots_and_Crawlers (1 hour ago)

## Your Environment

* Installation method used:
* Version/branch used:
* Operating System and version (like Kali, Debian, ArchLinux, etc): Kali2
* pip/setuptools version:
* sudo access:

**Comment by DarKnight24** [comment]
@delta24 I have looked into it and I think passive plugin is stucking due to some exception thrown. I will look into it and fix it asap.
