### ISSUE TITLE
Wrong worker log file created on creating new worker

### ISSUE THREAD

**Issue by saganshul** [owtf/owtf#758]
On creating new worker, let say worker-5 , worker log file in owtf_review/logs/ generated by the API call is worker-8.log.
## Expected Behavior

It is should create correct log file.
## Current Behavior

On creating new worker, let say worker-5 , log file generated by the API call is worker-8.log.
## Steps to Reproduce (for bugs)

1. Go to /ui/workers/
2. Click Add worker
3. Go to owtf_review/logs
## Your Environment

- Installation method used: 
- Version/branch used: Develop

**Comment by DarKnight24** [comment]
@saganshul are you working on this?

**Comment by saganshul** [comment]
@DarKnight24 currently, I am not working on this.

**Comment by DarKnight24** [comment]
@saganshul Is this bug fixed?

**Comment by saganshul** [comment]
@DarKnight24 no

**Comment by DarKnight24** [comment]
@saganshul What backend problem is left to fix?

**Comment by saganshul** [comment]
@DarKnight24  Backend is generating wrong worker log file "On creating new worker, let say worker-5 , worker log file in owtf_review/logs/ generated by the API call is worker-8.log".
As a part of front end I just doubled checked it and avoid if nothing found.

**Comment by DarKnight24** [comment]
@saganshul After this PR is merged, use the name field obtained in json to get worker logs.

**Comment by saganshul** [comment]
sure!
