### ISSUE TITLE
OWTF installer recommendation misleads new users

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#766]
OWTF should never, ever, be run from its own directory, this makes absolutely no sense since that will result in creating the output files for a given pentest within the OWTF directory.

In the real world, an OWTF user should run OWTF *always* like:

cd /path/to/pentest/directory
/path/to/owtf.py

This results in the output files being saved in the correct directory for a given pentest, instead of the OWTF directory.

Unfortunately, the installer is recommending users to do exactly this, which has led to confusion in the past, this should be replaced with an explanation like above:

[*] Start OWTF by running './owtf.py' in parent directory

We had even distro maintainers trying to call OWTF like this, maybe we should even go a step further and literally refuse to run OWTF when it is on its own directory.

Thoughts? :)

**Comment by saganshul** [comment]
#746 Copy of this issue.

**Comment by ujjwal96** [comment]
Anyone working on this?
If not, can you assign it to me. I'd like to contribute

**Comment by delta24** [comment]
Hi @ujjwal96, welcome to OWTF! You cannot be assigned the issue because you are not a member of the organization. However you can fork OWTF, implement a fix and send a PR! :)
