### ISSUE TITLE
[UI Improvements] Worker refresh is too quick for log line selection

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#768]
When I go to:
http://127.0.0.1:8009/ui/workers/

And then try to select a number of lines to be displayed from the dropdown, while a worker is running, this is not possible because the worker panel is refreshing too quickly.

Suggestion: Maybe we could decrease the refresh time a bit? it is close to impossible to choose a number of lines from the dropdown now :D

**Comment by saganshul** [comment]
@7a This is same issue I was facing. Yeah! we can increase the refresh time. Can you suggest which will be good. IMO 5-10 sec will be good.

**Comment by 7a** [comment]
We'll have to shoot a bit more conservatively, perhaps 10-15, see https://github.com/owtf/owtf/issues/769

But much better than before, we're getting there! ;)

**Comment by saganshul** [comment]
@delta24 you can close this issue now.
