### ISSUE TITLE
[UI Improvements] Workers and Dashboard panels need to be much more lightweight

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#769]
Edit: Same happens on the Dashboard tab but a bit less bad (20% CPU)

The ui on the workers panel is too heavy, CPU goes to 30-40% when you run 3 workers that are actively scanning stuff.

This happens consistently as I switch to "workers" (30-40% CPU) from "targets" (Chrome CPU goes down to 6%).

Background: Given the time constraints and limited resources in equipment that a pentester could have, the last thing you want is the browser to hog CPU, while scanners should use it instead :)

Suggestions:
 - Decrease refresh time
 - Make the log lines displayed optional (i.e. only if the user clicks on a button, and then only for that worker)
 - Try to see if this can be more lightweight

**Comment by delta24** [comment]
@saganshul can you see to the 2 point?
> Make the log lines displayed optional (i.e. only if the user clicks on a button, and then only for that worker)

**Comment by delta24** [comment]
@saganshul why not render the interface using React rather than using the old template?

**Comment by saganshul** [comment]
@delta24, sure! we can do that but it will take time and I am not doing it as part of a project. So I edited the present Jquery code. But yeah it will be done sometime later when I actually have time.

**Comment by viyatb** [comment]
This has been done in the `ui-improvments` branch! :)
