### ISSUE TITLE
Default installation fails to install O-Saft

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#772]
NOTE: Tried on UI Improvements branch (please merge fix there for next round! ;)

O-Saft does not appear in the installation trail and the SSL active plugin returns the following output for O-Saft, which means the installer failed to install it:

```
/bin/sh: 1: /usr/bin/o-saft: not found
```

**Comment by delta24** [comment]
@7a Kali removed it from default installation. I think we'll need to add it to the install script :P
