### ISSUE TITLE
tools bug report

### ISSUE THREAD

**Issue by Any3ite** [owtf/owtf#780]
hey my friend 👍 
       very thanks your team provide this tools，
now im installed owtf on my vmware - kali-2016.2， and run this tools， im edit config file ，edit listen ip 0.0.0.0 and create task， scan website  http://testphp.vulnweb.com ，but nikto tell me 0 host up ， omg！~  and run plugins arachni ， scan http://testphp.vulnweb.com  scan result is 0issue 。 i don't know what's happend.  why can be this , and i think you can at next version provide custom tools command  function。 this is my all  report issue ， thanks  very mach

**Comment by delta24** [comment]
Possible spam.
