### ISSUE TITLE
[Feature Request] Add a update script

### ISSUE THREAD

**Issue by DarKnight24** [owtf/owtf#784]
Currently if any version changes are done, to incorporate with it we need to do it manually or rerun install script. We can add a update script containing changes to be done to update the tools on which owtf depends.

## Expected Behavior

It should update the tool on which owtf depends to its newest version supported. This will remove the manual work.

**Comment by delta24** [comment]
I am working on making a Dockerfile in the main repo to have a fully functional development environment on any OS. That will solve majority of these issues. The current `owtf/owtf-docker` is too large and very bloated.

I'll have more time after 16th to work on these issues. (finals week atm)

**Comment by viyatb** [comment]
Most of the tools are included by Kali and can be upgraded using `apt-get dist-upgrade` or `apt-get upgrade`. Others are just hosted on external websites but are not updated as frequently.
IMO it is not the job for OWTF (+ discussion on https://github.com/owtf/owtf/pull/843)

**Comment by DePierre** [comment]
@viyatb I agree with you. @DarKnight24 It is not OWTf's job to make sure that your distribution is up-to-date but the user's responsibility.
