### ISSUE TITLE
Will not install on Kali

### ISSUE THREAD

**Issue by eflittle** [owtf/owtf#786]
## Current Behavior

Installing with the bootstrap.sh with the command:
 wget https://raw.githubusercontent.com/owtf/bootstrap-script/master/bootstrap.sh
bash bootstrap.sh

When it gets to Building wheels for collected packages: lxml, pycurl, cryptography, all 3 module builds fail with the message Filed to build lxml pycurl cryptography.

Then when installing collected packages: lxml, Markdown, pexpect, psycopg2, PTP, pycurl, six, cryptography, pyOpenSSL, phython-owasp-zap-V2, EasyProcess, PyVirtualDisplay, isodate, SPARQLWrapper, rdflib, selenium, SQLAlchemy, certifi, tornado

The script fails with lxml, and generates a "Can't rollback lxml, nothing installed."

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Installation method used:
* Version/branch used:
* Operating System and version (like Kali, Debian, ArchLinux, etc):
* pip/setuptools version:
* sudo access:

**Comment by delta24** [comment]
@eflittle did you try installing using virtualenv? Kali 2016.x (rolling) has a known problem.

**Comment by eflittle** [comment]
No.
