### ISSUE TITLE
owtf.py run is nothing

### ISSUE THREAD

**Issue by hktalent** [owtf/owtf#787]
1、mac os 10.12.2
2、install is ok
3、$ cat  ~/.owtf/db.cfg 
DATABASE_IP: 127.0.0.1
DATABASE_PORT: 5433
DATABASE_NAME: msf
DATABASE_USER: msf
DATABASE_PASS: +kgeBhms5Igd776CnAjvf0OZQdBdB5TKHMwtQLCyxjY=

4、nothing ?
$ ./owtf.py 

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
$

**Comment by DarKnight24** [comment]
What is the output when you execute ./owtf.py ?
Can you put a screenshot in the comments?

**Comment by delta24** [comment]
@hktalent OWTF is not supported on MacOS. You should run OWTF on Linux, preferably Kali Linux.

**Comment by hktalent** [comment]
@delta24 ok, thank
@DarKnight24 
￼

**Comment by hktalent** [comment]
kali linux
install is ok
update is ok
always 
# ./owtf.py 
The following python libraries seem missing : 
	Markdown,ndg-httpsclient,pyOpenSSL

Haven't you run the install script? 
	python2 install/install.py

If you are sure you ran the install script, install the missing libraries seperately
	pip install --upgrade -r install/owtf.pip

why?
how?
thank you

**Comment by delta24** [comment]
Did you try using https://github.com/owtf/owtf/issues/516#issuecomment-226993626? We have a PR for this one - should be in develop branch soon!
