### ISSUE TITLE
[config] Move the framework configuration file out of framework directory

### ISSUE THREAD

**Issue by delta24** [owtf/owtf#790]
The `framework_config.cfg` file is currently inside the `framework/config` directory which is bad.
Instead there should be a default configuration file which is there and the user modified configuration file is not committed.

 The `-m` profiles option provides this functionality for the loading user profiles but not the framework configuration.

#### Solution
- [ ] Move the `framework_config.cfg` outside the framework directory.
- [ ] Rename it as `framework_config.cfg.default`.
- [ ] At run-time, check for the file `framework_config.cfg`. If it does not exists, create a copy of the default configuration file for usage, otherwise load the user modified `framework_config.cfg` file.

or maybe even move all configuration files to `~/.owtf`? @DarKnight24 @7a?

**Comment by affinity7** [comment]
@delta24 I am willing to fix this. Please suggest an approach for this issue.

**Comment by delta24** [comment]
@affinity7 see the issue description. I've worked out a possible solution.

**Comment by DarKnight24** [comment]
@delta24 I suggest to read all the config from `~/.owtf` folder. We can create default files from `$root_dir/profiles` folder in case config file is absent.

**Comment by affinity7** [comment]
@delta24 where should we move the config file from framework directory to?

**Comment by delta24** [comment]
@DarKnight24 sounds good. @DePierre ?

**Comment by DePierre** [comment]
@delta24 Your proposition sounds great IMO
@affinity7 Anywhere that makes sense, while keeping some consistency with the other configuration files

**Comment by delta24** [comment]
@affinity7 @DarKnight24 @DePierre ok, so here is a brief implementation plan:

- Move the default configuration files to `$rootdir_OWTF/default`.
- During installation, copy over the default configuration files to `~/.owtf` and change the code to load the configuration (as well as profiles) from there.
- Always prefer the configuration files in `~/.owtf` over the default ones. Check at run-time if the user copy exists, otherwise create the copy at run-time.

sounds good?

**Comment by DePierre** [comment]
@delta24 Just a thought. How about keeping some consistency between the hierarchy in `$rootdir_OWTF/` and `~/.owtf/` with something like:

```
$rootdir_OWTF/
    configuration/
        [default configuration files here]
~/.owtf/
    configuration/
        [user configuration files here]
```

**Comment by delta24** [comment]
@DePierre sounds good.

**Comment by delta24** [comment]
@DePierre @DarKnight24 should this also include the `profiles` folder?

**Comment by DarKnight24** [comment]
@delta24 Yes, all the configuration files will be shifted to `.owtf/` folder as discussed above. We will have all files from profile and `framework.cfg` to `configuration` folder as @DePierre commented.

**Comment by affinity7** [comment]
@delta24 @DePierre @DarKnight24 The profile folder also contains plugin config files. Should I move them to the `configuration` folders too?

**Comment by jack17529** [comment]
So is the bug still open ??

**Comment by DePierre** [comment]
@jack17529 I wouldn't say that this is a bug but yes it is still open. A PR is currently being reviewed (see #800). We are waiting for @affinity7 to update the PR according to our comments.
