### ISSUE TITLE
Database related scripts runs before postgresql installation

### ISSUE THREAD

**Issue by DarKnight24** [owtf/owtf#797]
Currently the database setup scripts are set to run before the installation of postgresql. This is creating failure in the database creation scripts.

## Expected Behavior

Database related scripts should be run after proper installation of postgresql during installation.

## Possible Solution

Change the order of the installation.

## Context

During installation.

## Your Environment

* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): Kali

**Comment by delta24** [comment]
Fixed in 6816acdaf7750f9ff91dd08ccb3a2cef210346ba. (wrong issue number! :P )

**Comment by delta24** [comment]
@DarKnight24 I know. The next step is to move those dependencies to `owtf.pip`.
