### ISSUE TITLE
Invoking ./db_run.sh produces owtf/scripts/db_run.sh: line 85: syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by irn00b** [owtf/owtf#802]
root@kali:/opt# ./owtf/owtf.py 

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
ERROR:root:Aborted by Framework: [DB] (psycopg2.OperationalError) FATAL:  password authentication failed for user "owtfuser"
FATAL:  password authentication failed for user "owtfuser"

Run scripts/db_run.sh to start/setup db
root@kali:/opt# sh owtf/scripts/db_run.sh 
owtf/scripts/db_run.sh: 85: owtf/scripts/db_run.sh: Syntax error: "fi" unexpected (expecting "then")
root@kali:/opt# bash owtf/scripts/db_run.sh 
owtf/scripts/db_run.sh: line 85: syntax error near unexpected token `fi'
owtf/scripts/db_run.sh: line 85: `        fi'

## Steps to Reproduce (for bugs)

1. Install OWTF using bootstrap.sh or via git clone source && python2 install/install.py
2. run sudo ./owtf/owtf.py resulting to db error and suggests run scripts/db_run.sh
3.  bash owtf/scripts/db_run.sh
4. generates this error:  line 85: syntax error near unexpected token `fi'

## Context

I was trying to install OWTF for research purposes.

## Your Environment

* Installation method used: Used bootstrap.sh
* Version/branch used:
* Operating System and version (like Kali, Debian, ArchLinux, etc): Linux kali 4.4.0-kali1-686 #1 SMP Debian 4.4.2-3kali1 (2016-02-23) i686 GNU/Linux
* pip/setuptools version:
* sudo access: yes

**Comment by delta24** [comment]
@irn00b Thanks! It should be fixed now.

**Comment by irn00b** [comment]
that was fast, thank you!
