### ISSUE TITLE
Issues in install script

### ISSUE THREAD

**Issue by DarKnight24** [owtf/owtf#809]
@delta24 @DePierre @7a I have found following problems in install script:
*  The check in `install.py` whether owtf installed successfully is useless as install function does not return anything. Look [here](https://github.com/owtf/owtf/blob/develop/install/install.py#L315). The `installer_status_code` is always `null`. 
*  The debian installer has missing sudo access for `pref.sh`. Look [here](https://github.com/owtf/owtf/blob/develop/install/debian/install.sh#L48)
*  `pref.sh` in debian installer is using `kali-bleeding-edge` I guess. Should we use kali-rolling?
*  Travis is showing error while installing postgres-9.6. Look [here](https://travis-ci.org/owtf/owtf/builds/194497121#L382)

Please comment over the issues.

**Comment by delta24** [comment]
@DarKnight24 

- [ ] Re: check in `install.py`: Correct - should the `install` function return something meaningful?
- [ ] Re: `sudo` access in `pref.sh` missing - yes, add that! and yes it should use Kali rolling (there was no rolling version at that time :( )
- [ ] Re: They are warnings - IMO this is because of some misconfiguration in `.deb` package. (IMO we should not change anything)

**Comment by DarKnight24** [comment]
@delta24 IMO there should not be any check as we cannot simply tell whether error occurred in the shell script or not. The return code will be the return code of the last command, if it was successful it will return 0 regardless of the error occurred previously.

**Comment by DarKnight24** [comment]
@delta24 After the fix [`101a8c8`](https://github.com/owtf/owtf/commit/101a8c8312ab67a869c04fd189c308a7830068bc) the script is having GPG issue. Look [here](https://travis-ci.org/owtf/owtf/builds/195805134#L992) and [here](https://travis-ci.org/owtf/owtf/builds/195805134#L1051).

**Comment by delta24** [comment]
@DarKnight24 should be fixed in https://github.com/owtf/owtf/commit/e6b271df0f8723205b984b5340b74961266f0fdf.
