### ISSUE TITLE
Filter work from the worklist ands  delete all / pause all / resume all in the output

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#822]
A very useful and needed worklist improvement: It should be possible to filter + select all + delete all / pause all / resume all on the worklist. For example, if I want to delete all the "niktos" from the worklist I should be able to filter by "nikto", then "delete all selected" (or something like that)

If I "delete all" right now, I delete the entire worklist, which is not as useful.

**Comment by sharmamohit123** [comment]
I would like to work on this issue.
