### ISSUE TITLE
Target export functionality broken

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#823]
The targets export functionality in the `ui_improvements` branch is broken. 

Need to investigate more.

**Comment by saganshul** [comment]
@delta24 I added 914 targets. Export functionality is working correctly. 
I am not able to reproduce the error.

**Comment by delta24** [comment]
@7a maybe this was a one-off event where the JS code responsible was not properly loaded in the browser.

**Comment by jack17529** [comment]
@viyatb can you elaborate the issue and send the link of the code.

**Comment by viyatb** [comment]
Cannot reproduce. Closing.
