### ISSUE TITLE
OWTF cannot find hoppy in a new fresh installation

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#824]
The hoppy plugin cannot find the installation in the OWTF root directory. Below is the stacktrace,
```
[*] /bin/sh: 1: cd: can't cd to /root/owtf/tools/restricted/hoppy-1.8.1/hoppy-1.8.1
[*] /bin/sh: 1: ./hoppy: not found
```

> UPDATE: This happens because the domain `https://labs.portcullis.co.uk/` presents an invalid HTTPs certificate and wget does not proceed.
> The fix is to add `no-check-certificate` arg for the time being.

**Comment by supreet11agrawal** [comment]
@delta24 I am a first timer on GitHub and I am seriously looking forward to contribute. Can you please guide me?

**Comment by delta24** [comment]
@supreet11agrawal Try to installing OWTF on the latest Kali Linux and run `Plugin semi_passiveHTTP_Methods_and_XST@OWASP-CM-008.py`plugin to reproduce the issue. Then try to implement a fix.

**Comment by DePierre** [comment]
@delta24 This is a won't fix if Hoppy SSL certificate is expired. We have to wait for them to fix their own shit.

Also starting adding this kind of wget option is IMO a bad idea.

**Comment by delta24** [comment]
@DePierre I agree - I contacted them about this via Twitter. Hopefully it gets fixed soon!

**Comment by viyatb** [comment]
They fixed it! :)

**Comment by DePierre** [comment]
Finally! It took them a while :/
