### ISSUE TITLE
w3af patching script error

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#825]
OWTF patches the w3af console for a number of reasons like normalizing the User Agent string, etc. The Kali install script cannot find `w3af_console`.

```
/root/owtf/install/kali/kali_patch_w3af.sh: 16: /root/owtf/install/kali/kali_patch_w3af.sh: w3af_console: not found
-e
```

**Comment by jack17529** [comment]
@delta24 please assign me this , I will start working with full intensity in 4-5 days.

**Comment by delta24** [comment]
@jack17529 The issue can be assigned only if you are a member of the organization. However you are free to work on it, and send a PR!

**Comment by jack17529** [comment]
@viyatb ,please tell me how can someone become member?

**Comment by DePierre** [comment]
@jack17529 When @viyatb mentionned "only if your are a member", it was meant only for github. Anyone can work on a fix but on github, only OWTF member crews can be assigned in the UI.

You are free to create a fix and open a pull request that references this issue ;)

**Comment by jack17529** [comment]
So is this the problem
![screenshot from 2017-02-23 07 43 17](https://cloud.githubusercontent.com/assets/15366183/23241889/01dc0a08-f99c-11e6-8861-3aa783cf2913.png)

**Comment by viyatb** [comment]
@jack17529 Yes.

**Comment by Tikam02** [comment]
@jack17529 can  you please provide the log.

**Comment by Tikam02** [comment]
@jack17529  i could not produce the same issue, it's working fine on my system, just check updates or do update your kali repository check it once.

![w3af2](https://user-images.githubusercontent.com/10548085/29502517-78f2c020-85e5-11e7-8968-13f72cd5bb1b.png)
![w3af](https://user-images.githubusercontent.com/10548085/29502518-79eb0eec-85e5-11e7-8d87-42778db37af2.png)

**Comment by viyatb** [comment]
w3af-console was broken for some time before, but its fixed in the new version.
