### ISSUE TITLE
Integrate HTTP requests translator tool in OWTF

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#829]
Tool - https://github.com/owtf/http-request-translator

The feature should support:

* Single HTTP transactions
Have a button to "export HTTP request" , then show its relevant code.

* Multiple HTTP transactions
Same as with Single transactions, but letting the user "select a number of transactions" first.
 
The end result should something like: (although it has to be modified for the web interface changes)

<img width="682" alt="screen shot 2017-02-19 at 17 14 48" src="https://cloud.githubusercontent.com/assets/4557897/23107284/536c638a-f6c8-11e6-89fa-ad8728a1bd1d.png">

**Comment by saganshul** [comment]
I am starting working on it now.

**Comment by DePierre** [comment]
HTTP Request Translator is now available on PyPi: https://pypi.python.org/pypi/hrt/0.1.0

@saganshul Could you update OWTF's pip requirement accordingly?

**Comment by saganshul** [comment]
@DePierre sure!

**Comment by viyatb** [comment]
Fixed in PR https://github.com/owtf/owtf/pull/832.
