### ISSUE TITLE
KeyError while installing - KeyError: 'WORKON_HOME'

### ISSUE THREAD

**Issue by sachinkamath** [owtf/owtf#836]
The installation of OWTF from ./owtf/owtf/install fails with a KeyError

## Current Behavior

Throws a `KeyError` : 
<pre>
Traceback (most recent call last):
  File "install.py", line 307, in <module>
    installer_status_code = install(sys.argv[1:])
  File "install.py", line 211, in install
    setup_virtualenv()
  File "install.py", line 133, in setup_virtualenv
    if os.path.join(os.environ["WORKON_HOME"], "owtf") == os.environ["VIRTUAL_ENV"]:
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'WORKON_HOME'

</pre>
## Possible Solution

Check if the environment variable is set.  The problem with the environment variable is not very visible on googling.
(Is this out of context from OWTF point of view?)

## Steps to Reproduce (for bugs)

1. Navigate to installation folder
2. Run the installer

## Your Environment

* Installation method used: Manual
* Version/branch used: develo[
* Operating System and version (like Kali, Debian, ArchLinux, etc): ArchLinux
* pip/setuptools version: pip 9.0.1
* sudo access: Yep :)

**Comment by viyatb** [comment]
@sachinkamath you are not using the latest develop. This `    installer_status_code = install(sys.argv[1:])` was removed sometime back.

**Comment by sachinkamath** [comment]
@viyatb Pretty sure I am on the latest develop :)

![screenshot from 2017-03-06 19-38-34](https://cloud.githubusercontent.com/assets/9546091/23613267/c25af198-02a4-11e7-9bb6-bc4c66d9a14c.png)

**Comment by viyatb** [comment]
@sachinkamath you must've updated after this. The lines on your stacktrace do not exist in the latest develop.

**Comment by sachinkamath** [comment]
@viyatb Yes. After I saw your message, I did update and had the same error. That's why I commented.

**Comment by viyatb** [comment]
@sachinkamath can you post the stacktrace from the updated installation?

**Comment by sachinkamath** [comment]
@viyatb, I pulled #837 from @DarKnight24 's repo and it seemed to have worked. Ran the install again after cleaning up my `.zshrc` and  `git reset --hard HEAD~1` and here is the stacktrace : 

<pre>
Traceback (most recent call last):
  File "install.py", line 304, in <module>
    install(sys.argv[1:])
  File "install.py", line 214, in install
    setup_virtualenv()
  File "install.py", line 129, in setup_virtualenv
    if os.path.join(os.environ["WORKON_HOME"], "owtf") == os.environ["VIRTUAL_ENV"]:
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'WORKON_HOME'
</pre>


Can confirm #837 fixes this issue :100:

**Comment by viyatb** [comment]
@sachinkamath that did not fix the installation. It simply skipped the `pip` dependency installation because the environment variable was not found.
I don't have access to an Arch installation but I don't understand why the environment variables are not being updated. There can be 2 reasons: either your .zshrc is doing something funny or there is a problem with Arch specifically (less probable).

Can you debug at the line which adds the environment variables to the shell config? https://github.com/owtf/owtf/blob/develop/install/install.py#L128

**Comment by sachinkamath** [comment]
@viyatb Ah, got it. Will dig in and let you know. Thanks :smile:

**Comment by sachinkamath** [comment]
@viyatb Finally figured it out. Arch has python3 as the default Python interpreter so `virtualenv` was symlinked to the `python3-virtualenv`.

Not a big fan of python3 so the following fixed it: 
<pre>
cd /usr/bin
ln -sf virtualenv2 virtualenv
</pre>

IMO, we should explicitly use `virtualenv2` instead of `virtualenv` in install.py.

**Comment by viyatb** [comment]
@sachinkamath good idea. @DarKnight24 can you send a PR?

**Comment by sachinkamath** [comment]
@viyatb @DarKnight24 Forgot one more thing. I had to change the [source line](https://github.com/owtf/owtf/blob/develop/install/install.py#L118) from `source /usr/local/bin/virtualenvwrapper.sh` to `source /usr/bin/virtualenvwrapper.sh` on Arch. We should also maybe check if `/usr/local/bin/virtualenvwrapper.sh` exists or not. 

The no such file or directory can easily go un-noticed on stdout. If these are the only things required to be changed, I can maybe send in a PR :)

**Comment by viyatb** [comment]
@sachinkamath that's a Arch specific thing afaik. Send a PR - @DarKnight24 can check if its valid!

**Comment by DarKnight24** [comment]
@sachinkamath What is the location of `virtualenvwrapper.sh` file in arch linux. Try `locate virtualenvwrapper.sh` to get it.
