### ISSUE TITLE
Script installation of Httprint cant find tools/restricted/httprint

### ISSUE THREAD

**Issue by greenfreq** [owtf/owtf#839]
Running Fresh installation of Debian 8.7 (7Mar2017)
After performing a git clone (without -b branch) and running the install/install.py  an error occurs stating that tools/restricted/httprint is missing and the script exists with:

OSError: [Errno 2] No such file or directory: '/home/sysadmin/owtf/tools/restricted/httprint'

## Expected Behavior
I presume that Httprint should be installed

## Current Behavior
Httprint installation fails to install and installation script exits [Errno 2]

<snip>
[*] Installing Httprint
Traceback (most recent call last):
  File "install/install.py", line 304, in <module>
    install(sys.argv[1:])
  File "install/install.py", line 219, in install
    install_restricted_from_cfg(restricted_cfg)
  File "install/install.py", line 97, in install_restricted_from_cfg
    install_in_directory(os.path.expanduser(cp.get(section, "directory")), cp.get(section, "command"))
  File "install/install.py", line 71, in install_in_directory
    if create_directory(directory):
  File "install/install.py", line 26, in create_directory
    if not os.listdir(directory):
OSError: [Errno 2] No such file or directory: '/home/sysadmin/owtf/tools/restricted/httprint'
</snip>

## Possible Solution

Maybe the file was accidentally deleted or moved and the script was not updated.

## Steps to Reproduce (for bugs)

Run the install/install.py script will reproduce the error.

## Your Environment
* Installation method used: Git Clone 
* Version/branch used: Tikka Masala v2.0
* Operating System and version (like Kali, Debian, ArchLinux, etc): Debian 8.7
* pip/setuptools version: pip 9.0.1

**Comment by viyatb** [comment]
@greenfreq There have been some changes. Can you download the latest version from the develop branch? https://github.com/owtf/owtf/archive/develop.zip

**Comment by greenfreq** [comment]
After renaming the old owtf and downloading the above develop.zip and running the install script no errors were identified; however, execution of owtf.py shows a misiing module named tornado.
Do you want a new issue entered?
<snip>
Traceback (most recent call last):
  File "./owtf.py", line 14, in <module>
    from framework.core import Core
  File "/home/sysadmin/owtf-develop/framework/core.py", line 14, in <module>
    import tornado
ImportError: No module named tornado
</snip>

**Comment by viyatb** [comment]
@greenfreq you need to run the install script again. There have been a ton of changes since the last release.

**Comment by greenfreq** [comment]
@viyatb Not sure which install script you are refering to.  As I stated in my comment above, I moved the old git clone and downloaded the zip file and ran the install/install.py script from that dev version.  No error were reported during the install.

**Comment by viyatb** [comment]
@greenfreq I meant the `install/install.py` script. As your installation traceback says, and the ![readme](https://github.com/owtf/owtf/blob/develop/README.md) says, you need to reload your script configuration and activate the OWTF python environment.
Do
`source .bashrc`
`workon owtf`.

This has been done to provide a clean Python environment for OWTF (and to support every Linux distribution).

**Comment by greenfreq** [comment]
the source and workon commands appear to have done the trick
