### ISSUE TITLE
Unable to Add Workers

### ISSUE THREAD

**Issue by CreativeWolf** [owtf/owtf#846]
## Expected Behavior
Add Worker should be able to add more workers

## Current Behavior
Throws Error

```
Uncaught TypeError: Cannot read property 'localeCompare' of undefined
    at Object.<anonymous> ((index):273)
    at Function.each (jquery.js?v=5ca7582…:2)
    at Object.success ((index):256)
    at j (jquery.js?v=5ca7582…:2)
    at Object.fireWith [as resolveWith] (jquery.js?v=5ca7582…:2)
    at x (jquery.js?v=5ca7582…:4)
    at XMLHttpRequest.<anonymous> (jquery.js?v=5ca7582…:4)
```

## Steps to Reproduce (for bugs)
1. Go to Workers - Try and Add Workers

## Logs
Please let me know which log files need to be posted

## Context
Unable to add workers

## Your Environment
* Installation method used: Git
* Version/branch used: Current
* Operating System and version (like Kali, Debian, ArchLinux, etc): Ubuntu
* pip/setuptools version: pip 9.0.1
* sudo access: Yes

**Comment by viyatb** [comment]
@CreativeWolf can you provide UI logs from `/tmp/owtf`?

**Comment by viyatb** [comment]
@CreativeWolf did you resolve the issue?

**Comment by CreativeWolf** [comment]
@viyatb Heya, sorry wasn't able to spend time on this last few days. 

Had done nothing after that but I was able to add 2 workers today right after starting owtf and right after trying to run a plugin, again tried adding workers, back to the same issue.

Here's log from ui_server.log - https://pastebin.com/KiSJrQ9z

**Comment by viyatb** [comment]
@CreativeWolf from the log file, I can infer this:
The main problem I think are the PostgreSQL Python adapter "SSL" error which from https://devcenter.heroku.com/articles/postgres-logs-errors#pgerror-ssl-syscall-error-eof-detected is due to incorrect engine creation with multi-processing in the framework.

**Comment by CreativeWolf** [comment]
@viyatb Is there something that I can do to fix this issue from my end? Any pointers please?

**Comment by viyatb** [comment]
@CreativeWolf I don't think so. This is a problem we identified before we switched to using pooling in SQLAlchemy. I am reverting that commit to disable pooling.

**Comment by viyatb** [comment]
@CreativeWolf fix has been pushed to develop in https://github.com/owtf/owtf/commit/f2b11188548832d1400ecb4a871f49b423d677f5. Let me know if you have any more problems.
