### ISSUE TITLE
Incorrect nikto ssl switch check

### ISSUE THREAD

**Issue by nicolabressan** [owtf/owtf#847]
The following part of run_nikto.sh script is used to check if website provides SSL to determine if -ssl switch for nikto should be used:

```
SSL_HANDSHAKE_LINES=$(sleep 5 ; echo -e "^C" 2> /dev/null | openssl s_client -connect "$HOST_NAME":"$PORT" 2> /dev/null | wc -l)
if [ "$SSL_HANDSHAKE_LINES" -gt 15 ]; then # SSL Handshake successful, proceed with nikto -ssl switch
```

## Expected Behavior

-ssl switch should not be added while website doesn't support ssl on a specific port

## Current Behavior

testing the output of openssl s_client -connect for being greater of 15 lines to be sure that SSL is accepted on a port it's not a correct check, I have a website who is not using ssl on a port but the output of that command is greater than 15 lines, examble:

```
root@kali-box:~# openssl s_client -connect UNDISCLOSED-HOST:80
CONNECTED(00000003)
139999231132864:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:252:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1492769811
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
root@kali-box:~#
```

this is 28 lines in output, but the port doesn't accept SSL, so the check it's wrong. In fact the nikto script launches it with the ssl option and it fails.

## Possible Solution

maybe a better check could be grepping for the word "ESTABLISHED" in the answer, something like:

```
SSL_HANDSHAKE_LINES=$(sleep 5 ; echo -e "^C" 2> /dev/null | openssl s_client -connect "$HOST_NAME":"$PORT" -brief 2>&1 | grep "ESTABLISHED" | wc -l)
if [ "$SSL_HANDSHAKE_LINES" -gt 0 ]; then # SSL Handshake successful, proceed with nikto -ssl switch
        NIKTO_SSL="-ssl"
fi

```
## Steps to Reproduce (for bugs)

1. test against f.e. www.google.it port 80 (it should return 28 lines from the openssl test and so nikto will be run with the -ssl switch leading to a:

```
- Nikto v2.1.6
---------------------------------------------------------------------------
+ No web server found on www.google.it:80
---------------------------------------------------------------------------
+ 0 host(s) tested
```

## Your Environment

* Installation method used: bootstrap
* Version/branch used: 2.1a (while it still report 2.0a...dunno why)
* Operating System and version (like Kali, Debian, ArchLinux, etc): Kali
* pip/setuptools version:
* sudo access:

**Comment by DePierre** [comment]
@nicolabressan Thanks for reporting the issue. I totally agree with you: checking if the output is larger than 15 lines is not the way to go.

**Comment by viyatb** [comment]
@nicolabressan @DePierre +1, this may been correct for when the script was written (~4 years ago!) and it has not been updated since.

@nicolabressan can you send a pull request?

**Comment by nicolabressan** [comment]
@viyatb ok did it 👍

**Comment by viyatb** [comment]
Fixed in https://github.com/owtf/owtf/commit/f2b2a3573a15af7e05b5b9e675c37fb61a2a45c8.
