### ISSUE TITLE
Add user login and signup handlers

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#852]
OWTF should provide authentication options for users to log in and securely run tests if OWTF is hosted on a public IP.

It is possible to use Tornado to provide authentication really easy as given on http://www.tornadoweb.org/en/stable/auth.html

**Comment by Tikam02** [comment]
Yeah like BEEF's  Authentication it will be more secure for users. Plus point it has many integrated Api's and other third party services which will be really great for implementing in Owtf.

**Comment by viyatb** [comment]
Added to epic issue https://github.com/owtf/owtf/issues/695.
