### ISSUE TITLE
IndexError in /owtf/scripts/ssl/reporter.py

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#862]
Running the `Testing_For_Ssl-Tls` plugin throws an `IndexError` in /owtf/scripts/ssl/reporter.py

OWTF:
```bash
Starting the postgresql service
[ ok ] Starting PostgreSQL 9.6 database server: main.
Restarting the postgresql service
[ ok ] Restarting PostgreSQL 9.6 database server: main.
CREATE ROLE
CREATE DATABASE

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
[*] OWTF Version: 2.1a, Release: Chicken Korma (Alpha) 
[-] Loading framework please wait..
[-] Loading Resources from: /root/.owtf/configuration/resources.cfg..
[-] Loading Mapping from: /root/.owtf/configuration/mappings.cfg..
[*] 0.0.0.0:8008 <-- HTTP(S) Proxy to which requests can be directed
[*] http://0.0.0.0:8009 <-- Web UI URL
[-] Press Ctrl+C when you spawned a shell ;)
[-] __________ 1 - Target: http://192.168.1.59 -> Plugin: Visit Urls (web/active) __________
[-] 0 URLs were visited
[-] __________ 2 - Target: http://192.168.1.59 -> Plugin: Application Discovery (web/active) __________
[-] 
[-] Executing :

[ . . . ]
cd owtf_review/targets/http__192.168.1.59/partial/Testing_For_Ssl-Tls/active;/owtf/tools/restricted/ssllabs-scan/ssllabs-scan http://192.168.1.59 > SSL_TLS_testing_functionality_from_SSLLabs.json; /owtf/scripts/ssl/reporter.py SSL_TLS_testing_functionality_from_SSLLabs.json


[-] 
[-] ------> Execution Start Date/Time: 31/07/2017-11:48
[-] 
[*] 2017/07/31 11:48:14 [INFO] SSL Labs v1.29.2 (criteria version 2009o)
[*] 2017/07/31 11:48:14 [NOTICE] Server message: This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://www.ssllabs.com/about/terms.html
[*] 2017/07/31 11:48:16 [INFO] Assessment starting: http://192.168.1.59
[*] 2017/07/31 11:48:17 [INFO] All assessments complete; shutting down
[*] Traceback (most recent call last):
[*] File "/owtf/scripts/ssl/reporter.py", line 13, in <module>
[*] if data[0]['status'] == 'ERROR':
[*] IndexError: list index out of range
[-] Time=4s,  87ms
[-] 
[-] Executing :

cd owtf_review/targets/http__192.168.1.59/partial/Testing_For_Ssl-Tls/active;/usr/bin/o-saft +cipher --force-openssl 192.168.1.59 --port 80
```

Setup:
```
---> Starting metasploitable2
-> ip 192.168.1.59
----> on web app : target view : add target 192.168.1.59
----> click on ip address
----> click on run plugins
----> click on launch in group - web - active - RUN
```

Thanks @nico34 for reporting the issue

**Comment by viyatb** [comment]
@DePierre @nico34 Thanks for the report! I am looking at alternative ways to create a HTML report which does not involve OWTF maintaining the script since it breaks regularly.

**Comment by Tikam02** [comment]
The main Error is this :  
[*] File "/owtf/scripts/ssl/reporter.py", line 13, in <module>
[*] if data[0]['status'] == 'ERROR':
[*] IndexError: list index out of range

but when running manually -- cd owtf_review/targets/http__192.168.1.59/partial/Testing_For_Ssl-Tls/active;/usr/bin/o-saft +cipher --force-openssl 192.168.1.59 --port 80

It gives warning on SSL version checks: 

![ssl-tls](https://user-images.githubusercontent.com/10548085/28820748-c4a5cda6-7680-11e7-9bf5-019c74ddafd5.png)

**Comment by Tikam02** [comment]
I think issue ia about the version problem.
Because in my system its not showing any error in reporter.py.
![ssl-tls1](https://user-images.githubusercontent.com/10548085/28823379-48375a22-768b-11e7-9058-16bab518ba79.png)

![ssl-tls-v](https://user-images.githubusercontent.com/10548085/28823522-fc3386b8-768b-11e7-8736-02ed36bb7486.png)

**Comment by viyatb** [comment]
@Tikam02 it is the SSL labs reporting script which is failing not O-saft. 
@DePierre ^

**Comment by DePierre** [comment]
@viyatb No idea. I just pasted the logs from @nico34, hoping it would be enough to reproduce the error.

**Comment by viyatb** [comment]
Closed in https://github.com/owtf/owtf/commit/90d18ea4252e5507e623acb0cdd76bbd03161a82.
