### ISSUE TITLE
Stored XSS in Worker Log

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#865]
There is a stored XSS when accessing the worker logs in the web UI. When you click on the worker log to see ALL lines, valid HTML/JS will not be escaped, leading to the XSS.

The following worker log contain a simple XSS creating a pop-up with 'VULNERABLE' in there:
```bash
. . .
cd owtf_review/targets/http__192.168.1.59/partial/Nikto_Unauthenticated/active;/owtf/scripts/verify_nikto.py Nikto.txt http://192.168.1.59
. . .
[WARNING] [2017-07-31 11:49:43,101] [File 'blocking_shell.py', line 117, in shell_exec_monitor] - + /phpinfo.php' target='_blank'>/phpinfo.php?VARIABLE=<script>alert('Vulnerable')</script>' target='_blank'>/phpinfo.php' target='_blank'>/phpinfo.php?VARIABLE=<script>alert('Vulnerable')</script>: Output from the phpinfo() function was found.
. . .

```

IMO there is no impact due to the setup of OWTF running inside a container, the lack of session management, etc. But it should be fixed ASAP.

Thanks @nico34 for reporting the issue

**Comment by viyatb** [comment]
@DePierre @nico34 Thanks for the report! I'll fix this today - should be simple case of sanitizing and escaping the log output before serving through the REST API.

**Comment by viyatb** [comment]
Should be fixed in develop.
