### ISSUE TITLE
rebuild setup

### ISSUE THREAD

**Issue by peterpt** [owtf/owtf#882]
I notice that even with most dependencies installed in my linux , OWFT still goes get those dependencies to install them .
You should build a setup based on detection .
This means that before downloading and installing tools (nikto , arachni , hooper , etc ....) , the setup script should check if those tools are already installed .
A simple 

"which programexecutablebinary"
would be enough .
In case which result pops up 0 then it is installed , else it is not installed .

No everyone  installs tools from apt repositories , in my case i install the tools from git and create symlinks to a system path so i can call them .

**Comment by viyatb** [comment]
Hi @peterpt, thanks for trying out OWTF! Can you tell us what Linux distribution are you using?

**Comment by peterpt** [comment]
My linux distribution is a kali wheezy migrated to Devuan Linux .
By the way , your hopper link is dead in your script , i had to look for that version on the web and install it manually .

**Comment by viyatb** [comment]
@peterpt We support only Kali linux for out-of-box installation. Otherwise use Docker to run OWTF.
re hopper: are you talking about `hoppy` tool?

**Comment by peterpt** [comment]
yes , hoppy tool .
I think that if your script detects the tools first will be better .
At the end after everything installed i got an issue on virtual environment , which tells me to edit .bashrc
and add something .
Well , something like that , i did not had much time to deal with that issue because i have been very occupied in last days .

**Comment by viyatb** [comment]
@peterpt We are moving to a pip based installation. It will simplify the installation to a great extent. However the official supported distribution will Kali with Docker support for everything else. 
If you want to try that (fair warning - maybe unstable), go to https://github.com/owtf/owtf/tree/develop.

**Comment by peterpt** [comment]
Thanks , i  will surely test the developer version .
