### ISSUE TITLE
Convert complex configuration files to YAML

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#883]
The INI format is not every readable and there is no structure in the current configuration files. Converting them to YAML has several advantages:
- clean, simple markup
- structure with mappings and lists
- will remove much of the parsing logic in the config.py

**Comment by biggydbs** [comment]
I am willing to solve this issue.

**Comment by viyatb** [comment]
@biggydbs welcome to OWTF! Have you gone through the codebase and determine what changes should be required? This is a pretty easy task,

- [  ] Convert existing files to YAML.
- [  ] Edit the https://github.com/owtf/owtf/blob/develop/owtf/config/config.py to parse it correctly and replace the Python `ConfigParser` (which is used for .ini files) with YAML parsing.

**Comment by mzfr** [comment]
@viyatb  I am willing to solve this issue but i have few doubts:

1. Exactly which files do I need to convert ?
2. Which parser should I use for YAML parsing ?

**Comment by viyatb** [comment]
OWTF has some miscellaneous configuration files at `https://github.com/owtf/owtf/tree/new-arch/owtf/data/conf.
re parser: The standard Python YAML library, PyYAML (https://pypi.python.org/pypi/PyYAML)

**Comment by viyatb** [comment]
Fixed in https://github.com/owtf/owtf/commit/b133d0a141bbad3b8db6f5fbdafd4cedc2fe399c.
