### ISSUE TITLE
REST API documentation in Sphinx style

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#885]
OWTF provides a nice REST API for clients to communicate with OWTF and build more tools on top of the framework. It would be nice if there is Sphinx style documentation for the API. Here are a few resources to get started,
* https://pythonhosted.org/sphinxcontrib-httpdomain/#sphinxcontrib-autohttp-tornado-exporting-api-reference-from-tornado-app
* http://kartowicz.com/dryobates/2016-10/sphinx-rest-api/

**Comment by madgab** [comment]
I will take this!

**Comment by kumarabd** [comment]
I will take this up!

**Comment by viyatb** [comment]
Closed in https://github.com/owtf/owtf/commit/af7b361b86d19cc87b09109e9dc1a18d0a174ac0.
