### ISSUE TITLE
Which version to use for docker and which branch is used for development

### ISSUE THREAD

**Issue by menzow** [owtf/owtf#889]
## Expected behavior:
A successful build when using docker. I would also expect the installation to run on a Ubuntu installation that taps the kali repositories.

## Current behavior:
All branches I've tested had one or more issues when building or running the docker image. I've tried following the instructions from `README.md`, [PR(s)](https://github.com/owtf/owtf/pull/884), and [Makefile](https://github.com/owtf/owtf/blob/v2.1.1-beta/Makefile).

## Possible Solution:

1. Remove unused branches
2. Follow a single branching model
3. Ensure that documentation is up to date.

## Context:
I'm currently working on fixing the`Dockerfile` branched of `v2.1.1-beta`. I can create a PR once it's finished. I also suggest updating the docs relating Docker builds (I could include this in the PR).

There's a lot of great work being done and a lot of documentation. My issue as a new user however was that the docs don't seem to align with the new 2.X release. Following a constant branching model and limiting the sizes of PRs would help a lot in understanding the projects structure without documentation.

### Docker based installation: 
1. Check out any branch or feature tag
2. Run docker installation as described in `README.md`

## Your Environment
I've attempted installation in two different environments and tried multiple branches / tags. 

### Project:

```
Tags:
1. v2.1.1-be
2. v2.1a
3. v2.00
	
Branches:
1. Master
2. develop
3. ui-break
4. new-install
```

### Hosted VPS:

```
$ uname -a
Linux instance-2.c.clonne-168622.internal 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ docker -v
Docker version 17.09.0-ce, build afdb6d4

$ python --version
Python 2.7.13

$ pip --version
pip 9.0.1 from /home/hello/.local/lib/python2.7/site-packages (python 2.7)

$ virtualenv --version
15.1.0
```

### Local environment (only used w/ docker):
```
OS: macOS Sierra 10.12.6 

$ docker -v 
Docker version 17.06.1-ce-rc1, build 77b4dce
```

### Provisioning ubuntu installation

1. Install ubuntu on a VM or deploy a VPS with Ubuntu 14.04
2. Provision installation for use with Kali packages using the following commands;

	```
	// Commands require root privilleges
	echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" \ 
		 >> /etc/apt/sources.list.d/kali.sources.list && \
	gpg --keyserver pgpkeys.mit.edu --recv-key  ED444FF07D8D0BF6 && \
	gpg -a --export ED444FF07D8D0BF6 | apt-key add 
	```
3. Follow installation instructions as described by `README.md` 

## Logs
Since this issue covers a broad scope specific logs aren't included. I could add them based on requests.

**Comment by viyatb** [comment]
Hi @menzow,

If you want to use OWTF for testing purposes, please use the master branch (stable). If you wish to send a PR or want to participate in the development, then focus on develop (and other branches).

Now for installation, if you have a VPS with Kali packages installed, it is trivial to install OWTF without Docker. If you want to run OWTF with Docker for testing purposes, use the instructions at https://github.com/owtf/owtf-docker. The Docker instructions in the [README.md](./README.md) provide instructions for the development environment **only** (using volumes, etc.). It needs more manual configuration.

Let me know if this answers your questions.

**Comment by menzow** [comment]
Hey @viyatb,

Thanks for your fast response. It answers my confusion about which branches are used for what purpose, thanks for that. 

I've managed to do a clean install and resolve all dependency issues on `2.1.1-Beta` and `2.1a`. Both are a bit unstable, probably because of version mismatches. Could you tell me which version of Kali you use? I can use that as a reference point in resolving these issues. 

Due to my workflow I want to be able to rebuild the package in ephemeral environments. For that I'll update the `Dockerfile` in the`master` branch. Are PRs accepted there? I also have a couple of fixes for the `develop` branch that I could create PRs for. Is that branch currently up to date with all changes?

**Comment by viyatb** [comment]
`develop` is the branch me and others are working on right now with changing OWTF to a Python package format. I think all PRs should go there so that it stabilizes and I can release it as soon as I get some time to fix everything up.

**Comment by viyatb** [comment]
@menzow Let me know if you need to open this issue again.
