### ISSUE TITLE
lib64 and pycurl problems in OpenSuse... maybe other distros

### ISSUE THREAD

**Issue by spinfoo** [owtf/owtf#897]
I got several errors when installing owtf from the github repository.

First, when I run owtf.py, python failed to import several modules as time module. It seemed an issue with the 32/64-bit libraries of the virtualenv environment.

Second I got this error when executing owtf.py:

`ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)`

I did a simple script to fix that from the owtf installation path:
```
#!/bin/bash

# Usual installation fails in OpenSuse due a lib64 issue and pycurl problem

cd ~/.virtualenvs/owtf/
mv lib64/ lib64.old 
ln -s lib lib64 
cd -
./install/install.py 
source ~/.bashrc 
workon owtf
pip install --no-cache-dir --compile --ignore-installed --install-option="--with-openssl" pycurl
./owtf.py
```
Hope it helps!

**Comment by csk** [comment]
I have being playing lastly a lot with owtf installations , mostly the develop branch . Can you tell step-by-step how did you install owtf si I can check if it also happens in other Linux distributions ?

**Comment by viyatb** [comment]
Closing the issue as it is a distro specific issue.
