### ISSUE TITLE
Form-based authentication

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#90]
We have received a user request to support form-based authentication.

The easiest way to go about this is potentially from the proxy, something like:
./owtf.py --form-auth 'user_here' 'pass_here' ... http://target.com

And then prompt the user with something like:

1) "Please login using valid credentials"
We see what the request looks like and figure out what the user and password is based on the HTTP request (potential problem: JSON-encoded logins)

2) "Please login using invalid credentials"
We see what a bad login looks like, and with this information we can hopefully determine if we have been logged out or not (which should enable smarter session-management tests later).

Thoughts from the team welcome :)

**Comment by delta24** [comment]
Closing as this has been implemented for the new requester (using PhantomJS) during the OWASP Summer Code Sprint 2015.

**Comment by 7a** [comment]
ok, but maybe we need a usage tutorial or quick wiki article :D

**Comment by delta24** [comment]
Sure, yes!
