### ISSUE TITLE
Mitigation boiler plate DB

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#91]
We need a DB with boiler plate mitigation advice to improve reporting efficiency: This is one of those great ideas I had for a long time but never got a chance to implement :P.

This has also been flagged by our user base:

"I’m seeing a lot of economic pressures in my work forcing less and less time for assessments. 

Biggest problem I’ve seen so far is reporting. Explaining web vulns to non technical customers is difficult. Particularly conveying the urgency of fixing XSS and csrf is difficult.
I’d like to see boilerplate vuln explanations verbiage that can be plopped into reports. Actually storing it in database would be nice then flowing it into a msoft word doc "

The ideal scenario would perhaps be either mitigation plugins OR mitigation templates that can be loaded from the reporting rich editor (or surroundings) clicking a button or similar. Of course, additional ideas welcome :)

**Comment by delta24** [comment]
Initial implementation in [owtf/boilerplate-templates](http://github.com/owtf/boilerplate-templates)
