### ISSUE TITLE
Plugin "Session Management Schema" stucking for hours in Workers

### ISSUE THREAD

**Issue by ThOhT** [owtf/owtf#920]
I was running testing OWTF for the first time and runned all plugins over 22 IP's/domains. My workers stucked on this plugin and it's running for more than 8 hours and can't finishing it's work.

I tried to close workers, but didn't work.

I'm using Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.13-1kali1 (2017-11-17) x86_64 GNU/Linux.
Instalation method:  wget -N https://raw.githubusercontent.com/owtf/bootstrap-script/master/bootstrap.sh; bash bootstrap.sh

**Comment by viyatb** [comment]
Yes, that's a known problem. Try pressing Cntrl-C on the terminal and restarting OWTF. It should pick up the work from the worklist and resume.
