### ISSUE TITLE
Uninstalling documentation?

### ISSUE THREAD

**Issue by D219** [owtf/owtf#921]
After installing OWTF, I've noticed that it use Kali's repository, which then tries to pull a lot of upgrade coming from it. However, it is inconvenient in my current setup.
I wanted to uninstall OWTF from my current partition, and reinstall it on a more standard debian, but I am surprised to see no documentation on how to uninstall.

As a last resort, I could make a list of all packages OWTF install, and uninstall them, and remove the owtf folder, but that would be long and tedious. Is there a uninstallation method I missed somewhere in the documentation?

**Comment by viyatb** [comment]
Which platform are you using? We won't be supporting installation of miscellaneous tools on distros other than Kali linux. If you do not have a Kali VM/host, try running OWTF using the Dockerfile provided.

**Comment by D219** [comment]
Debian Jessie, I ve naively installed with ` wget -N https://raw.githubusercontent.com/owtf/bootstrap-script/master/bootstrap.sh; bash bootstrap.sh `, as recommended in https://owtf.github.io/#download
I ve succeeded in removing the third party tools and the Kali repo, if OWTF didn't installed elsewhere than it s own directory, and the calls to `apt install`, I should be fine :)

**Comment by viyatb** [comment]
Ah, I see. I need to update the website (https://owtf.github.io/#download) to **not** recommend using the bootstrap script.
