### ISSUE TITLE
Install via docker, can't find waffit

### ISSUE THREAD

**Issue by D219** [owtf/owtf#922]
## Current Behavior
When using `make docker-build`, the script crash because the package `waffit` is not found

## Possible Solution
A workaround is to open Dockerfile.dev and comment out `waffit` from the list of package to install.

## Your Environment

* Installation method used: Docker
* Version/branch used: latest (master/b103adef5fa2efe4352d219829ca5aac5caf4b67)
* Operating System and version (like Kali, Debian, ArchLinux, etc): Debian Stretch
* pip/setuptools version: 
- pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
- setuptools (38.4.0)
* sudo access: Yes

**Comment by viyatb** [comment]
Closed in https://github.com/owtf/owtf/commit/7adf14bfd1e54c358f94b3c42735951cf91c9b99.
