### ISSUE TITLE
ImportError at start, installed via docker

### ISSUE THREAD

**Issue by D219** [owtf/owtf#923]
Installed via docker, following exactly what is currently in the README. It does start, but crash immediately crash with a long stack trace.

## Logs

Bash history on the machine: https://ghostbin.com/paste/moxwy
Bash history in docker: https://ghostbin.com/paste/c24nm
Stack trace: https://ghostbin.com/paste/g58no

## Your Environment

* Installation method used: Docker
* Version/branch used: Latest
* Operating System and version (like Kali, Debian, ArchLinux, etc): Debian Stretch
* pip/setuptools version: 
- pip 9.0.1 from /env/local/lib/python2.7/site-packages (python 2.7)
- setuptools (38.4.0)
* sudo access: In the docker, directly as root

**Comment by viyatb** [comment]
@D219 somehow PostgreSQL in your container is not running. Try starting it manually by,
`service postgresql start`.

**Comment by D219** [comment]
I had to remove the package first, but owtf did started (and crashed because of a misconfiguration of Postgres). Currently redoing the installation from scratch to try properly.

**Comment by D219** [comment]
Okay, I finally got OWTF to start after manually creating the user and db (for some reason, `make db-run` don t detect the instance of postgres, and didn't create the user nor db).

However, the connection is reset when I try to open the link (127.0.0.1:8009), idem for port 8008 and 8010. I ll file a new issue for this.
