### ISSUE TITLE
How to install a plugin (specifically https://github.com/owtf/login-sessions-plugin) ?

### ISSUE THREAD

**Issue by zWaR** [owtf/owtf#924]
Hey there,

I am sorry if this question is not acceptable among the issues, but the truth is, I do not know where else to ask. I've checked the user documentation and your gitHub wiki and did not find documentation which would help me to install a plugin. There is pretty good documentation on how to use the installed plugins though ...

In particular I'd like to use https://github.com/owtf/login-sessions-plugin. I need form based authentication w/ session cookies in the tests. (btw. i am using the recommended installation method for owtf (v2.1a) as per: https://github.com/owtf/owtf/wiki/OWASP-OWTF-Installation on Kali linux).

If possible give me some pointers or direct me to plugin installation specific documentation.

Thank you!

**Comment by viyatb** [comment]
Hi @zWaR, that specific is not functional  and cannot be integrated with OWTF in its current state. I suggest you use OWASP https://github.com/zaproxy/zaproxy as an proxy for OWTF (thus replacing the packaged OWTF proxy). ZAP's implementation is stable and works great.

**Comment by zWaR** [comment]
@viyatb Thank you for your prompt reply! I'll checkout zaproxy!
