### ISSUE TITLE
Improper orientation of page describing individual targets 

### ISSUE THREAD

**Issue by sharmamohit123** [owtf/owtf#926]
## Expected Behavior
Appeared page should completely fit into the screen and there should be no need to scroll until required.

## Current Behavior
After opening a target from the target page, the window that appears is not screen fit instead we have to 
do unneccesary scrolling to see all the elements on the screen.

## Steps to Reproduce (for bugs)
1. Open the target page from the nav bar.
2. Select a target from the listed targets.
![screenshot from 2018-02-27 19-36-58](https://user-images.githubusercontent.com/31919606/36733236-f87671f6-1bf5-11e8-83a2-d7f922afc93e.png)

##  Operating System and version
Ubuntu 16.04

#### Would you like to work on this issue?
Yes

**Comment by viyatb** [comment]
Closed in favor of meta-issue #695.
