### ISSUE TITLE
multiprocessing deadlock

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#93]
There is a multiprocessing deadlock bug. The plugins somehow block each other and OWTF halts.

Steps:

Scan a huge scope, like 94 urls:

owtf.py file_with_94_urls.txt

Expected result:

OWTF eventually completes without issues

Actual result:

OWTF gets stuck due to deadlocks despite the URLs being reachable.

Related bugs:

Apart from the deadlock issue, the "s" + enter approach is very messy and does not work: After a few "stop tests for target" and "stop plugin" tries, I had to control + C due to 0 progress :(

**Comment by DePierre** [comment]
IMHO this has been fixed since 2013 with the whole new internal gears developed over the past couple of years.
