### ISSUE TITLE
Configure a proper production build for react.

### ISSUE THREAD

**Issue by fristonio** [owtf/owtf#937]
When currently react web app is built in production mode console shows the following error:

### Steps to reproduce.
Run webapp in production mode.
- Go to `./owtf/webapp`
- Run `yarn prod` and `owtf`

### Screenshots
![image](https://user-images.githubusercontent.com/21292343/37181357-9c8ef368-2352-11e8-9937-53eb83888058.png)

**Comment by saganshul** [comment]
Try, `yarn run prod` now.

**Comment by fristonio** [comment]
OK, I should have mentioned that I have a patch for this. Thanks though for fixing. :)

**Comment by saganshul** [comment]
Oh! I thought you are suggesting that we should have production configuration. Never mind!

**Comment by fristonio** [comment]
Fixed by #938
