### ISSUE TITLE
OWTF does not exit cleanly when PostgreSQL server is not running.

### ISSUE THREAD

**Issue by fristonio** [owtf/owtf#953]
owtf when run with PostgreSQL not running does not exit cleanly and prints sqlalchemy tracebacks. 

## Expected Behavior
The correct behaviour should make owtf exit cleanly with an error log that postgres server is not running.

## Current Behavior
owtf prints Traceback to the console.

## Possible Solution
owtf should catch the exception raised by SQLAlchemy to print error that postgres server is not running.

## Steps to Reproduce (for bugs)

1. Stop postgres server running using `sudo service postgres stop`
2. Try running owtf

## Logs
https://pastebin.com/dLJEnWXS

## Your Environment

* Installation method used: Installation script
* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): Debian
* Python version:  3.5.4

**Comment by viyatb** [comment]
This should be caught at https://github.com/owtf/owtf/blob/develop/owtf/db/database.py#L43.

**Comment by fristonio** [comment]
Yes, that would be the place I will create a pull request as soon as possible regarding the same :)

**Comment by viyatb** [comment]
Closed in https://github.com/owtf/owtf/commit/d0f2958f1994afd5c71526c5fc648851184ac94f.
