### ISSUE TITLE
Upgrade psycopg2 version to 2.7.4

### ISSUE THREAD

**Issue by fristonio** [owtf/owtf#959]
Currently psycopg2 in `requirements.txt` is using version 2.7.2 which has a known issue  in some distros. 
https://github.com/psycopg/psycopg2-wheels/issues/2 

This issue can be resolved by simply upgrading psycopg2 to version 2.7.4 and since this version upgrade is not conflicting we can do it.

## Your Environment

* Installation method used: `python setup.py develop`
* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): ArchLinux
* python version: 3.6

**Comment by viyatb** [comment]
Closed in https://github.com/owtf/owtf/commit/d06b9f872e69b492126c2ed16b2b0a62d7bf7696.
