### ISSUE TITLE
Issues on execution flow UI: Command zombies and inability to stop individual commands

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#97]
The execution flow UI needs some clean-up. There are 2 serious bugs:

1) Failure to stop commands when the caller plugin is stopped

I stopped 2 "Infrastructure_Configuration_Management/active" plugins to then see (after like 20 minutes or so, while OWTF was already scanning other targets -same 94 url scope-) the "lbd" load balancer check command still running (!).

Possibly more plugins are affected, this seems a bug in the multiprocessing code to stop a plugin: The plugin seems to be stopped but the underlying command is not.

2) Missing feature: Before the GSoC there was an option to "stop command", because sometimes, a plugin may run several commands and we might want to stop just 1 of those (i.e. a tool that is stuck). This feature is missing and needs to be added back.

After stopping OWTF I got the following zombie processes (from same terminal):

$ ps
  PID TTY          TIME CMD
10789 pts/10   00:00:00 nc
10791 pts/10   00:00:00 nc
10794 pts/10   00:00:00 nc
10797 pts/10   00:00:00 ps
11982 pts/10   00:00:00 lbd
13034 pts/10   00:00:00 lbd
15682 pts/10   00:00:00 bash
24577 pts/10   00:00:00 lbd

**Comment by DePierre** [comment]
I am not sure that the problem has been completely fixed but I have spent a semester trying to implement some testing framework for OWTF and along the way I have fixed numerous problems related to this issue.

I feel that it has been fixed now (but as I opened with, I am not sure of it).
