### ISSUE TITLE
FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by BBQ2000** [owtf/owtf#973]
I am attempting to install OWTF on Kali Linux (4.14.0-kali3-amd64) and upon running OWTF I get the error:

FATAL:  password authentication failed for user "owtf_db_user"

![image](https://user-images.githubusercontent.com/38767059/39330278-19ca2694-496f-11e8-8854-a16b4b15e56c.png)

## Expected Behavior

The behavior that is expected is for OWTF to run without the error

## Current Behavior

Currently, OWTF fails to run.

## Possible Solution

Maybe try a different version of Kali?

## Steps to Reproduce (for bugs)

* Replace 'peer' with 'md5 in /etc/postgresql/10/main/pg_hba.conf
* Download bootstrap.sh using: wget https://raw.githubusercontent.com/owtf/bootstrap-script/master/bootstrap.sh
* Run bootstrap.sh with: bash bootstrap.sh
* Start virtualenv with: source ~/.bashrc; workon owtf
* Upgrade virtualenv using the command: pip install virtualenv --upgrade
* Install pip 9.0.1 with: pip install pip==9.0.1
* Run OWTF with: /owtf/owtf.py

## Your Environment

* Installation method used: wget bootstrap.sh
* Version/branch used: 2.1
* Operating System and version (like Kali, Debian, ArchLinux, etc): Kali
* pip/setuptools version: pip 9.0.1
* sudo access:

**Comment by viyatb** [comment]
Please install OWTF (latest master branch) with `python setup.py install`.
