### ISSUE TITLE
[refactor] Generate queries for model data 

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#979]
To filter and output data according to user queries (on the web interface), there are separate `{model}_gen_query` methods in the respective manager modules (`owtf/managers`). There should a simple search query API around SQLAlchemy that allows for similar functionality without repeating code everywhere.

Flask-Restless (https://github.com/jfinkels/flask-restless/tree/master/flask_restless/search) has a good search API based on attribute, operator (`lt`, `gt`, `or`, `like`) and the value provided in the `filter_data`. The API is documented [here](https://flask-restless.readthedocs.io/en/stable/searchformat.html).

More resources:

* http://ruddra.com/2015/09/18/dynamically-constructing-filters-based-on-string-input-using-sqlalchemy/

**Comment by ankitkataria** [comment]
Hey @viyatb ! I'm an open source enthusiast and would really love to make my first contribution to the project. Could I work on this issue?

**Comment by viyatb** [comment]
@ankitkataria yep, welcome to OWTF! Let me know if you have any questions :)

**Comment by viyatb** [comment]
Fixed by using `sqlchemy_mixins` - can now use Django ORM like queries!
