### ISSUE TITLE
Receives "Connection refused" when trying to launch OWTF with docker-compose

### ISSUE THREAD

**Issue by testingplusme** [owtf/owtf#981]
I tried to install owtf by docker-compose. I tried on both systems. One it was my personal laptop which was windows second it was fresh instance from DigitalOcean.
Do you have any idea what I should do?
![image](https://user-images.githubusercontent.com/17097924/39991433-781aafce-5767-11e8-96b9-e3f1922c907d.png)

Ofc, I had PowerShell in administrator mode.
Cheers,
Michał

**Comment by viyatb** [comment]
@testingplusme thanks for the report! - investigating it right now.

**Comment by testingplusme** [comment]
@viyatb  Thanks 👍 I'm waiting for it, because I want to use it  :)

**Comment by viyatb** [comment]
If you want to use the web interface, try using https://github.com/owtf/owtf-docker.

- `git clone https://github.com/owtf/owtf-docker`
- `cd owtf-docker; docker build -t <name> .`
- `docker run -it -p 8009:8009 -p 8008:8008 -p 8010:8010 <name>`

**Comment by testingplusme** [comment]
Thank you @viyatb  cheers !

**Comment by viyatb** [comment]
https://github.com/owtf/owtf/commit/6ccfe39d00439b774e9c3e09fc590186e1e96fb3 should fix the port errors.
