### ISSUE TITLE
After install, Python error - No such file or directory: '/usr/local/lib/python2.7/dist-packages/owtf-2.3.2-py2.7.egg/owtf/webapp/build/index.html'

### ISSUE THREAD

**Issue by r3naissance** [owtf/owtf#982]
I had numerous errors when attempting to install, however, I was able to overcome some of them by changing version numbers of the pip requirements, specifically PyCurl. It also seems the environment for the various scripts is using sh as the shell but I get errors and it seems like it should be using bash. I had to change the scripts to use bash instead and everything installed correctly.

However, now when running python -m owtf, everything starts up fine, but I get this error when browsing to index.html:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/owtf-2.3.2-py2.7.egg/owtf/api/handlers/index.py", line 35, in get
    self.render("index.html")
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 750, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 888, in render_string
    t = loader.load(template_name)
  File "/usr/lib/python2.7/dist-packages/tornado/template.py", line 425, in load
    self.templates[name] = self._create_template(name)
  File "/usr/lib/python2.7/dist-packages/tornado/template.py", line 452, in _create_template
    with open(path, "rb") as f:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/owtf-2.3.2-py2.7.egg/owtf/webapp/build/index.html'
```

## Possible Solution
The OWTF repo has a structure as owtf/webapp/src/*
The server is looking for owtf/webapp/build

I've attempted to create symlinks to the location that the server is looking for. I get further and get the 'Loading Application' screen but nothing progresses.

## Steps to Reproduce (for bugs)
1. Git clone https://github.com/owtf/owtf
2. cd owtf/
3. python setup.py

## Your Environment
* Installation method used: git clone, modified some dependencies, then python setup.py install
* Version/branch used: master and develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): Kali 2018.2
* pip/setuptools version: 9.0.1
* sudo access: running as root

**Comment by r3naissance** [comment]
@viyatb, thank you for the quick response. I appreciate your time to help out. I'll give it a shot. I didn't see any errors on build but I'll double check in either event.

**Comment by r3naissance** [comment]
I did see this error on installing:

error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".                                                                                                                
error Found incompatible module

**Comment by r3naissance** [comment]
Solved my issue. Edited owtf/webapp.yarn.lock with updated upath

````
upath@^1.0.0:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/upath/-/upath-1.1.0.tgz#35256597e46a581db4793d0ce47fa9aebfc9fabd"

**Comment by r3naissance** [comment]
I abandoned the install via git clone && python setup.py install. I instead used the develop branch and used

`docker-compose up` 

Now I'm getting this error:

```db_1    | performing post-bootstrap initialization ... sh: locale: not found
db_1    | 2018-05-19 03:02:01.183 UTC [30] WARNING:  no usable system locales were found
db_1    | ok
owtf_1  | [-] Could not create database engine - Exception occured
owtf_1  | (psycopg2.OperationalError) could not connect to server: Connection refused
owtf_1  | 	Is the server running on host "db" (172.18.0.2) and accepting
owtf_1  | 	TCP/IP connections on port 5342?
owtf_1  |  (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by viyatb** [comment]
@r3naissance I am still checking up on the `docker-compose` issue - I might not be able to push a fix before end of next week since I'm traveling. I've tested the Docker image and the web interface works perfectly.
`docker pull owtf/owtf` and `docker run -it -p 8009:8009 -p 8008:8008 -p 8010:8010 owtf/owtf`

**Comment by r3naissance** [comment]
As always @viyatb, thank you for your time and effort!

**Comment by r3naissance** [comment]
The reason I was attempting the git install method is because I would get an error running Arachni and Wapiti. The install would work and every other tool would work just not these two. Even though they are installed and configured as they are in the settings. Running them manually from the command line works...

[*] [*] Running: /usr/share/arachni/bin/arachni --http-user-agent="Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0" --http-request-concurrency=20 --report-save-path="arachni_report2018-05-19_15_19_11.afr" --http-proxy=0.0.0.0:8008 http://testphp.vulnweb.com
[*] /owtf/owtf/scripts/run_arachni.sh: 33: /owtf/owtf/scripts/run_arachni.sh: /usr/share/arachni/bin/arachni: not found

AND

[*] [*] Running: /usr/bin/wapiti http://testphp.vulnweb.com -f xml --output wapiti_report2018-05-19_15_28_25.xml
[*] Traceback (most recent call last):
[*] File "/usr/bin/wapiti", line 41, in <module>
[*] lan.configure()
[*] File "/usr/lib/python2.7/dist-packages/wapitiCore/language/language.py", line 58, in configure
[*] lang = langCounty[:2]  # en
[*] TypeError: 'NoneType' object has no attribute '__getitem__'

I have a fork that I'm working on as well, I'll be sure to update if I find anything in the mean time. Enjoy your weekend!

**Comment by viyatb** [comment]
@r3naissance thanks for the debugging this! I think the paths to the Kali tools have changed - I'll push a fix with the updates soon or you can send a PR!

**Comment by viyatb** [comment]
@r3naissance https://github.com/owtf/owtf/commit/1f054ba83339eb85acb3d89e64b630ea3aedbaff should fix the Arachni path issues. Sorry for taking so long to get the fix out!

**Comment by viyatb** [comment]
https://github.com/owtf/owtf/commit/2bf691481a4c9ef950371bf4af4462633499c91a should resolve the Wapiti locale issue. Thanks for reporting this!
