### ISSUE TITLE
Python setup.py install fails

### ISSUE THREAD

**Issue by guyenko** [owtf/owtf#984]
"Error: you need to install postgresql-server-dev-X.Y for  building  a server side- extension or libpq-dev for building a client-side application.
OS= Kali Linux
## Expected Behavior

It should install without any errors

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Installation method used: 
Followed the instruction in the OWTF project documentation. 
* Version/branch used:
* Operating System and version (like Kali, Debian, ArchLinux, etc):
OS= Kali Linux
* pip/setuptools version:
* sudo access: Yes

**Comment by viyatb** [comment]
@guyenko `apt-get install postgresql-server-dev-<X.Y>` should let you build the Postgres driver.
