### ISSUE TITLE
owtf failed to start with "Error TypeError: main() takes exactly 1 argument (0 given)"

### ISSUE THREAD

**Issue by lmcthbe** [owtf/owtf#991]
## Current Behavior

After installed owtf from git with no issues on Kali-rolling. owtf failed so start with errors

## Steps to Reproduce (for bugs)

1. git clone https://github.com/owtf/owtf.git
2.cd owtf
3.python setup.py install
4.owtf

## Logs

Traceback (most recent call last):
  File "/usr/local/bin/owtf", line 11, in <module>
    load_entry_point('owtf==2.3.2', 'console_scripts', 'owtf')()
TypeError: main() takes exactly 1 argument (0 given)

## Environment

* Installation method used: git
* Version/branch used: latest
* Operating System and version : Kali-rolling (updated yesterday)
* pip/setuptools version: pip 10.0.1
* sudo access: root

**Comment by viyatb** [comment]
@lmcthbe thanks for reporting this! Normally, during `python setup.py install`, the script in `bin/` directory should be used as the entrypoint. It seems that the `console_scripts` is overriding the `scripts` to be the entrypoint (https://github.com/owtf/owtf/blob/develop/setup.py#L99).

This should be an easy fix.

**Comment by viyatb** [comment]
Fixed in https://github.com/owtf/owtf/commit/3b59f2ddfec36f8ca5b58deb85018de0bbacd137.

**Comment by viyatb** [comment]
@lmcthbe please let me know if this worked for you.

**Comment by viyatb** [comment]
@lmcthbe that's weird. Can you `cd owtf/webapp` and do `yarn run` to regenerate the assets and see if it fixes the problem?

**Comment by lmcthbe** [comment]
@viyatb I had to execute  /root/.nvm/versions/node/v10.7.0/bin/yarn run from /owtf/owtf/webapp and got this
yarn run v1.7.0
warning package.json: License should be a valid SPDX license expression
error There are no binary scripts available.
info Project commands
   - build
      NODE_ENV=production webpack --config webpack/prod.config.js --color -p --progress --hide-modules --display-optimization-bailout
   - precommit
      pretty-quick --staged
   - start
      NODE_ENV=development node server
question Which command would you like to run?:
