### ISSUE TITLE
Error on dependancies (Kali linux)

### ISSUE THREAD

**Issue by Dark056** [owtf/owtf#993]
I installed owrf and ran the ./owrf.py. 

root@kali:~/owtf# uname -a
Linux kali 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux

**Im fairly new to linux but here is the error im getting** 
root@kali:~/owtf# ./owtf.py
Traceback (most recent call last):
  File "./owtf.py", line 12, in <module>
    from framework.dependency_check import verify_dependencies
  File "/root/owtf/framework/dependency_check.py", line 14, in <module>
    pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'

**Comment by ThOhT** [comment]
Did you try this command inside the owtf folder?
`pip install -r requirements.txt`

**Comment by viyatb** [comment]
@Dark056 are you using an old version of OWTF? You should be using the latest develop branch.

**Comment by viyatb** [comment]
Closing since this is related to an old OWTF release (not supported anymore).
